// apps/web/src/components/workspace/node/blocks/workspace-checklist-block-editor.tsx
import {
  createWorkspaceChecklistItem,
  getChecklistProgress,
  type WorkspaceChecklistBlock,
} from "@brainiac/workspace";
import { Plus, Trash2 } from "lucide-react";
import { useMemo } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { BlockCheckbox } from "@/components/workspace/node/blocks/shared/block-checkbox";
import { BlockProgressBar } from "@/components/workspace/node/blocks/shared/block-progress-bar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function WorkspaceChecklistBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceChecklistBlock>) {
  const { mutateTypedBlock } = useWorkspaceNodeEditorContext();

  const progress = useMemo(() => getChecklistProgress(block), [block]);
  const openItemCount = Math.max(progress.total - progress.completed, 0);

  function mutateChecklistItem(
    itemId: string,
    mutator: (item: WorkspaceChecklistBlock["items"][number]) => void,
  ) {
    mutateTypedBlock(tabId, block.id, "checklist", (entry) => {
      const target = entry.items.find((candidate) => candidate.id === itemId);
      if (!target) {
        return;
      }
      mutator(target);
    });
  }

  function addItem() {
    mutateTypedBlock(tabId, block.id, "checklist", (entry) => {
      entry.items.push(createWorkspaceChecklistItem({ text: "" }));
    });
  }

  return (
    <div className="space-y-6">
      <div className="space-y-4 rounded-3xl border border-muted/20 bg-muted/10 p-5">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-6">
            <div className="flex size-14 shrink-0 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10 text-primary">
              <span className="text-lg font-black tracking-tight">{progress.percent}%</span>
            </div>

            <div className="flex-1 space-y-2">
              <div className="flex items-center justify-between gap-2">
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                  Completion
                </p>
                <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/40">
                  {progress.completed}/{progress.total}
                </p>
              </div>
              <BlockProgressBar value={progress.completed} max={Math.max(progress.total, 1)} />
            </div>
          </div>

          <Button
            type="button"
            variant="secondary"
            className="rounded-full px-4"
            aria-label="Add checklist item"
            onClick={addItem}
          >
            <Plus />
            Add Item
          </Button>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="secondary" className="rounded-2xl">
            {progress.completed} completed
          </Badge>
          <Badge variant="secondary" className="rounded-2xl">
            {openItemCount} open
          </Badge>
          <Badge variant="secondary" className="rounded-2xl">
            {progress.total} total
          </Badge>
        </div>
      </div>

      <div className="space-y-2">
        {block.items.map((item) => (
          <div
            key={item.id}
            className="flex items-center gap-3 rounded-2xl border border-muted/20 bg-background/40 p-3 transition-all hover:border-primary/20 hover:bg-background/60"
          >
            <BlockCheckbox
              checked={item.completed}
              aria-label={
                item.completed ? "Mark checklist item as open" : "Mark checklist item as complete"
              }
              onCheckedChange={(checked) =>
                mutateChecklistItem(item.id, (entry) => {
                  entry.completed = checked;
                })
              }
            />

            <Input
              value={item.text}
              placeholder="Checklist item"
              className={`flex-1 border-0 bg-transparent px-0 font-medium shadow-none focus-visible:ring-0 ${item.completed ? "text-muted-foreground/60 line-through" : "text-foreground"}`}
              onChange={(event) =>
                mutateChecklistItem(item.id, (entry) => {
                  entry.text = event.target.value.slice(0, 240);
                })
              }
            />

            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="rounded-lg text-muted-foreground/70 hover:text-destructive"
              aria-label="Delete checklist item"
              onClick={() =>
                mutateTypedBlock(tabId, block.id, "checklist", (entry) => {
                  entry.items = entry.items.filter((candidate) => candidate.id !== item.id);
                })
              }
            >
              <Trash2 />
            </Button>
          </div>
        ))}

        {block.items.length === 0 ? (
          <div className="rounded-3xl border border-dashed border-muted/20 bg-muted/5 py-12 text-center">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/40">
              No checklist items yet
            </p>
            <p className="mt-2 text-sm text-muted-foreground">
              Add the first item to start tracking completion.
            </p>
          </div>
        ) : null}
      </div>
    </div>
  );
}

// apps/web/app/components/workspace/node/blocks/WorkspaceChecklistBlockEditor.vue
<script setup lang="ts">
import {
    createWorkspaceChecklistItem,
    getChecklistProgress,
    type WorkspaceChecklistBlock,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
    block: WorkspaceChecklistBlock;
    tabId: string;
}>();

const { mutateTypedBlock } = useWorkspaceNodeEditorContext();

const progress = computed(() => getChecklistProgress(props.block));
const openItemCount = computed(() =>
    Math.max(progress.value.total - progress.value.completed, 0),
);

function mutateChecklistItem(
    itemId: string,
    mutator: (item: WorkspaceChecklistBlock["items"][number]) => void,
) {
    mutateTypedBlock(props.tabId, props.block.id, "checklist", (entry) => {
        const target = entry.items.find((candidate) => candidate.id === itemId);

        if (!target) {
            return;
        }

        mutator(target);
    });
}

function addItem() {
    mutateTypedBlock(props.tabId, props.block.id, "checklist", (entry) => {
        entry.items.push(createWorkspaceChecklistItem({ text: "" }));
    });
}

function updateItemCompleted(
    itemId: string,
    value: boolean | string | undefined,
) {
    mutateChecklistItem(itemId, (item) => {
        item.completed = Boolean(value);
    });
}

function updateItemText(itemId: string, value: string | number | undefined) {
    mutateChecklistItem(itemId, (item) => {
        item.text = String(value ?? "").slice(0, 240);
    });
}

function removeItem(itemId: string) {
    mutateTypedBlock(props.tabId, props.block.id, "checklist", (entry) => {
        entry.items = entry.items.filter(
            (candidate) => candidate.id !== itemId,
        );
    });
}
</script>

<template>
    <div class="space-y-6">
        <div
            class="space-y-4 rounded-3xl border border-muted/20 bg-elevated/10 p-5"
        >
            <div class="flex flex-wrap items-center justify-between gap-4">
                <div class="flex items-center gap-6">
                    <div
                        class="flex size-14 shrink-0 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10 text-primary"
                    >
                        <span class="text-lg font-black tracking-tight"
                            >{{ progress.percent }}%</span
                        >
                    </div>

                    <div class="flex-1 space-y-2">
                        <div class="flex items-center justify-between gap-2">
                            <p
                                class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                            >
                                Completion
                            </p>
                            <p
                                class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/40"
                            >
                                {{ progress.completed }}/{{ progress.total }}
                            </p>
                        </div>
                        <UProgress
                            :model-value="progress.completed"
                            :max="Math.max(progress.total, 1)"
                            size="sm"
                            class="rounded-full"
                            color="primary"
                        />
                    </div>
                </div>

                <UButton
                    color="primary"
                    variant="soft"
                    icon="i-lucide-plus"
                    class="rounded-full px-4"
                    aria-label="Add checklist item"
                    @click="addItem"
                >
                    Add Item
                </UButton>
            </div>

            <div class="flex flex-wrap items-center gap-2">
                <UBadge variant="subtle" class="rounded-2xl">
                    {{ progress.completed }} completed
                </UBadge>
                <UBadge color="neutral" variant="soft" class="rounded-2xl">
                    {{ openItemCount }} open
                </UBadge>
                <UBadge color="neutral" variant="soft" class="rounded-2xl">
                    {{ progress.total }} total
                </UBadge>
            </div>
        </div>

        <div class="space-y-2">
            <div
                v-for="item in block.items"
                :key="item.id"
                class="flex items-center gap-3 rounded-2xl border border-muted/20 bg-default/40 p-3 transition-all hover:border-primary/20 hover:bg-default/60"
            >
                <UCheckbox
                    :model-value="item.completed"
                    size="sm"
                    class="shrink-0"
                    :aria-label="
                        item.completed
                            ? 'Mark checklist item as open'
                            : 'Mark checklist item as complete'
                    "
                    @update:model-value="updateItemCompleted(item.id, $event)"
                />

                <UInput
                    :model-value="item.text"
                    variant="none"
                    placeholder="Checklist item"
                    class="flex-1"
                    :ui="{
                        base: [
                            'px-0 font-medium placeholder:text-muted/50 transition-all',
                            item.completed
                                ? 'text-muted/60 line-through'
                                : 'text-highlighted',
                        ].join(' '),
                    }"
                    @update:model-value="updateItemText(item.id, $event)"
                />

                <UButton
                    color="neutral"
                    variant="ghost"
                    size="xs"
                    icon="i-lucide-trash-2"
                    class="rounded-lg text-muted/70 transition-colors hover:text-error"
                    aria-label="Delete checklist item"
                    @click="removeItem(item.id)"
                />
            </div>

            <div
                v-if="block.items.length === 0"
                class="rounded-3xl border border-dashed border-muted/20 bg-elevated/5 py-12 text-center"
            >
                <p
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/40"
                >
                    No checklist items yet
                </p>
                <p class="mt-2 text-sm text-muted">
                    Add the first item to start tracking completion.
                </p>
            </div>
        </div>
    </div>
</template>
