// apps/web/src/features/workspace/node/blocks/workspace-message-house-block-editor.tsx
import {
  buildMessageHouseStressTestPrompt,
  getMessageHouseSummary,
  type WorkspaceMessageHouseBlock,
} from "@brainiac/workspace";
import { Loader2, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { Button } from "@/ui/button";
import { Input } from "@/ui/input";
import { Label } from "@/ui/label";
import { Textarea } from "@/ui/textarea";
import { formatDateTime } from "@/lib/utils/format-date-time";
import { getErrorMessage } from "@/lib/utils/get-error-message";

const bottomSections = [
  {
    key: "audiencePains" as const,
    label: "Audience Pains",
    placeholder: "What frustrations, risks, and stalled outcomes does the audience already feel?",
  },
  {
    key: "proofPoints" as const,
    label: "Proof Points",
    placeholder:
      "Case studies, client results, founder receipts, or market proof that support the promise.",
  },
  {
    key: "voicePrinciples" as const,
    label: "Voice Principles",
    placeholder: "Rules for how the brand should sound across posts, scripts, and team output.",
  },
];

export function WorkspaceMessageHouseBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceMessageHouseBlock>) {
  const { mutateBlock, runBlockAgentPrompt } = useWorkspaceNodeEditorContext();
  const summary = useMemo(() => getMessageHouseSummary(block), [block]);
  const [isStressTesting, setIsStressTesting] = useState(false);

  async function runStressTest() {
    setIsStressTesting(true);

    try {
      const response = await runBlockAgentPrompt(
        tabId,
        block.id,
        buildMessageHouseStressTestPrompt(block),
      );

      mutateBlock(tabId, block.id, (entry, _tab, _node, timestamp) => {
        if (entry.type !== "message-house") {
          return;
        }
        entry.latestStressTest = response;
        entry.stressTestUpdatedAt = timestamp;
      });

      toast.success("Stress test saved", {
        description: "The Brand agent analysis was added to the message house.",
      });
    } catch (error) {
      toast.error("Stress test failed", {
        description: getErrorMessage(
          error,
          "The Brand agent could not stress-test the message house.",
        ),
      });
    } finally {
      setIsStressTesting(false);
    }
  }

  return (
    <div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-2xl border border-primary/10 bg-primary/5 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary/60">Filled</p>
          <p className="mt-2 text-xl font-black tracking-tight text-primary sm:text-2xl">
            {summary.filledSectionCount}/7
          </p>
        </div>

        <div className="rounded-2xl border border-secondary/10 bg-secondary/5 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-secondary/60">
            Pillars
          </p>
          <p className="mt-2 text-xl font-black tracking-tight text-secondary sm:text-2xl">
            {summary.pillarCount}
          </p>
        </div>

        <div className="rounded-2xl border border-warning/10 bg-warning/5 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-warning/60">
            Stress Test
          </p>
          <p className="mt-2 text-lg font-black tracking-tight text-warning sm:text-xl">
            {summary.latestStressTestAvailable ? "Saved" : "Pending"}
          </p>
        </div>
      </div>

      <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5">
        <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
          <div>
            <h2 className="text-sm font-black tracking-tight text-foreground">Brand Promise</h2>
            <p className="mt-0.5 text-xs text-muted-foreground">
              The line the whole team can repeat without improvising.
            </p>
          </div>

          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="rounded-full"
            disabled={isStressTesting}
            onClick={runStressTest}
          >
            {isStressTesting ? <Loader2 className="animate-spin" /> : <Sparkles />}
            AI Stress-Test
          </Button>
        </div>

        <Textarea
          value={block.brandPromise}
          rows={3}
          className="rounded-2xl bg-background/60 text-lg leading-relaxed font-black tracking-tight"
          placeholder="What is the single promise this brand owns?"
          onChange={(event) =>
            mutateBlock(tabId, block.id, (entry) => {
              if (entry.type !== "message-house") {
                return;
              }
              entry.brandPromise = event.target.value.slice(0, 4000);
            })
          }
        />
      </section>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {block.pillars.map((pillar) => (
          <article
            key={pillar.id}
            className="rounded-2xl border border-muted/20 bg-background/40 p-4 transition-colors hover:border-muted/30"
          >
            <div className="mb-3">
              <Label
                htmlFor={`pillar-title-${pillar.id}`}
                className="mb-1.5 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
              >
                Pillar
              </Label>
              <Input
                id={`pillar-title-${pillar.id}`}
                value={pillar.title}
                placeholder="Pillar title"
                className="border-0 bg-transparent px-0 text-base font-black tracking-tight uppercase shadow-none focus-visible:ring-0"
                onChange={(event) =>
                  mutateBlock(tabId, block.id, (entry) => {
                    if (entry.type !== "message-house") {
                      return;
                    }
                    const target = entry.pillars.find((candidate) => candidate.id === pillar.id);
                    if (!target) {
                      return;
                    }
                    target.title = event.target.value.slice(0, 80);
                  })
                }
              />
            </div>

            <Label
              htmlFor={`pillar-body-${pillar.id}`}
              className="mb-1.5 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
            >
              Message
            </Label>
            <Textarea
              id={`pillar-body-${pillar.id}`}
              value={pillar.body}
              rows={5}
              className="rounded-xl bg-muted/5 leading-relaxed"
              placeholder="What repeatable message should this pillar carry?"
              onChange={(event) =>
                mutateBlock(tabId, block.id, (entry) => {
                  if (entry.type !== "message-house") {
                    return;
                  }
                  const target = entry.pillars.find((candidate) => candidate.id === pillar.id);
                  if (!target) {
                    return;
                  }
                  target.body = event.target.value.slice(0, 2000);
                })
              }
            />
          </article>
        ))}
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {bottomSections.map((section) => (
          <article
            key={section.key}
            className="rounded-2xl border border-muted/20 bg-background/40 p-4 transition-colors hover:border-muted/30"
          >
            <Label
              htmlFor={section.key}
              className="mb-1.5 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
            >
              {section.label}
            </Label>
            <Textarea
              id={section.key}
              value={block[section.key]}
              rows={5}
              className="rounded-xl bg-muted/5 leading-relaxed"
              placeholder={section.placeholder}
              onChange={(event) =>
                mutateBlock(tabId, block.id, (entry) => {
                  if (entry.type !== "message-house") {
                    return;
                  }
                  entry[section.key] = event.target.value.slice(0, 4000);
                })
              }
            />
          </article>
        ))}
      </div>

      <section className="rounded-2xl border border-warning/20 bg-warning/5 p-4">
        <div className="mb-3 flex flex-wrap items-start justify-between gap-3">
          <div>
            <h2 className="text-sm font-black tracking-tight text-foreground">
              Stress-Test Output
            </h2>
            <p className="mt-0.5 text-xs text-muted-foreground">
              Finds gaps, contradictions, and weak proof.
            </p>
          </div>

          {block.stressTestUpdatedAt ? (
            <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/60">
              Last run {formatDateTime(block.stressTestUpdatedAt)}
            </p>
          ) : null}
        </div>

        <div className="min-h-[80px] rounded-xl border border-muted/20 bg-background/60 p-4 text-sm leading-relaxed text-muted-foreground">
          {block.latestStressTest ? (
            <p className="whitespace-pre-wrap">{block.latestStressTest}</p>
          ) : (
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/40">
              Run AI Stress-Test to get a critique of the messaging
            </p>
          )}
        </div>
      </section>
    </div>
  );
}

// apps/web/app/components/workspace/node/blocks/WorkspaceMessageHouseBlockEditor.vue
<script setup lang="ts">
import {
  buildMessageHouseStressTestPrompt,
  getMessageHouseSummary,
  type WorkspaceMessageHouseBlock,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";
import { formatDateTime } from "~/utils/format-date-time";
import { getErrorMessage } from "~/utils/get-error-message";

const props = defineProps<{
  block: WorkspaceMessageHouseBlock;
  tabId: string;
}>();

const toast = useToast();
const { mutateBlock, runBlockAgentPrompt } = useWorkspaceNodeEditorContext();

const summary = computed(() => getMessageHouseSummary(props.block));
const isStressTesting = ref(false);

async function runStressTest() {
  isStressTesting.value = true;

  try {
    const response = await runBlockAgentPrompt(
      props.tabId,
      props.block.id,
      buildMessageHouseStressTestPrompt(props.block),
    );

    mutateBlock(props.tabId, props.block.id, (block, _tab, _node, timestamp) => {
      if (block.type !== "message-house") {
        return;
      }

      block.latestStressTest = response;
      block.stressTestUpdatedAt = timestamp;
    });

    toast.add({
      title: "Stress test saved",
      description: "The Brand agent analysis was added to the message house.",
      color: "success",
      icon: "i-lucide-sparkles",
    });
  } catch (error) {
    toast.add({
      title: "Stress test failed",
      description: getErrorMessage(
        error,
        "The Brand agent could not stress-test the message house.",
      ),
      color: "error",
      icon: "i-lucide-alert-circle",
    });
  } finally {
    isStressTesting.value = false;
  }
}

const bottomSections = [
  {
    key: "audiencePains",
    label: "Audience Pains",
    placeholder: "What frustrations, risks, and stalled outcomes does the audience already feel?",
  },
  {
    key: "proofPoints",
    label: "Proof Points",
    placeholder:
      "Case studies, client results, founder receipts, or market proof that support the promise.",
  },
  {
    key: "voicePrinciples",
    label: "Voice Principles",
    placeholder: "Rules for how the brand should sound across posts, scripts, and team output.",
  },
] as const;
</script>

<template>
  <div class="space-y-5">
    <!-- Summary Stats -->
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <div class="rounded-2xl bg-primary/5 p-4 border border-primary/10">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-primary/60">Filled</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-primary">
          {{ summary.filledSectionCount }}/7
        </p>
      </div>

      <div class="rounded-2xl bg-secondary/5 p-4 border border-secondary/10">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-secondary/60">Pillars</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-secondary">
          {{ summary.pillarCount }}
        </p>
      </div>

      <div class="rounded-2xl bg-warning/5 p-4 border border-warning/10">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-warning/60">Stress Test</p>
        <p class="mt-2 text-lg sm:text-xl font-black tracking-tight text-warning">
          {{ summary.latestStressTestAvailable ? "Saved" : "Pending" }}
        </p>
      </div>
    </div>

    <!-- Brand Promise Section -->
    <section class="rounded-2xl border border-primary/20 bg-primary/5 p-5">
      <div class="flex flex-wrap items-start justify-between gap-3 mb-4">
        <div>
          <h2 class="text-sm font-black text-highlighted tracking-tight">Brand Promise</h2>
          <p class="text-xs text-muted mt-0.5">
            The line the whole team can repeat without improvising.
          </p>
        </div>

        <UButton
          color="primary"
          variant="soft"
          icon="i-lucide-sparkles"
          size="sm"
          class="rounded-full"
          :loading="isStressTesting"
          @click="runStressTest"
        >
          AI Stress-Test
        </UButton>
      </div>

      <UTextarea
        :model-value="block.brandPromise"
        autoresize
        variant="subtle"
        :rows="3"
        class="rounded-2xl"
        :ui="{
          base: 'bg-default/60 text-lg font-black tracking-tight leading-relaxed placeholder:text-muted/30',
        }"
        placeholder="What is the single promise this brand owns?"
        @update:model-value="
          mutateBlock(tabId, block.id, (entry) => {
            if (entry.type !== 'message-house') return;
            entry.brandPromise = ($event ?? '').slice(0, 4000);
          })
        "
      />
    </section>

    <!-- Pillars Grid -->
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <article
        v-for="pillar in block.pillars"
        :key="pillar.id"
        class="rounded-2xl border border-muted/20 bg-default/40 p-4 transition-colors hover:border-muted/30"
      >
        <div class="mb-3">
          <label
            :for="'pillar-title-' + pillar.id"
            class="block text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60 mb-1.5"
          >
            Pillar
          </label>
          <UInput
            :id="'pillar-title-' + pillar.id"
            :model-value="pillar.title"
            variant="none"
            placeholder="Pillar title"
            size="lg"
            class="w-full"
            :ui="{
              base: 'px-0 text-base font-black text-highlighted placeholder:text-muted/40 uppercase tracking-tight',
            }"
            @update:model-value="
              mutateBlock(tabId, block.id, (entry) => {
                if (entry.type !== 'message-house') return;
                const target = entry.pillars.find((candidate) => candidate.id === pillar.id);
                if (!target) return;
                target.title = ($event ?? '').slice(0, 80);
              })
            "
          />
        </div>

        <label
          :for="'pillar-body-' + pillar.id"
          class="block text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60 mb-1.5"
        >
          Message
        </label>
        <UTextarea
          :id="'pillar-body-' + pillar.id"
          :model-value="pillar.body"
          autoresize
          variant="subtle"
          :rows="5"
          class="rounded-xl"
          :ui="{ base: 'bg-elevated/5 leading-relaxed text-sm' }"
          placeholder="What repeatable message should this pillar carry?"
          @update:model-value="
            mutateBlock(tabId, block.id, (entry) => {
              if (entry.type !== 'message-house') return;
              const target = entry.pillars.find((candidate) => candidate.id === pillar.id);
              if (!target) return;
              target.body = ($event ?? '').slice(0, 2000);
            })
          "
        />
      </article>
    </div>

    <!-- Supporting Sections Grid -->
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <article
        v-for="section in bottomSections"
        :key="section.key"
        class="rounded-2xl border border-muted/20 bg-default/40 p-4 transition-colors hover:border-muted/30"
      >
        <label
          :for="section.key"
          class="block text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60 mb-1.5"
        >
          {{ section.label }}
        </label>
        <UTextarea
          :id="section.key"
          :model-value="block[section.key]"
          autoresize
          variant="subtle"
          :rows="5"
          class="rounded-xl"
          :ui="{ base: 'bg-elevated/5 leading-relaxed text-sm' }"
          :placeholder="section.placeholder"
          @update:model-value="
            mutateBlock(tabId, block.id, (entry) => {
              if (entry.type !== 'message-house') return;
              entry[section.key] = ($event ?? '').slice(0, 4000);
            })
          "
        />
      </article>
    </div>

    <!-- Stress Test Output -->
    <section class="rounded-2xl border border-warning/20 bg-warning/5 p-4">
      <div class="flex flex-wrap items-start justify-between gap-3 mb-3">
        <div>
          <h2 class="text-sm font-black text-highlighted tracking-tight">Stress-Test Output</h2>
          <p class="text-xs text-muted mt-0.5">Finds gaps, contradictions, and weak proof.</p>
        </div>

        <p
          v-if="block.stressTestUpdatedAt"
          class="text-[10px] font-bold uppercase tracking-widest text-muted/60"
        >
          Last run {{ formatDateTime(block.stressTestUpdatedAt) }}
        </p>
      </div>

      <div
        class="rounded-xl border border-muted/20 bg-default/60 p-4 text-sm leading-relaxed text-toned min-h-[80px]"
      >
        <p v-if="block.latestStressTest" class="whitespace-pre-wrap">
          {{ block.latestStressTest }}
        </p>
        <p v-else class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/40">
          Run AI Stress-Test to get a critique of the messaging
        </p>
      </div>
    </section>
  </div>
</template>
