// apps/web/src/components/workspace/node/blocks/workspace-timeline-block-editor.tsx
import {
  WORKSPACE_TIMELINE_MILESTONE_STATUSES,
  type WorkspaceTimelineBlock,
  type WorkspaceTimelineMilestoneStatus,
} from "@brainiac/workspace";
import {
  AlertCircle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Circle,
  Milestone,
  PlayCircle,
  Plus,
  Settings2,
  Trash2,
} from "lucide-react";
import { useMemo, useState } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { BlockSelect } from "@/components/workspace/node/blocks/shared/block-select";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

const statusLabels: Record<WorkspaceTimelineMilestoneStatus, string> = {
  planned: "Planned",
  active: "Active",
  done: "Done",
  blocked: "Blocked",
};

const StatusIcons: Record<WorkspaceTimelineMilestoneStatus, typeof Circle> = {
  planned: Circle,
  active: PlayCircle,
  done: CheckCircle2,
  blocked: AlertCircle,
};

function getNextStatus(status: WorkspaceTimelineMilestoneStatus): WorkspaceTimelineMilestoneStatus {
  const currentIndex = WORKSPACE_TIMELINE_MILESTONE_STATUSES.indexOf(status);
  const nextIndex =
    currentIndex < 0 ? 0 : (currentIndex + 1) % WORKSPACE_TIMELINE_MILESTONE_STATUSES.length;
  return WORKSPACE_TIMELINE_MILESTONE_STATUSES[nextIndex] ?? "planned";
}

function toTimelineStatus(value: string): WorkspaceTimelineMilestoneStatus {
  return value === "active" || value === "done" || value === "blocked" ? value : "planned";
}

function getStatusColor(status: WorkspaceTimelineMilestoneStatus) {
  switch (status) {
    case "done":
      return "text-success bg-success/10 border-success/20";
    case "active":
      return "text-primary bg-primary/10 border-primary/20";
    case "blocked":
      return "text-destructive bg-destructive/10 border-destructive/20";
    default:
      return "text-muted-foreground bg-muted/10 border-muted/20";
  }
}

export function WorkspaceTimelineBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceTimelineBlock>) {
  const {
    addTimelineMilestone,
    mutateTimelineMilestone,
    removeTimelineMilestone,
    moveTimelineMilestone,
  } = useWorkspaceNodeEditorContext();

  const [expandedMilestoneId, setExpandedMilestoneId] = useState<string | null>(null);

  const timelineSummary = useMemo(() => {
    const total = block.milestones.length;
    const activeCount = block.milestones.filter((milestone) => milestone.status === "active").length;
    const doneCount = block.milestones.filter((milestone) => milestone.status === "done").length;
    const blockedCount = block.milestones.filter((milestone) => milestone.status === "blocked").length;

    return {
      total,
      activeCount,
      doneCount,
      blockedCount,
      completionPercent: Math.round((doneCount / Math.max(total, 1)) * 100),
    };
  }, [block.milestones]);

  function toggleMilestone(id: string) {
    setExpandedMilestoneId((current) => (current === id ? null : id));
  }

  return (
    <div className="space-y-6">
      <div className="space-y-4 rounded-3xl border border-muted/20 bg-muted/10 p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="space-y-1">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
              Milestone Journey
            </p>
            <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/40">
              Chronological project roadmap
            </p>
          </div>
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="rounded-full px-4"
            aria-label="Add timeline milestone"
            onClick={() => addTimelineMilestone(tabId, block.id)}
          >
            <Plus />
            Add Milestone
          </Button>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="secondary" className="rounded-2xl">
            {timelineSummary.total} milestones
          </Badge>
          <Badge className="rounded-2xl">{timelineSummary.activeCount} active</Badge>
          <Badge variant="success" className="rounded-2xl">
            {timelineSummary.doneCount} done
          </Badge>
          <Badge variant="destructive" className="rounded-2xl">
            {timelineSummary.blockedCount} blocked
          </Badge>
          <Badge variant="secondary" className="rounded-2xl">
            {timelineSummary.completionPercent}% complete
          </Badge>
        </div>
      </div>

      <div className="relative space-y-8 pl-8">
        <div className="absolute top-4 bottom-4 left-[15px] w-0.5 bg-gradient-to-b from-primary/30 via-muted/20 to-transparent" />

        {block.milestones.map((milestone, index) => {
          const StatusIcon = StatusIcons[milestone.status];
          const isExpanded = expandedMilestoneId === milestone.id;

          return (
            <article key={milestone.id} className="group relative">
              <div
                className={cn(
                  "absolute top-0 -left-[21px] z-10 size-5 rounded-full border-2 bg-background transition-all duration-300 group-hover:scale-125",
                  getStatusColor(milestone.status),
                )}
              >
                {milestone.status === "active" ? (
                  <div className="absolute inset-0 animate-ping rounded-full bg-primary/20" />
                ) : null}
              </div>

              <div
                className={cn(
                  "rounded-3xl border border-muted/20 bg-background/40 p-5 transition-all hover:border-primary/20 hover:bg-background/60 hover:shadow-xl hover:shadow-black/5",
                  isExpanded && "ring-1 ring-primary/20",
                )}
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <div className="mb-1 flex flex-wrap items-center gap-2">
                      <span className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground/60">
                        {milestone.date || "No Date Set"}
                      </span>
                      <Badge
                        variant="secondary"
                        className={cn(
                          "cursor-pointer rounded-lg text-[9px] font-bold uppercase",
                          getStatusColor(milestone.status),
                        )}
                        aria-label={`Cycle status for ${milestone.title || "milestone"}`}
                        onClick={() =>
                          mutateTimelineMilestone(tabId, block.id, milestone.id, (entry) => {
                            entry.status = getNextStatus(entry.status);
                          })
                        }
                      >
                        <StatusIcon className="mr-1 size-3" />
                        {statusLabels[milestone.status]}
                      </Badge>
                    </div>

                    <Input
                      value={milestone.title}
                      placeholder="Milestone name..."
                      className="w-full border-0 bg-transparent px-0 text-lg leading-tight font-bold shadow-none focus-visible:ring-0"
                      onChange={(event) =>
                        mutateTimelineMilestone(tabId, block.id, milestone.id, (entry) => {
                          entry.title = event.target.value.slice(0, 160);
                        })
                      }
                    />

                    {milestone.note && !isExpanded ? (
                      <p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{milestone.note}</p>
                    ) : null}
                  </div>

                  <div className="flex items-center gap-1">
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="rounded-lg text-muted-foreground/70 hover:text-foreground"
                      aria-label={isExpanded ? "Hide milestone details" : "Show milestone details"}
                      aria-expanded={isExpanded}
                      onClick={() => toggleMilestone(milestone.id)}
                    >
                      {isExpanded ? <ChevronUp /> : <Settings2 />}
                    </Button>

                    <div className="flex flex-col gap-1">
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="h-6 rounded-lg text-muted-foreground/70 hover:text-foreground"
                        disabled={index === 0}
                        aria-label={`Move ${milestone.title || "milestone"} up`}
                        onClick={() => moveTimelineMilestone(tabId, block.id, milestone.id, "up")}
                      >
                        <ChevronUp />
                      </Button>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="h-6 rounded-lg text-muted-foreground/70 hover:text-foreground"
                        disabled={index === block.milestones.length - 1}
                        aria-label={`Move ${milestone.title || "milestone"} down`}
                        onClick={() => moveTimelineMilestone(tabId, block.id, milestone.id, "down")}
                      >
                        <ChevronDown />
                      </Button>
                    </div>

                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="rounded-lg text-muted-foreground/70 hover:text-destructive"
                      aria-label={`Remove ${milestone.title || "milestone"}`}
                      onClick={() => removeTimelineMilestone(tabId, block.id, milestone.id)}
                    >
                      <Trash2 />
                    </Button>
                  </div>
                </div>

                {isExpanded ? (
                  <div className="mt-6 space-y-6 border-t border-muted/10 pt-6">
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                          Milestone Date
                        </Label>
                        <Input
                          type="date"
                          value={milestone.date ?? ""}
                          className="rounded-xl"
                          onChange={(event) =>
                            mutateTimelineMilestone(tabId, block.id, milestone.id, (entry) => {
                              entry.date = event.target.value || null;
                            })
                          }
                        />
                      </div>

                      <div className="space-y-2">
                        <Label className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                          Status
                        </Label>
                        <BlockSelect
                          value={milestone.status}
                          options={WORKSPACE_TIMELINE_MILESTONE_STATUSES.map((status) => ({
                            label: statusLabels[status],
                            value: status,
                          }))}
                          className="rounded-xl"
                          onValueChange={(value) =>
                            mutateTimelineMilestone(tabId, block.id, milestone.id, (entry) => {
                              entry.status = toTimelineStatus(value);
                            })
                          }
                        />
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                        Supporting Note
                      </Label>
                      <Textarea
                        value={milestone.note}
                        placeholder="Add context, challenges, or success criteria..."
                        className="rounded-2xl text-sm leading-relaxed"
                        onChange={(event) =>
                          mutateTimelineMilestone(tabId, block.id, milestone.id, (entry) => {
                            entry.note = event.target.value.slice(0, 2000);
                          })
                        }
                      />
                    </div>
                  </div>
                ) : null}
              </div>
            </article>
          );
        })}

        {block.milestones.length === 0 ? (
          <div className="rounded-3xl border border-dashed border-muted/20 bg-muted/5 py-12 text-center">
            <Milestone className="mx-auto mb-3 size-8 text-muted-foreground/20" />
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
              No milestones defined
            </p>
            <Button
              type="button"
              variant="link"
              size="sm"
              className="mt-2"
              onClick={() => addTimelineMilestone(tabId, block.id)}
            >
              Create the first one
            </Button>
          </div>
        ) : null}
      </div>
    </div>
  );
}

// apps/web/app/components/workspace/node/blocks/WorkspaceTimelineBlockEditor.vue
<script setup lang="ts">
import {
  WORKSPACE_TIMELINE_MILESTONE_STATUSES,
  type WorkspaceTimelineBlock,
  type WorkspaceTimelineMilestoneStatus,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
  block: WorkspaceTimelineBlock;
  tabId: string;
}>();

const {
  addTimelineMilestone,
  mutateTimelineMilestone,
  removeTimelineMilestone,
  moveTimelineMilestone,
} = useWorkspaceNodeEditorContext();

const statusLabels: Record<WorkspaceTimelineMilestoneStatus, string> = {
  planned: "Planned",
  active: "Active",
  done: "Done",
  blocked: "Blocked",
};

const statusIcons: Record<WorkspaceTimelineMilestoneStatus, string> = {
  planned: "i-lucide-circle",
  active: "i-lucide-play-circle",
  done: "i-lucide-check-circle-2",
  blocked: "i-lucide-alert-circle",
};

const timelineSummary = computed(() => {
  const total = props.block.milestones.length;
  const activeCount = props.block.milestones.filter(
    (milestone) => milestone.status === "active",
  ).length;
  const doneCount = props.block.milestones.filter(
    (milestone) => milestone.status === "done",
  ).length;
  const blockedCount = props.block.milestones.filter(
    (milestone) => milestone.status === "blocked",
  ).length;

  return {
    total,
    activeCount,
    doneCount,
    blockedCount,
    completionPercent: Math.round((doneCount / Math.max(total, 1)) * 100),
  };
});

function getNextStatus(status: WorkspaceTimelineMilestoneStatus): WorkspaceTimelineMilestoneStatus {
  const currentIndex = WORKSPACE_TIMELINE_MILESTONE_STATUSES.indexOf(status);
  const nextIndex =
    currentIndex < 0 ? 0 : (currentIndex + 1) % WORKSPACE_TIMELINE_MILESTONE_STATUSES.length;
  return WORKSPACE_TIMELINE_MILESTONE_STATUSES[nextIndex] ?? "planned";
}

function toTimelineStatus(value: string): WorkspaceTimelineMilestoneStatus {
  return value === "active" || value === "done" || value === "blocked" ? value : "planned";
}

function getStatusColor(status: WorkspaceTimelineMilestoneStatus) {
  switch (status) {
    case "done":
      return "text-success bg-success/10 border-success/20";
    case "active":
      return "text-primary bg-primary/10 border-primary/20";
    case "blocked":
      return "text-error bg-error/10 border-error/20";
    default:
      return "text-muted bg-muted/10 border-muted/20";
  }
}

const expandedMilestoneId = ref<string | null>(null);

function toggleMilestone(id: string) {
  expandedMilestoneId.value = expandedMilestoneId.value === id ? null : id;
}

function updateMilestoneTitle(milestoneId: string, value: string | number | undefined) {
  mutateTimelineMilestone(props.tabId, props.block.id, milestoneId, (entry) => {
    entry.title = String(value ?? "").slice(0, 160);
  });
}

function updateMilestoneDate(milestoneId: string, value: string | number | undefined) {
  mutateTimelineMilestone(props.tabId, props.block.id, milestoneId, (entry) => {
    const nextValue = String(value ?? "");
    entry.date = nextValue || null;
  });
}

function updateMilestoneStatus(milestoneId: string, value: string) {
  mutateTimelineMilestone(props.tabId, props.block.id, milestoneId, (entry) => {
    entry.status = toTimelineStatus(value);
  });
}

function cycleMilestoneStatus(milestoneId: string) {
  mutateTimelineMilestone(props.tabId, props.block.id, milestoneId, (entry) => {
    entry.status = getNextStatus(entry.status);
  });
}

function updateMilestoneNote(milestoneId: string, value: string | number | undefined) {
  mutateTimelineMilestone(props.tabId, props.block.id, milestoneId, (entry) => {
    entry.note = String(value ?? "").slice(0, 2000);
  });
}
</script>

<template>
  <div class="space-y-6">
    <!-- Timeline Header -->
    <div class="space-y-4 rounded-3xl border border-muted/20 bg-elevated/10 p-5">
      <div class="flex flex-wrap items-center justify-between gap-3">
        <div class="space-y-1">
          <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">
            Milestone Journey
          </p>
          <p class="text-[10px] font-bold uppercase tracking-widest text-muted/40">
            Chronological project roadmap
          </p>
        </div>
        <UButton
          color="primary"
          variant="soft"
          size="sm"
          icon="i-lucide-plus"
          class="rounded-full px-4"
          aria-label="Add timeline milestone"
          @click="addTimelineMilestone(tabId, block.id)"
        >
          Add Milestone
        </UButton>
      </div>

      <div class="flex flex-wrap items-center gap-2">
        <UBadge variant="subtle" class="rounded-2xl">
          {{ timelineSummary.total }} milestones
        </UBadge>
        <UBadge color="primary" variant="soft" class="rounded-2xl">
          {{ timelineSummary.activeCount }} active
        </UBadge>
        <UBadge color="success" variant="soft" class="rounded-2xl">
          {{ timelineSummary.doneCount }} done
        </UBadge>
        <UBadge color="error" variant="soft" class="rounded-2xl">
          {{ timelineSummary.blockedCount }} blocked
        </UBadge>
        <UBadge color="neutral" variant="soft" class="rounded-2xl">
          {{ timelineSummary.completionPercent }}% complete
        </UBadge>
      </div>
    </div>

    <!-- Vertical Timeline Container -->
    <div class="relative pl-8 space-y-8">
      <!-- Continuous Line -->
      <div
        class="absolute left-[15px] top-4 bottom-4 w-0.5 bg-linear-to-b from-primary/30 via-muted/20 to-transparent"
      />

      <article
        v-for="(milestone, index) in block.milestones"
        :key="milestone.id"
        class="group relative"
      >
        <!-- Milestone Dot -->
        <div
          class="absolute -left-[21px] top-0 z-10 size-5 rounded-full border-2 bg-default transition-all duration-300 group-hover:scale-125"
          :class="getStatusColor(milestone.status)"
        >
          <div
            v-if="milestone.status === 'active'"
            class="absolute inset-0 animate-ping rounded-full bg-primary/20"
          />
        </div>

        <!-- Milestone Card -->
        <div
          class="rounded-3xl border border-muted/20 bg-default/40 p-5 transition-all hover:border-primary/20 hover:bg-default/60 hover:shadow-xl hover:shadow-black/5"
          :class="{
            'ring-1 ring-primary/20': expandedMilestoneId === milestone.id,
          }"
        >
          <div class="flex items-start justify-between gap-4">
            <div class="flex-1 min-w-0">
              <div class="flex flex-wrap items-center gap-2 mb-1">
                <span class="text-[10px] font-black uppercase tracking-[0.2em] text-muted/60">
                  {{ milestone.date || "No Date Set" }}
                </span>
                <UBadge
                  variant="subtle"
                  size="xs"
                  class="cursor-pointer rounded-lg text-[9px] uppercase font-bold"
                  :class="getStatusColor(milestone.status)"
                  :aria-label="`Cycle status for ${milestone.title || 'milestone'}`"
                  @click.stop="cycleMilestoneStatus(milestone.id)"
                >
                  <UIcon :name="statusIcons[milestone.status]" class="mr-1 size-3" />
                  {{ statusLabels[milestone.status] }}
                </UBadge>
              </div>

              <UInput
                :model-value="milestone.title"
                variant="none"
                placeholder="Milestone name..."
                class="w-full"
                :ui="{
                  base: 'px-0 py-0 text-lg font-bold text-highlighted leading-tight',
                }"
                @update:model-value="updateMilestoneTitle(milestone.id, $event)"
              />

              <p
                v-if="milestone.note && expandedMilestoneId !== milestone.id"
                class="mt-2 text-sm text-toned line-clamp-2"
              >
                {{ milestone.note }}
              </p>
            </div>

            <div class="flex items-center gap-1">
              <UButton
                color="neutral"
                variant="ghost"
                size="xs"
                :icon="
                  expandedMilestoneId === milestone.id
                    ? 'i-lucide-chevron-up'
                    : 'i-lucide-settings-2'
                "
                class="rounded-lg text-muted/70 transition-colors hover:text-highlighted"
                :aria-label="
                  expandedMilestoneId === milestone.id
                    ? 'Hide milestone details'
                    : 'Show milestone details'
                "
                :aria-expanded="expandedMilestoneId === milestone.id"
                @click="toggleMilestone(milestone.id)"
              />

              <div class="flex flex-col gap-1">
                <UButton
                  color="neutral"
                  variant="ghost"
                  size="xs"
                  icon="i-lucide-chevron-up"
                  :disabled="index === 0"
                  class="rounded-lg h-6 text-muted/70 transition-colors hover:text-highlighted"
                  :aria-label="`Move ${milestone.title || 'milestone'} up`"
                  @click="moveTimelineMilestone(tabId, block.id, milestone.id, 'up')"
                />
                <UButton
                  color="neutral"
                  variant="ghost"
                  size="xs"
                  icon="i-lucide-chevron-down"
                  :disabled="index === block.milestones.length - 1"
                  class="rounded-lg h-6 text-muted/70 transition-colors hover:text-highlighted"
                  :aria-label="`Move ${milestone.title || 'milestone'} down`"
                  @click="moveTimelineMilestone(tabId, block.id, milestone.id, 'down')"
                />
              </div>

              <UButton
                color="neutral"
                variant="ghost"
                size="xs"
                icon="i-lucide-trash-2"
                class="rounded-lg text-muted/70 transition-colors hover:text-error"
                :aria-label="`Remove ${milestone.title || 'milestone'}`"
                @click="removeTimelineMilestone(tabId, block.id, milestone.id)"
              />
            </div>
          </div>

          <!-- Expanded Details -->
          <div
            v-if="expandedMilestoneId === milestone.id"
            class="mt-6 space-y-6 border-t border-muted/10 pt-6"
          >
            <div class="grid grid-cols-2 gap-4">
              <UFormField size="sm">
                <template #label>
                  <span class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                    >Milestone Date</span
                  >
                </template>
                <UInput
                  :model-value="milestone.date ?? ''"
                  type="date"
                  icon="i-lucide-calendar"
                  class="rounded-xl"
                  @update:model-value="updateMilestoneDate(milestone.id, $event)"
                />
              </UFormField>

              <UFormField size="sm">
                <template #label>
                  <span class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                    >Status</span
                  >
                </template>
                <USelect
                  :model-value="milestone.status"
                  :items="
                    WORKSPACE_TIMELINE_MILESTONE_STATUSES.map((s) => ({
                      label: statusLabels[s],
                      value: s,
                    }))
                  "
                  class="rounded-xl"
                  @update:model-value="updateMilestoneStatus(milestone.id, $event)"
                />
              </UFormField>
            </div>

            <UFormField size="sm">
              <template #label>
                <span class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                  >Supporting Note</span
                >
              </template>
              <UTextarea
                :model-value="milestone.note"
                variant="soft"
                placeholder="Add context, challenges, or success criteria..."
                autoresize
                :max-rows="10"
                class="rounded-2xl"
                :ui="{
                  base: 'text-sm text-toned leading-relaxed',
                }"
                @update:model-value="updateMilestoneNote(milestone.id, $event)"
              />
            </UFormField>
          </div>
        </div>
      </article>

      <!-- Empty State -->
      <div
        v-if="block.milestones.length === 0"
        class="rounded-3xl border border-dashed border-muted/20 bg-elevated/5 py-12 text-center"
      >
        <UIcon name="i-lucide-milestone" class="size-8 text-muted/20 mb-3" />
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">
          No milestones defined
        </p>
        <UButton
          color="primary"
          variant="link"
          size="sm"
          class="mt-2"
          @click="addTimelineMilestone(tabId, block.id)"
        >
          Create the first one
        </UButton>
      </div>
    </div>
  </div>
</template>
