// apps/web/src/features/workspace/node/blocks/workspace-talent-grid-block-editor.tsx
import {
  createWorkspaceTalentGridMember,
  getTalentGridBoxKey,
  getTalentGridSummary,
  workspaceTalentGridBoxLabels,
  type WorkspaceTalentGridBlock,
  type WorkspaceTalentGridBoxKey,
} from "@brainiac/workspace";
import { Trash2, UserPlus, Users } from "lucide-react";
import { Fragment, useMemo } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { Badge } from "@/ui/badge";
import { Button } from "@/ui/button";
import { Input } from "@/ui/input";
import { cn } from "@/lib/utils";

const gridRows: Array<{
  label: string;
  cells: WorkspaceTalentGridBoxKey[];
}> = [
  {
    label: "High Growth Potential",
    cells: ["enigma", "growth-star", "superstar"],
  },
  {
    label: "Moderate Growth Potential",
    cells: ["under-performer", "core-player", "high-performer"],
  },
  {
    label: "Specialized Potential",
    cells: ["risk", "average-joe", "specialist"],
  },
];

const performanceColumns = ["Building Foundation", "Solid Performance", "Excelling"];

function clampGridScore(value: string) {
  const numeric = Number(value || 3);
  return Math.min(5, Math.max(1, Math.round(numeric)));
}

function getCellClasses(key: WorkspaceTalentGridBoxKey) {
  switch (key) {
    case "superstar":
    case "growth-star":
      return "border-success/35 bg-success/10";
    case "high-performer":
    case "specialist":
      return "border-primary/35 bg-primary/5";
    case "core-player":
    case "average-joe":
      return "border-muted/35 bg-muted/50";
    case "risk":
    case "under-performer":
      return "border-destructive/35 bg-destructive/10";
    default:
      return "border-warning/35 bg-warning/10";
  }
}

function getCellTone(
  key: WorkspaceTalentGridBoxKey,
): "success" | "default" | "secondary" | "warning" | "destructive" {
  switch (key) {
    case "superstar":
    case "growth-star":
      return "success";
    case "high-performer":
    case "specialist":
      return "default";
    case "core-player":
    case "average-joe":
      return "secondary";
    case "risk":
    case "under-performer":
      return "destructive";
    default:
      return "warning";
  }
}

function getBoxDescription(key: WorkspaceTalentGridBoxKey): string {
  const descriptions: Record<WorkspaceTalentGridBoxKey, string> = {
    superstar: "Exceeds expectations with high growth potential",
    "growth-star": "Strong performer ready for advancement",
    "high-performer": "Consistent excellence in current role",
    enigma: "High potential seeking clearer direction",
    "core-player": "Reliable contributor to team success",
    "average-joe": "Steady performer in established domain",
    "under-performer": "Support needed to reach full potential",
    specialist: "Deep expertise in focused area",
    risk: "Opportunity for role alignment discussion",
  };
  return descriptions[key] || "";
}

export function WorkspaceTalentGridBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceTalentGridBlock>) {
  const { mutateBlock } = useWorkspaceNodeEditorContext();

  const summary = useMemo(() => getTalentGridSummary(block), [block]);

  const membersByBox = useMemo(() => {
    const grouped = new Map<WorkspaceTalentGridBoxKey, WorkspaceTalentGridBlock["members"]>();

    for (const row of gridRows) {
      for (const cell of row.cells) {
        grouped.set(cell, []);
      }
    }

    for (const member of block.members) {
      const key = getTalentGridBoxKey(member.performance, member.potential);
      const current = grouped.get(key);

      if (current) {
        current.push(member);
      } else {
        grouped.set(key, [member]);
      }
    }

    return grouped;
  }, [block.members]);

  function addMember() {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "talent-grid") {
        return;
      }

      entry.members.push(createWorkspaceTalentGridMember());
    });
  }

  function removeMember(memberId: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "talent-grid") {
        return;
      }

      entry.members = entry.members.filter((member) => member.id !== memberId);
    });
  }

  function updateMemberName(memberId: string, value: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "talent-grid") {
        return;
      }
      const target = entry.members.find((candidate) => candidate.id === memberId);
      if (!target) {
        return;
      }
      target.name = value.slice(0, 120);
    });
  }

  function updateMemberRole(memberId: string, value: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "talent-grid") {
        return;
      }
      const target = entry.members.find((candidate) => candidate.id === memberId);
      if (!target) {
        return;
      }
      target.role = value.slice(0, 120);
    });
  }

  function updateMemberPerformance(memberId: string, value: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "talent-grid") {
        return;
      }
      const target = entry.members.find((candidate) => candidate.id === memberId);
      if (!target) {
        return;
      }
      target.performance = clampGridScore(value);
    });
  }

  function updateMemberPotential(memberId: string, value: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "talent-grid") {
        return;
      }
      const target = entry.members.find((candidate) => candidate.id === memberId);
      if (!target) {
        return;
      }
      target.potential = clampGridScore(value);
    });
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-2xl border border-primary/20 bg-primary/5 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary/70">Team</p>
          <p className="mt-2 text-xl font-black tracking-tight text-primary sm:text-2xl">
            {summary.memberCount}
          </p>
        </div>

        <div className="rounded-2xl border border-success/20 bg-success/5 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-success/70">
            Growth Ready
          </p>
          <p className="mt-2 text-xl font-black tracking-tight text-success sm:text-2xl">
            {summary.superstarCount + summary.growthStarCount}
          </p>
        </div>

        <div className="rounded-2xl border border-muted/20 bg-muted/10 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
            Core Contributors
          </p>
          <p className="mt-2 text-xl font-black tracking-tight text-foreground sm:text-2xl">
            {summary.corePlayerCount}
          </p>
        </div>

        <div className="rounded-2xl border border-warning/20 bg-warning/5 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-warning/70">
            Development Focus
          </p>
          <p className="mt-2 text-xl font-black tracking-tight text-warning sm:text-2xl">
            {summary.riskCount + summary.boxCounts["under-performer"]}
          </p>
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 px-1">
        <div>
          <h2 className="text-sm font-black tracking-tight text-foreground">
            Talent Development Grid
          </h2>
          <p className="text-xs text-muted-foreground">
            Assess performance (1-5) and growth potential to support team development.
          </p>
        </div>

        <Button
          type="button"
          variant="secondary"
          size="sm"
          className="rounded-full"
          onClick={addMember}
        >
          <UserPlus />
          Add Member
        </Button>
      </div>

      <div className="overflow-x-auto pb-2">
        <div
          className="grid min-w-[740px] gap-2.5"
          style={{ gridTemplateColumns: "7rem repeat(3, minmax(0, 1fr))" }}
        >
          <div />

          {performanceColumns.map((column) => (
            <div
              key={column}
              className="rounded-xl border border-muted/20 bg-muted/10 px-3 py-2.5 text-center text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
            >
              {column}
            </div>
          ))}

          {gridRows.map((row) => (
            <Fragment key={row.label}>
              <div className="flex items-center rounded-xl border border-muted/20 bg-muted/5 px-2.5 py-3 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                {row.label}
              </div>

              {row.cells.map((cell) => (
                <div
                  key={cell}
                  className={cn("min-h-[140px] rounded-2xl border p-3.5", getCellClasses(cell))}
                >
                  <div className="mb-3 flex items-start justify-between gap-2">
                    <div className="flex-1">
                      <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                        {workspaceTalentGridBoxLabels[cell]}
                      </p>
                      <p className="mt-1 text-[9px] leading-tight text-muted-foreground/40">
                        {membersByBox.get(cell)?.length ?? 0} member
                        {(membersByBox.get(cell)?.length ?? 0) !== 1 ? "s" : ""}
                      </p>
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-1.5">
                    {membersByBox.get(cell)?.map((member) => (
                      <div
                        key={member.id}
                        className="rounded-full border border-muted/20 bg-background/80 px-2.5 py-0.5 text-[11px] font-semibold text-foreground"
                      >
                        {member.name || "—"}
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </Fragment>
          ))}
        </div>
      </div>

      {block.members.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-muted/20 bg-muted/5 py-10 text-center">
          <div className="mx-auto flex size-12 items-center justify-center rounded-xl bg-muted/10 text-muted-foreground/30">
            <Users className="size-6" />
          </div>
          <p className="mt-3 text-xs font-bold text-muted-foreground">No team members yet</p>
          <p className="mt-1 text-[11px] text-muted-foreground/60">
            Add members to assess and develop your team
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {block.members.map((member) => {
            const boxKey = getTalentGridBoxKey(member.performance, member.potential);
            const boxDescription = getBoxDescription(boxKey);

            return (
              <article
                key={member.id}
                className="rounded-2xl border border-muted/20 bg-background/40 p-4 transition-all hover:border-muted/30"
              >
                <div className="mb-4 flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0 flex-1">
                    <Input
                      value={member.name}
                      placeholder="Name"
                      className="w-full border-0 bg-transparent px-0 text-base font-bold text-foreground placeholder:text-muted-foreground/40 shadow-none focus-visible:ring-0"
                      onChange={(event) => updateMemberName(member.id, event.target.value)}
                    />
                    <Input
                      value={member.role}
                      placeholder="Role"
                      className="mt-0.5 border-0 bg-transparent px-0 text-xs text-muted-foreground placeholder:text-muted-foreground/40 shadow-none focus-visible:ring-0"
                      onChange={(event) => updateMemberRole(member.id, event.target.value)}
                    />
                  </div>

                  <div className="flex shrink-0 items-center gap-2">
                    <Badge variant={getCellTone(boxKey)} className="rounded-full">
                      {workspaceTalentGridBoxLabels[boxKey]}
                    </Badge>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="rounded-lg hover:bg-destructive/10 hover:text-destructive"
                      aria-label="Remove member"
                      onClick={() => removeMember(member.id)}
                    >
                      <Trash2 />
                    </Button>
                  </div>
                </div>

                <div className="grid gap-3 sm:grid-cols-2">
                  <div className="rounded-xl border border-muted/20 bg-muted/10 p-3">
                    <div className="mb-2 flex items-center justify-between">
                      <label
                        className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
                        htmlFor={`performance-${member.id}`}
                      >
                        Performance
                      </label>
                      <span className="text-xs font-black text-primary">
                        {member.performance}/5
                      </span>
                    </div>
                    <input
                      id={`performance-${member.id}`}
                      value={member.performance}
                      type="range"
                      min={1}
                      max={5}
                      step={1}
                      className="h-1.5 w-full cursor-pointer appearance-none rounded-full bg-muted/20 accent-primary"
                      onChange={(event) => updateMemberPerformance(member.id, event.target.value)}
                    />
                  </div>

                  <div className="rounded-xl border border-muted/20 bg-muted/10 p-3">
                    <div className="mb-2 flex items-center justify-between">
                      <label
                        className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
                        htmlFor={`potential-${member.id}`}
                      >
                        Growth Potential
                      </label>
                      <span className="text-xs font-black text-primary">{member.potential}/5</span>
                    </div>
                    <input
                      id={`potential-${member.id}`}
                      value={member.potential}
                      type="range"
                      min={1}
                      max={5}
                      step={1}
                      className="h-1.5 w-full cursor-pointer appearance-none rounded-full bg-muted/20 accent-primary"
                      onChange={(event) => updateMemberPotential(member.id, event.target.value)}
                    />
                  </div>
                </div>

                {boxDescription ? (
                  <div className="mt-3 rounded-lg bg-muted/5 px-3 py-2">
                    <p className="text-[10px] leading-snug text-muted-foreground/70">
                      {boxDescription}
                    </p>
                  </div>
                ) : null}
              </article>
            );
          })}
        </div>
      )}
    </div>
  );
}

// apps/web/app/components/workspace/node/blocks/WorkspaceTalentGridBlockEditor.vue
<script setup lang="ts">
import {
  createWorkspaceTalentGridMember,
  getTalentGridBoxKey,
  getTalentGridSummary,
  workspaceTalentGridBoxLabels,
  type WorkspaceTalentGridBlock,
  type WorkspaceTalentGridBoxKey,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
  block: WorkspaceTalentGridBlock;
  tabId: string;
}>();

const { mutateBlock } = useWorkspaceNodeEditorContext();

const summary = computed(() => getTalentGridSummary(props.block));

const gridRows: Array<{
  label: string;
  cells: WorkspaceTalentGridBoxKey[];
}> = [
  {
    label: "High Growth Potential",
    cells: ["enigma", "growth-star", "superstar"],
  },
  {
    label: "Moderate Growth Potential",
    cells: ["under-performer", "core-player", "high-performer"],
  },
  {
    label: "Specialized Potential",
    cells: ["risk", "average-joe", "specialist"],
  },
];

const performanceColumns = ["Building Foundation", "Solid Performance", "Excelling"];

const membersByBox = computed(() => {
  const grouped = new Map<WorkspaceTalentGridBoxKey, WorkspaceTalentGridBlock["members"]>();

  for (const row of gridRows) {
    for (const cell of row.cells) {
      grouped.set(cell, []);
    }
  }

  for (const member of props.block.members) {
    const key = getTalentGridBoxKey(member.performance, member.potential);
    const current = grouped.get(key);

    if (current) {
      current.push(member);
    } else {
      grouped.set(key, [member]);
    }
  }

  return grouped;
});

function addMember() {
  mutateBlock(props.tabId, props.block.id, (block) => {
    if (block.type !== "talent-grid") {
      return;
    }

    block.members.push(createWorkspaceTalentGridMember());
  });
}

function removeMember(memberId: string) {
  mutateBlock(props.tabId, props.block.id, (block) => {
    if (block.type !== "talent-grid") {
      return;
    }

    block.members = block.members.filter((member) => member.id !== memberId);
  });
}

function clampGridScore(value: string) {
  const numeric = Number(value || 3);
  return Math.min(5, Math.max(1, Math.round(numeric)));
}

function getCellClasses(key: WorkspaceTalentGridBoxKey) {
  switch (key) {
    case "superstar":
    case "growth-star":
      return "border-success/35 bg-success/10";
    case "high-performer":
    case "specialist":
      return "border-primary/35 bg-primary/5";
    case "core-player":
    case "average-joe":
      return "border-muted/35 bg-elevated/50";
    case "risk":
    case "under-performer":
      return "border-error/35 bg-error/10";
    default:
      return "border-warning/35 bg-warning/10";
  }
}

function getCellTone(key: WorkspaceTalentGridBoxKey): "success" | "primary" | "neutral" | "warning" | "error" {
  switch (key) {
    case "superstar":
    case "growth-star":
      return "success";
    case "high-performer":
    case "specialist":
      return "primary";
    case "core-player":
    case "average-joe":
      return "neutral";
    case "risk":
    case "under-performer":
      return "error";
    default:
      return "warning";
  }
}

function getBoxDescription(key: WorkspaceTalentGridBoxKey): string {
  const descriptions: Record<WorkspaceTalentGridBoxKey, string> = {
    "superstar": "Exceeds expectations with high growth potential",
    "growth-star": "Strong performer ready for advancement",
    "high-performer": "Consistent excellence in current role",
    "enigma": "High potential seeking clearer direction",
    "core-player": "Reliable contributor to team success",
    "average-joe": "Steady performer in established domain",
    "under-performer": "Support needed to reach full potential",
    "specialist": "Deep expertise in focused area",
    "risk": "Opportunity for role alignment discussion",
  };
  return descriptions[key] || "";
}
</script>

<template>
  <div class="space-y-6">
    <!-- Team Summary Stats -->
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <div class="rounded-2xl border border-primary/20 bg-primary/5 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-primary/70">Team</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-primary">
          {{ summary.memberCount }}
        </p>
      </div>

      <div class="rounded-2xl border border-success/20 bg-success/5 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-success/70">Growth Ready</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-success">
          {{ summary.superstarCount + summary.growthStarCount }}
        </p>
      </div>

      <div class="rounded-2xl border border-muted/20 bg-elevated/10 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">Core Contributors</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-highlighted">
          {{ summary.corePlayerCount }}
        </p>
      </div>

      <div class="rounded-2xl border border-warning/20 bg-warning/5 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-warning/70">Development Focus</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-warning">
          {{ summary.riskCount + summary.underPerformerCount }}
        </p>
      </div>
    </div>

    <!-- Section Header -->
    <div class="flex flex-wrap items-center justify-between gap-3 px-1">
      <div>
        <h2 class="text-sm font-black text-highlighted tracking-tight">Talent Development Grid</h2>
        <p class="text-xs text-muted">
          Assess performance (1-5) and growth potential to support team development.
        </p>
      </div>

      <UButton
        color="primary"
        variant="soft"
        icon="i-lucide-user-plus"
        size="sm"
        class="rounded-full"
        @click="addMember"
      >
        Add Member
      </UButton>
    </div>

    <!-- 9-Box Grid Visualization -->
    <div class="overflow-x-auto pb-2">
      <div
        class="grid min-w-[740px] gap-2.5"
        style="grid-template-columns: 7rem repeat(3, minmax(0, 1fr))"
      >
        <div />

        <div
          v-for="column in performanceColumns"
          :key="column"
          class="rounded-xl border border-muted/20 bg-elevated/10 px-3 py-2.5 text-center text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
        >
          {{ column }}
        </div>

        <template v-for="row in gridRows" :key="row.label">
          <div
            class="flex items-center rounded-xl border border-muted/20 bg-elevated/5 px-2.5 py-3 text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
          >
            {{ row.label }}
          </div>

          <div
            v-for="cell in row.cells"
            :key="cell"
            class="min-h-[140px] rounded-2xl border p-3.5"
            :class="getCellClasses(cell)"
          >
            <div class="flex items-start justify-between gap-2 mb-3">
              <div class="flex-1">
                <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">
                  {{ workspaceTalentGridBoxLabels[cell] }}
                </p>
                <p class="mt-1 text-[9px] text-muted/40 leading-tight">
                  {{ membersByBox.get(cell)?.length ?? 0 }} member{{ (membersByBox.get(cell)?.length ?? 0) !== 1 ? 's' : '' }}
                </p>
              </div>
            </div>

            <div class="flex flex-wrap gap-1.5">
              <div
                v-for="member in membersByBox.get(cell)"
                :key="member.id"
                class="rounded-full border border-muted/20 bg-default/80 px-2.5 py-0.5 text-[11px] font-semibold text-highlighted"
              >
                {{ member.name || "—" }}
              </div>
            </div>
          </div>
        </template>
      </div>
    </div>

    <!-- Member Cards -->
    <div
      v-if="block.members.length === 0"
      class="rounded-2xl border border-dashed border-muted/20 bg-elevated/5 py-10 text-center"
    >
      <div class="flex size-12 items-center justify-center rounded-xl bg-muted/10 text-muted/30 mx-auto">
        <UIcon name="i-lucide-users" size="24" />
      </div>
      <p class="mt-3 text-xs font-bold text-muted">No team members yet</p>
      <p class="mt-1 text-[11px] text-muted/60">Add members to assess and develop your team</p>
    </div>

    <div v-else class="space-y-3">
      <article
        v-for="member in block.members"
        :key="member.id"
        class="rounded-2xl border border-muted/20 bg-default/40 p-4 transition-all hover:border-muted/30"
      >
        <div class="flex flex-wrap items-start justify-between gap-3 mb-4">
          <div class="min-w-0 flex-1">
            <UInput
              :model-value="member.name"
              variant="none"
              placeholder="Name"
              class="w-full"
              :ui="{ base: 'px-0 text-base font-bold text-highlighted placeholder:text-muted/40' }"
              @update:model-value="
                mutateBlock(tabId, block.id, (entry) => {
                  if (entry.type !== 'talent-grid') return;
                  const target = entry.members.find((candidate) => candidate.id === member.id);
                  if (!target) return;
                  target.name = ($event ?? '').slice(0, 120);
                })
              "
            />
            <UInput
              :model-value="member.role"
              variant="none"
              placeholder="Role"
              class="mt-0.5"
              :ui="{ base: 'px-0 text-xs text-muted placeholder:text-muted/40' }"
              @update:model-value="
                mutateBlock(tabId, block.id, (entry) => {
                  if (entry.type !== 'talent-grid') return;
                  const target = entry.members.find((candidate) => candidate.id === member.id);
                  if (!target) return;
                  target.role = ($event ?? '').slice(0, 120);
                })
              "
            />
          </div>

          <div class="flex items-center gap-2 shrink-0">
            <UBadge
              :color="getCellTone(getTalentGridBoxKey(member.performance, member.potential))"
              variant="soft"
              size="sm"
              class="rounded-full"
            >
              {{
                workspaceTalentGridBoxLabels[
                  getTalentGridBoxKey(member.performance, member.potential)
                ]
              }}
            </UBadge>
            <UButton
              color="neutral"
              variant="ghost"
              icon="i-lucide-trash-2"
              size="sm"
              class="rounded-lg hover:text-error hover:bg-error/10"
              aria-label="Remove member"
              @click="removeMember(member.id)"
            />
          </div>
        </div>

        <div class="grid gap-3 sm:grid-cols-2">
          <div class="rounded-xl border border-muted/20 bg-elevated/10 p-3">
            <div class="flex items-center justify-between mb-2">
              <label class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                for="performance-{{ member.id }}"
              >
                Performance
              </label>
              <span class="text-xs font-black text-primary">{{ member.performance }}/5</span>
            </div>
            <input
              :id="'performance-' + member.id"
              :value="member.performance"
              type="range"
              min="1"
              max="5"
              step="1"
              class="h-1.5 w-full appearance-none rounded-full bg-muted/20 accent-primary cursor-pointer"
              @input="
                mutateBlock(tabId, block.id, (entry) => {
                  if (entry.type !== 'talent-grid') return;
                  const target = entry.members.find((candidate) => candidate.id === member.id);
                  if (!target) return;
                  target.performance = clampGridScore(
                    ($event.target as HTMLInputElement | null)?.value ?? '3',
                  );
                })
              "
            />
          </div>

          <div class="rounded-xl border border-muted/20 bg-elevated/10 p-3">
            <div class="flex items-center justify-between mb-2">
              <label class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                for="potential-{{ member.id }}"
              >
                Growth Potential
              </label>
              <span class="text-xs font-black text-primary">{{ member.potential }}/5</span>
            </div>
            <input
              :id="'potential-' + member.id"
              :value="member.potential"
              type="range"
              min="1"
              max="5"
              step="1"
              class="h-1.5 w-full appearance-none rounded-full bg-muted/20 accent-primary cursor-pointer"
              @input="
                mutateBlock(tabId, block.id, (entry) => {
                  if (entry.type !== 'talent-grid') return;
                  const target = entry.members.find((candidate) => candidate.id === member.id);
                  if (!target) return;
                  target.potential = clampGridScore(
                    ($event.target as HTMLInputElement | null)?.value ?? '3',
                  );
                })
              "
            />
          </div>
        </div>

        <div v-if="getBoxDescription(getTalentGridBoxKey(member.performance, member.potential))" class="mt-3 rounded-lg bg-muted/5 px-3 py-2">
          <p class="text-[10px] text-muted/70 leading-snug">
            {{ getBoxDescription(getTalentGridBoxKey(member.performance, member.potential)) }}
          </p>
        </div>
      </article>
    </div>
  </div>
</template>
