// apps/web/app/components/SignUpForm.vue
<script setup lang="ts">
import type { FormSubmitEvent } from "@nuxt/ui";
import * as z from "zod";

import { getErrorMessage } from "~/utils/get-error-message";

defineEmits<{
    switchToSignIn: [];
}>();

const authClient = useAuthClient();
const toast = useToast();
const loading = ref(false);

const schema = z.object({
    name: z.string().min(2, "Name must be at least 2 characters"),
    email: z.string().email("Invalid email address"),
    password: z.string().min(8, "Password must be at least 8 characters"),
});

type Schema = z.output<typeof schema>;

const state = reactive({
    name: "",
    email: "",
    password: "",
});

async function onSubmit(event: FormSubmitEvent<Schema>) {
    loading.value = true;

    try {
        await authClient.signUp.email(
            {
                name: event.data.name,
                email: event.data.email,
                password: event.data.password,
            },
            {
                onSuccess: () => {
                    toast.add({
                        title: "Account Created",
                        description:
                            "Welcome to Brainiac. Let's start thinking.",
                        color: "success",
                    });
                    navigateTo("/dashboard", { replace: true });
                },
                onError: (error) => {
                    toast.add({
                        title: "Sign up failed",
                        description: error.error.message,
                        color: "error",
                    });
                },
            },
        );
    } catch (error) {
        toast.add({
            title: "An unexpected error occurred",
            description: getErrorMessage(error, "Please try again."),
            color: "error",
        });
    } finally {
        loading.value = false;
    }
}
</script>

<template>
    <div class="flex flex-col gap-8">
        <!-- Header -->
        <header>
            <h1
                class="text-3xl font-bold tracking-tight text-neutral-900 dark:text-white"
            >
                Create Account
            </h1>
            <p class="mt-2 text-sm text-neutral-500 dark:text-neutral-400">
                Join 50k+ thinkers and builders on the infinite canvas.
            </p>
        </header>

        <!-- Form -->
        <UForm
            :schema="schema"
            :state="state"
            class="space-y-6"
            @submit="onSubmit"
        >
            <UFormField name="name" label="Full Name">
                <UInput
                    v-model="state.name"
                    placeholder="John Doe"
                    icon="i-lucide-user"
                    size="lg"
                    class="rounded-xl w-full"
                    :ui="{ base: 'rounded-xl' }"
                />
            </UFormField>

            <UFormField name="email" label="Email Address">
                <UInput
                    v-model="state.email"
                    type="email"
                    placeholder="name@company.com"
                    icon="i-lucide-mail"
                    size="lg"
                    class="rounded-xl w-full"
                    :ui="{ base: 'rounded-xl' }"
                />
            </UFormField>

            <UFormField name="password" label="Password">
                <UInput
                    v-model="state.password"
                    type="password"
                    placeholder="••••••••"
                    icon="i-lucide-lock"
                    size="lg"
                    class="rounded-xl w-full"
                    :ui="{ base: 'rounded-xl' }"
                />
            </UFormField>

            <UButton
                type="submit"
                color="primary"
                size="xl"
                block
                class="rounded-xl font-bold tracking-wide"
                :loading="loading"
            >
                Create Account
            </UButton>
        </UForm>

        <!-- Footer -->
        <p class="text-center text-sm text-neutral-500 dark:text-neutral-400">
            Already have an account?
            <ULink
                class="font-bold text-emerald-500 hover:text-emerald-600 transition-colors"
                @click="$emit('switchToSignIn')"
            >
                Sign In Instead
            </ULink>
        </p>
    </div>
</template>

// apps/web-start/src/components/auth/sign-up-form.tsx
import { useNavigate } from "@tanstack/react-router";
import { Loader2, Lock, Mail, User } from "lucide-react";
import * as React from "react";
import { z } from "zod";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "@/components/ui/toast";
import { signUp } from "@/lib/auth-client";
import { getErrorMessage } from "@/utils/get-error-message";

const schema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters"),
});

export function SignUpForm(props: { onSwitchToSignIn(): void }) {
  const navigate = useNavigate();
  const [loading, setLoading] = React.useState(false);
  const [errors, setErrors] = React.useState<Record<string, string>>({});

  async function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setLoading(true);
    setErrors({});

    const formData = new FormData(event.currentTarget);
    const parsed = schema.safeParse({
      name: formData.get("name"),
      email: formData.get("email"),
      password: formData.get("password"),
    });

    if (!parsed.success) {
      setErrors(Object.fromEntries(parsed.error.issues.map((issue) => [issue.path.join("."), issue.message])));
      setLoading(false);
      return;
    }

    try {
      await signUp.email(parsed.data, {
        onSuccess: () => {
          toast({ title: "Account created", description: "Welcome to Brainiac." });
          void navigate({ to: "/dashboard", replace: true });
        },
        onError: (error) => {
          toast({
            title: "Sign up failed",
            description: error.error.message,
            variant: "destructive",
          });
        },
      });
    } catch (error) {
      toast({
        title: "An unexpected error occurred",
        description: getErrorMessage(error, "Please try again."),
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <form className="flex flex-col gap-6" onSubmit={onSubmit}>
      <header>
        <h1 className="text-3xl font-bold tracking-normal">Create account</h1>
        <p className="mt-2 text-sm leading-6 text-muted-foreground">
          Start with a workspace and add structure as you work.
        </p>
      </header>

      <div className="grid gap-2">
        <Label htmlFor="name">Full name</Label>
        <div className="relative">
          <User className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input id="name" name="name" autoComplete="name" className="pl-11" placeholder="Ada Lovelace" />
        </div>
        {errors.name ? <p className="text-sm text-destructive">{errors.name}</p> : null}
      </div>

      <div className="grid gap-2">
        <Label htmlFor="signup-email">Email address</Label>
        <div className="relative">
          <Mail className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input id="signup-email" name="email" type="email" autoComplete="email" className="pl-11" placeholder="name@company.com" />
        </div>
        {errors.email ? <p className="text-sm text-destructive">{errors.email}</p> : null}
      </div>

      <div className="grid gap-2">
        <Label htmlFor="signup-password">Password</Label>
        <div className="relative">
          <Lock className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input id="signup-password" name="password" type="password" autoComplete="new-password" className="pl-11" placeholder="Password" />
        </div>
        {errors.password ? <p className="text-sm text-destructive">{errors.password}</p> : null}
      </div>

      <Button type="submit" size="lg" disabled={loading}>
        {loading ? <Loader2 className="size-4 animate-spin" /> : null}
        Create account
      </Button>

      <p className="text-center text-sm text-muted-foreground">
        Already have an account?{" "}
        <button type="button" className="font-bold text-primary hover:underline" onClick={props.onSwitchToSignIn}>
          Sign in instead
        </button>
      </p>
    </form>
  );
}
