// apps/web/app/components/dashboard/DashboardWorkspaceSidebar.vue
<script setup lang="ts">
type TeamOption = {
  label: string;
  value: string;
};

type DashboardSelectedNode = {
  title?: string | null;
  visibility?: string | null;
  teamId?: string | null;
};

const props = defineProps<{
  compact: boolean;
  teamsCount: number;
  newTeamName: string;
  selectedTeamId: string;
  teamItems: TeamOption[];
  selectedTeam: unknown;
  selectedNode: DashboardSelectedNode | null;
  canInvite: boolean;
  canManageSelectedNodeSharing: boolean;
  selectedNodeTeamRole: string | null;
  isSelectedNodeShared: boolean;
  isNodeShareActionPending: boolean;
  nodeShareActionLabel: string;
  nodeShareActionDisabled: boolean;
}>();

const emit = defineEmits<{
  "update:compact": [value: boolean];
  "update:newTeamName": [value: string];
  "update:selectedTeamId": [value: string];
  createTeam: [];
  openTeamSettings: [];
  toggleSelectedNodeSharing: [];
}>();

const sidebarClass = computed(() =>
  props.compact ? "w-14" : "w-[22rem] overflow-y-auto px-4 py-4 xl:w-[23rem]",
);
</script>

<template>
  <aside
    class="border-r border-neutral-200/80 bg-white/96 transition-[width] duration-200 ease-out dark:border-neutral-800/80 dark:bg-neutral-950/92"
    :class="sidebarClass"
  >
    <div v-if="compact" class="flex h-full flex-col items-center gap-3 py-4">
      <UButton
        icon="i-lucide-users"
        variant="ghost"
        color="neutral"
        size="md"
        square
        class="rounded-2xl"
        aria-label="Expand workspace sidebar"
        @click="emit('update:compact', false)"
      />
      <span
        class="text-[10px] font-semibold uppercase tracking-[0.22em] text-neutral-500 [writing-mode:vertical-rl]"
      >
        Team
      </span>
    </div>

    <template v-else>
      <div class="flex items-center justify-between gap-3">
        <h2 class="text-xs font-semibold uppercase tracking-[0.2em] text-neutral-500">Workspace</h2>
        <div class="flex items-center gap-2">
          <span class="text-[11px] font-medium text-neutral-500">{{ teamsCount }} total</span>
          <UButton
            icon="i-lucide-panel-left-close"
            variant="ghost"
            color="neutral"
            size="sm"
            square
            class="rounded-xl"
            aria-label="Compact workspace sidebar"
            @click="emit('update:compact', true)"
          />
        </div>
      </div>

      <div class="mt-4 flex items-center gap-2">
        <UInput
          :model-value="newTeamName"
          type="text"
          placeholder="New team name"
          size="sm"
          class="flex-1"
          @update:model-value="emit('update:newTeamName', String($event ?? ''))"
          @keydown.enter.prevent="emit('createTeam')"
        />
        <UButton
          label="Create"
          color="neutral"
          variant="soft"
          size="sm"
          @click="emit('createTeam')"
        />
      </div>

      <div class="mt-4">
        <label
          class="mb-1 block text-[11px] font-semibold uppercase tracking-[0.15em] text-neutral-500"
        >
          Share Target
        </label>
        <USelectMenu
          :model-value="selectedTeamId"
          :items="teamItems"
          value-key="value"
          placeholder="Select a team"
          size="sm"
          class="w-full"
          :search-input="{ placeholder: 'Find team' }"
          @update:model-value="emit('update:selectedTeamId', String($event ?? ''))"
        />
      </div>

      <div
        class="mt-4 rounded-2xl border border-neutral-200/80 bg-neutral-50/80 p-3 dark:border-neutral-800/80 dark:bg-neutral-900/70"
      >
        <p class="text-[11px] font-semibold uppercase tracking-[0.14em] text-neutral-500">
          Team Management
        </p>

        <p class="mt-2 text-xs text-neutral-500">
          Open the dedicated team settings modal to manage members and access rules.
        </p>

        <UButton
          label="Manage Team"
          color="primary"
          variant="solid"
          block
          size="sm"
          class="mt-3"
          :disabled="!selectedTeam"
          @click="emit('openTeamSettings')"
        />

        <div v-if="selectedTeam && !canInvite" class="mt-3 flex items-center gap-2">
          <UBadge color="neutral" variant="subtle" size="sm">Requires Owner</UBadge>
          <p class="text-xs text-neutral-500">
            Owner role is required for member and role changes.
          </p>
        </div>
      </div>

      <div
        class="mt-4 rounded-2xl border border-neutral-200/80 bg-neutral-50/80 p-3 dark:border-neutral-800/80 dark:bg-neutral-900/70"
      >
        <p class="text-[11px] font-semibold uppercase tracking-[0.14em] text-neutral-500">
          Selected Node
        </p>
        <p class="mt-1 truncate text-sm font-semibold text-neutral-900 dark:text-neutral-100">
          {{ selectedNode?.title ?? "No node selected" }}
        </p>
        <p class="mt-1 text-xs text-neutral-500">
          {{
            selectedNode
              ? selectedNode.visibility === "team"
                ? canManageSelectedNodeSharing
                  ? `Shared to ${selectedNode.teamId}`
                  : "Team-shared node"
                : "Private node"
              : "Click a node on canvas to share it."
          }}
        </p>
        <p
          v-if="selectedNode && !canManageSelectedNodeSharing"
          class="mt-1 text-xs text-neutral-500"
        >
          Role {{ selectedNodeTeamRole ?? "viewer" }} can edit content, but only owners can access
          sharing actions and team IDs.
        </p>
      </div>

      <div v-if="canManageSelectedNodeSharing" class="mt-3">
        <UButton
          :label="nodeShareActionLabel"
          block
          size="sm"
          :color="isSelectedNodeShared ? 'neutral' : 'primary'"
          :variant="isSelectedNodeShared ? 'outline' : 'solid'"
          :loading="isNodeShareActionPending"
          :disabled="nodeShareActionDisabled"
          @click="emit('toggleSelectedNodeSharing')"
        />
      </div>
    </template>
  </aside>
</template>

// apps/web-start/src/components/dashboard/dashboard-workspace-sidebar.tsx
import { useState, useCallback } from "react";
import { ChevronLeft, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";

type DashboardWorkspaceSidebarProps = {
  compact: boolean;
  onCompactChange: (compact: boolean) => void;
  teamsCount: number;
  selectedTeamId: string;
  onSelectedTeamChange: (teamId: string) => void;
  teams: Array<{ id: string; name: string }>;
  onCreateTeam: (name: string) => void;
  selectedNodeTitle: string | null;
  isSelectedNodeShared: boolean;
  canManageSharing: boolean;
  onToggleNodeSharing: () => void;
  onOpenTeamSettings: () => void;
};

export function DashboardWorkspaceSidebar({
  compact,
  onCompactChange,
  teamsCount,
  selectedTeamId,
  onSelectedTeamChange,
  teams,
  onCreateTeam,
  selectedNodeTitle,
  isSelectedNodeShared,
  canManageSharing,
  onToggleNodeSharing,
  onOpenTeamSettings,
}: DashboardWorkspaceSidebarProps) {
  const [newTeamName, setNewTeamName] = useState("");

  const handleCreateTeam = useCallback(() => {
    if (newTeamName.trim()) {
      onCreateTeam(newTeamName);
      setNewTeamName("");
    }
  }, [newTeamName, onCreateTeam]);

  const sidebarWidth = compact ? "w-14" : "w-[22rem]";

  if (compact) {
    return (
      <aside
        className={`${sidebarWidth} flex flex-col items-center gap-3 border-r bg-card py-4 transition-[width] duration-200`}
      >
        <Button
          size="lg"
          variant="ghost"
          className="h-10 w-10 rounded-2xl"
          onClick={() => onCompactChange(false)}
          title="Expand workspace sidebar"
        >
          <Users className="h-5 w-5" />
        </Button>
        <span className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground [writing-mode:vertical-rl]">
          Team
        </span>
      </aside>
    );
  }

  return (
    <aside className={`${sidebarWidth} border-r bg-card overflow-y-auto px-4 py-4 transition-[width] duration-200`}>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between gap-3">
          <h2 className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
            Workspace
          </h2>
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-medium text-muted-foreground">
              {teamsCount} total
            </span>
            <Button
              size="sm"
              variant="ghost"
              className="h-6 w-6 p-0"
              onClick={() => onCompactChange(true)}
              title="Compact workspace sidebar"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
          </div>
        </div>

        {/* Create Team */}
        <div className="space-y-2">
          <div className="flex gap-2">
            <Input
              placeholder="New team name"
              value={newTeamName}
              onChange={(e) => setNewTeamName(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleCreateTeam();
              }}
              size="sm"
              className="flex-1 h-9"
            />
            <Button
              size="sm"
              variant="secondary"
              onClick={handleCreateTeam}
              disabled={!newTeamName.trim()}
            >
              Create
            </Button>
          </div>
        </div>

        {/* Share Target */}
        <div className="space-y-2">
          <Label className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
            Share Target
          </Label>
          <Select value={selectedTeamId} onValueChange={onSelectedTeamChange}>
            <SelectTrigger size="sm">
              <SelectValue placeholder="Select a team" />
            </SelectTrigger>
            <SelectContent>
              {teams.map((team) => (
                <SelectItem key={team.id} value={team.id}>
                  {team.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Team Management */}
        <Card className="p-3">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
            Team Management
          </p>
          <p className="mt-2 text-xs text-muted-foreground">
            Open the dedicated team settings modal to manage members and access rules.
          </p>
          <Button
            block
            size="sm"
            onClick={onOpenTeamSettings}
            disabled={!selectedTeamId}
            className="mt-3 w-full"
          >
            Manage Team
          </Button>
        </Card>

        {/* Selected Node */}
        <Card className="p-3">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-muted-foreground">
            Selected Node
          </p>
          <p className="mt-1 truncate text-sm font-semibold">
            {selectedNodeTitle || "No node selected"}
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            {selectedNodeTitle
              ? isSelectedNodeShared
                ? `Shared to team`
                : "Private node"
              : "Click a node on canvas to share it."}
          </p>

          {canManageSharing && selectedNodeTitle && (
            <Button
              block
              size="sm"
              variant={isSelectedNodeShared ? "outline" : "default"}
              onClick={onToggleNodeSharing}
              className="mt-3 w-full"
            >
              {isSelectedNodeShared ? "Unshare Node" : "Share Node"}
            </Button>
          )}
        </Card>
      </div>
    </aside>
  );
}
