// apps/web/app/components/agency/AgencyMiniTimer.vue
<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import { storeToRefs } from "pinia";

import { useAgencyTimeTrackingStore } from "~/stores/agency-time-tracking";
import { withAgencyLiveQueryOptions } from "~/utils/agency-query-options";
import { formatDuration } from "~/utils/format-duration";

const props = defineProps<{
  teamId: string;
  taskId: string;
  projectId?: string;
  taskTitle?: string;
  projectName?: string;
}>();

const orpc = useOrpc();
const agencyTimeTrackingStore = useAgencyTimeTrackingStore();
const { isTimerMutationPending } = storeToRefs(agencyTimeTrackingStore);

const now = ref(Date.now());
let tickerHandle: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
  tickerHandle = setInterval(() => {
    now.value = Date.now();
  }, 1_000);
});

onBeforeUnmount(() => {
  if (tickerHandle) {
    clearInterval(tickerHandle);
    tickerHandle = null;
  }
});

const activeTimerQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.timer.getActive.queryOptions({
        input: { teamId: props.teamId || undefined },
      }),
      enabled: Boolean(props.teamId),
    }),
  ),
);

const activeTimer = computed(() => activeTimerQuery.data.value?.timer ?? null);
const isRunningForThisTask = computed(
  () => activeTimer.value?.taskId === props.taskId && activeTimer.value.teamId === props.teamId,
);

const elapsedSeconds = computed(() => {
  if (!activeTimer.value || !isRunningForThisTask.value) return 0;
  const startedAt = new Date(activeTimer.value.startedAt).getTime();
  if (Number.isNaN(startedAt)) return 0;
  return Math.max(0, Math.floor((now.value - startedAt) / 1_000));
});

async function toggleTimer() {
  if (!props.teamId || !props.projectId || !props.taskId) return;

  if (isRunningForThisTask.value && activeTimer.value) {
    await agencyTimeTrackingStore.stopTimer({
      teamId: props.teamId,
      description: activeTimer.value.description,
      linkUrl: activeTimer.value.linkUrl ?? "",
      tagIds: activeTimer.value.tags.map((t) => t.id),
      selectedTags: activeTimer.value.tags,
    });
    return;
  }

  await agencyTimeTrackingStore.startTimer({
    teamId: props.teamId,
    project: { id: props.projectId, name: props.projectName ?? "" },
    task: { id: props.taskId, title: props.taskTitle ?? "" },
    description: "",
    linkUrl: "",
    tagIds: [],
    selectedTags: [],
    successDescription: "Timer started for this task.",
  });
}
</script>

<template>
  <UButton
    :icon="isRunningForThisTask ? 'i-lucide-square' : 'i-lucide-play'"
    :color="isRunningForThisTask ? 'warning' : 'primary'"
    :variant="isRunningForThisTask ? 'soft' : 'solid'"
    size="xs"
    class="tabular-nums"
    :disabled="!projectId || !taskId || isTimerMutationPending"
    :loading="isTimerMutationPending"
    @click="toggleTimer"
  >
    {{ isRunningForThisTask ? formatDuration(elapsedSeconds) : "Track" }}
  </UButton>
</template>

// apps/web/src/components/agency/agency-mini-timer.tsx
import { useQuery } from "@tanstack/react-query";
import { Play, Square } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { orpc } from "@/lib/orpc";
import { withAgencyLiveQueryOptions } from "@/lib/utils/agency-query-options";
import { formatDuration } from "@/lib/utils/format-duration";
import {
  selectIsTimerMutationPending,
  useAgencyTimeTrackingStore,
} from "@/stores/agency-time-tracking";

type AgencyMiniTimerProps = {
  teamId: string;
  taskId: string;
  projectId?: string;
  taskTitle?: string;
  projectName?: string;
};

export function AgencyMiniTimer({
  teamId,
  taskId,
  projectId,
  taskTitle,
  projectName,
}: AgencyMiniTimerProps) {
  const agencyTimeTrackingStore = useAgencyTimeTrackingStore();
  const isTimerMutationPending = useAgencyTimeTrackingStore(selectIsTimerMutationPending);
  const [now, setNow] = useState(Date.now());

  useEffect(() => {
    const tickerHandle = setInterval(() => setNow(Date.now()), 1_000);
    return () => clearInterval(tickerHandle);
  }, []);

  const activeTimerQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.timer.getActive.queryOptions({
        input: { teamId: teamId || undefined },
      }),
      enabled: Boolean(teamId),
    }),
  );

  const activeTimer = activeTimerQuery.data?.timer ?? null;
  const isRunningForThisTask =
    activeTimer?.taskId === taskId && activeTimer.teamId === teamId;

  const elapsedSeconds = useMemo(() => {
    if (!activeTimer || !isRunningForThisTask) return 0;
    const startedAt = new Date(activeTimer.startedAt).getTime();
    if (Number.isNaN(startedAt)) return 0;
    return Math.max(0, Math.floor((now - startedAt) / 1_000));
  }, [activeTimer, isRunningForThisTask, now]);

  async function toggleTimer() {
    if (!teamId || !projectId || !taskId) return;

    if (isRunningForThisTask && activeTimer) {
      await agencyTimeTrackingStore.stopTimer({
        teamId,
        description: activeTimer.description,
        linkUrl: activeTimer.linkUrl ?? "",
        tagIds: activeTimer.tags.map((t) => t.id),
        selectedTags: activeTimer.tags,
      });
      return;
    }

    await agencyTimeTrackingStore.startTimer({
      teamId,
      project: { id: projectId, name: projectName ?? "" },
      task: { id: taskId, title: taskTitle ?? "" },
      description: "",
      linkUrl: "",
      tagIds: [],
      selectedTags: [],
      successDescription: "Timer started for this task.",
    });
  }

  return (
    <Button
      variant={isRunningForThisTask ? "secondary" : "default"}
      size="sm"
      className="tabular-nums"
      disabled={!projectId || !taskId || isTimerMutationPending}
      onClick={() => void toggleTimer()}
    >
      {isTimerMutationPending ? (
        <Square className="animate-pulse" />
      ) : isRunningForThisTask ? (
        <Square />
      ) : (
        <Play />
      )}
      {isRunningForThisTask ? formatDuration(elapsedSeconds) : "Track"}
    </Button>
  );
}
