// apps/web/app/components/agency/AgencySegmentBar.vue
<script setup lang="ts">
/**
 * In-page agency section tabs. The shell topbar keeps team + current section;
 * this strip carries full segment navigation without crowding the shell.
 */
import type { AgencySegmentId } from "./agency-segments";
import { AGENCY_SEGMENTS } from "./agency-segments";
import {
  shellFocusRingClass,
  shellInPageSubnavClass,
  shellSegmentTabActiveClass,
  shellSegmentTabClass,
} from "~/utils/app-shell-ui";

const props = defineProps<{
  segment: AgencySegmentId;
}>();

const emit = defineEmits<{
  "update:segment": [value: AgencySegmentId];
}>();

function tabIdFor(segmentId: AgencySegmentId) {
  return `agency-tab-${segmentId}`;
}

function panelIdFor(segmentId: AgencySegmentId) {
  return `agency-panel-${segmentId}`;
}

function selectSegment(nextSegment: AgencySegmentId) {
  if (nextSegment === props.segment) return;
  emit("update:segment", nextSegment);
}

function handleTabKeydown(event: KeyboardEvent, index: number) {
  const lastIndex = AGENCY_SEGMENTS.length - 1;
  let nextIndex = index;

  if (event.key === "ArrowRight") {
    event.preventDefault();
    nextIndex = index >= lastIndex ? 0 : index + 1;
  } else if (event.key === "ArrowLeft") {
    event.preventDefault();
    nextIndex = index <= 0 ? lastIndex : index - 1;
  } else if (event.key === "Home") {
    event.preventDefault();
    nextIndex = 0;
  } else if (event.key === "End") {
    event.preventDefault();
    nextIndex = lastIndex;
  } else {
    return;
  }

  const nextSegment = AGENCY_SEGMENTS[nextIndex];
  if (nextSegment) selectSegment(nextSegment.id);
}
</script>

<template>
  <nav :class="shellInPageSubnavClass" role="tablist" aria-label="Agency sections">
    <div
      class="flex items-center gap-1 overflow-x-auto py-2.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
    >
      <button
        v-for="(entry, index) in AGENCY_SEGMENTS"
        :id="tabIdFor(entry.id)"
        :key="entry.id"
        type="button"
        role="tab"
        :aria-selected="entry.id === segment"
        :aria-controls="panelIdFor(entry.id)"
        :tabindex="entry.id === segment ? 0 : -1"
        :class="[
          shellSegmentTabClass,
          shellFocusRingClass,
          entry.id === segment ? shellSegmentTabActiveClass : '',
        ]"
        :title="`${entry.label} (g ${entry.shortcutKey})`"
        @click="selectSegment(entry.id)"
        @keydown="handleTabKeydown($event, index)"
      >
        <UIcon :name="entry.icon" class="size-3.5" />
        <span>{{ entry.label }}</span>
      </button>
    </div>
  </nav>
</template>

// apps/web/src/components/agency/agency-segment-bar.tsx
import type { AgencySegmentId } from "@/lib/agency-segments";
import { AGENCY_SEGMENTS } from "@/lib/agency-segments";
import { LucideIcon } from "@/lib/lucide-icon";
import {
  shellFocusRingClass,
  shellInPageSubnavClass,
  shellSegmentTabActiveClass,
  shellSegmentTabClass,
} from "@/lib/utils/app-shell-ui";

type AgencySegmentBarProps = {
  segment: AgencySegmentId;
  onSegmentChange: (segment: AgencySegmentId) => void;
};

function tabIdFor(segmentId: AgencySegmentId) {
  return `agency-tab-${segmentId}`;
}

function panelIdFor(segmentId: AgencySegmentId) {
  return `agency-panel-${segmentId}`;
}

export function AgencySegmentBar({ segment, onSegmentChange }: AgencySegmentBarProps) {
  function selectSegment(nextSegment: AgencySegmentId) {
    if (nextSegment === segment) return;
    onSegmentChange(nextSegment);
  }

  function handleTabKeydown(event: React.KeyboardEvent<HTMLButtonElement>, index: number) {
    const lastIndex = AGENCY_SEGMENTS.length - 1;
    let nextIndex = index;

    if (event.key === "ArrowRight") {
      event.preventDefault();
      nextIndex = index >= lastIndex ? 0 : index + 1;
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      nextIndex = index <= 0 ? lastIndex : index - 1;
    } else if (event.key === "Home") {
      event.preventDefault();
      nextIndex = 0;
    } else if (event.key === "End") {
      event.preventDefault();
      nextIndex = lastIndex;
    } else {
      return;
    }

    const nextSegment = AGENCY_SEGMENTS[nextIndex];
    if (nextSegment) selectSegment(nextSegment.id);
  }

  return (
    <nav className={shellInPageSubnavClass} role="tablist" aria-label="Agency sections">
      <div className="flex items-center gap-1 overflow-x-auto py-2.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        {AGENCY_SEGMENTS.map((entry, index) => (
          <button
            key={entry.id}
            id={tabIdFor(entry.id)}
            type="button"
            role="tab"
            aria-selected={entry.id === segment}
            aria-controls={panelIdFor(entry.id)}
            tabIndex={entry.id === segment ? 0 : -1}
            className={[
              shellSegmentTabClass,
              shellFocusRingClass,
              entry.id === segment ? shellSegmentTabActiveClass : "",
            ].join(" ")}
            title={`${entry.label} (g ${entry.shortcutKey})`}
            onClick={() => selectSegment(entry.id)}
            onKeyDown={(event) => handleTabKeydown(event, index)}
          >
            <LucideIcon name={entry.icon} className="size-3.5" />
            <span>{entry.label}</span>
          </button>
        ))}
      </div>
    </nav>
  );
}
