// apps/web/app/components/agency/AgencyTimeEntryActions.vue
<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    entry: { id: string; projectName: string; taskTitle?: string | null };
    canRestart?: boolean;
    deleting?: boolean;
  }>(),
  {
    canRestart: true,
    deleting: false,
  },
);

const entryLabel = computed(() => props.entry.taskTitle || props.entry.projectName);

const emit = defineEmits<{
  edit: [];
  restart: [];
  delete: [];
}>();
</script>

<template>
  <div class="flex shrink-0 items-center gap-1.5">
    <UButton
      color="neutral"
      variant="ghost"
      size="xs"
      icon="i-lucide-pencil"
      :aria-label="`Edit ${entryLabel} entry`"
      @click="emit('edit')"
    />
    <UButton
      color="neutral"
      variant="ghost"
      size="xs"
      icon="i-lucide-play"
      :disabled="!props.canRestart"
      :aria-label="`Restart timer for ${entryLabel}`"
      @click="emit('restart')"
    />
    <UButton
      color="error"
      variant="ghost"
      size="xs"
      icon="i-lucide-trash-2"
      :loading="props.deleting"
      :aria-label="`Delete ${entryLabel} entry`"
      @click="emit('delete')"
    />
  </div>
</template>

// apps/web/src/components/agency/agency-time-entry-actions.tsx
import { Pencil, Play, Square, Trash2 } from "lucide-react";

import { Button } from "@/components/ui/button";

type AgencyTimeEntryActionsProps = {
  entry: { id: string; projectName: string; taskTitle?: string | null };
  canRestart?: boolean;
  deleting?: boolean;
  onEdit: () => void;
  onRestart: () => void;
  onDelete: () => void;
};

export function AgencyTimeEntryActions({
  entry,
  canRestart = true,
  deleting = false,
  onEdit,
  onRestart,
  onDelete,
}: AgencyTimeEntryActionsProps) {
  const entryLabel = entry.taskTitle || entry.projectName;

  return (
    <div className="flex shrink-0 items-center gap-1.5">
      <Button
        variant="ghost"
        size="sm"
        aria-label={`Edit ${entryLabel} entry`}
        onClick={onEdit}
      >
        <Pencil />
      </Button>
      <Button
        variant="ghost"
        size="sm"
        disabled={!canRestart}
        aria-label={`Restart timer for ${entryLabel}`}
        onClick={onRestart}
      >
        <Play />
      </Button>
      <Button
        variant="ghost"
        size="sm"
        disabled={deleting}
        aria-label={`Delete ${entryLabel} entry`}
        onClick={onDelete}
      >
        {deleting ? <Square className="animate-pulse" /> : <Trash2 />}
      </Button>
    </div>
  );
}
