// apps/web/app/components/agency/AgencyTaskList.vue
<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import type { SelectMenuItem } from "@nuxt/ui";

import { getErrorMessage } from "~/utils/get-error-message";
import { withAgencyLiveQueryOptions } from "~/utils/agency-query-options";
import { useAgencyOpsStore } from "~/stores/agency-ops";
import { useAuthSession } from "~/composables/useAuthClient";
import AgencyMiniTimer from "~/components/agency/AgencyMiniTimer.vue";

type Project = {
  id: string;
  clientName: string;
  name: string;
};

type AgencyProjectTask = {
  id: string;
  teamId: string;
  projectId: string;
  title: string;
  status: "open" | "in_progress" | "done" | "archived";
  assigneeUserId: string | null;
  assigneeName: string | null;
  assigneeAvatar: string | null;
  dueDate: string | null;
};

type TaskStatus = AgencyProjectTask["status"];

const ALL_ASSIGNEES_VALUE = "__all_assignees__";
const ALL_PROJECTS_VALUE = "__all_projects__";
const UNASSIGNED_ASSIGNEE_VALUE = "__unassigned__";

const props = defineProps<{
  teamId: string;
  projects: Project[];
  selectedTaskId: string;
}>();

const emit = defineEmits<{
  select: [taskId: string];
  "select-project": [projectId: string];
}>();

const orpc = useOrpc();
const agencyOps = useAgencyOpsStore();
const authSession = useAuthSession();

const teamId = computed(() => props.teamId);
const currentUserId = computed(() => authSession.value?.data?.user?.id ?? "");
const statusFilter = ref<TaskStatus[]>(["open", "in_progress"]);
const assigneeFilter = ref(ALL_ASSIGNEES_VALUE);
const projectFilter = ref(ALL_PROJECTS_VALUE);
const search = ref("");
const titleDraft = ref("");
const selectedProjectIdForCreate = ref("");

const selectedStatusFilter = computed(() =>
  statusFilter.value.length > 0 ? statusFilter.value : undefined,
);
const selectedAssigneeFilter = computed(() =>
  assigneeFilter.value === ALL_ASSIGNEES_VALUE ? undefined : assigneeFilter.value,
);

watch(
  currentUserId,
  (id) => {
    if (id && assigneeFilter.value === ALL_ASSIGNEES_VALUE) {
      assigneeFilter.value = id;
    }
  },
  { immediate: true },
);

const membersQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.taskThreads.members.list.queryOptions({
        input: { teamId: teamId.value },
      }),
      enabled: Boolean(teamId.value),
    }),
  ),
);

const tasksQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.projectTasks.list.queryOptions({
        input: {
          teamId: teamId.value,
          statuses: selectedStatusFilter.value,
          assigneeUserId: selectedAssigneeFilter.value,
          search: search.value || undefined,
        },
      }),
      enabled: Boolean(teamId.value),
    }),
  ),
);

const tasksQueryKey = computed(
  () =>
    orpc.agencyOps.projectTasks.list.queryOptions({
      input: {
        teamId: teamId.value,
        statuses: selectedStatusFilter.value,
        assigneeUserId: selectedAssigneeFilter.value,
        search: search.value || undefined,
      },
    }).queryKey,
);

watch(
  tasksQueryKey,
  (next, prev) => {
    if (prev) agencyOps.unregisterProjectTasksQuery(prev);
    if (teamId.value) {
      agencyOps.registerProjectTasksQuery({ queryKey: next, teamId: teamId.value });
    }
  },
  { immediate: true },
);

onUnmounted(() => {
  agencyOps.unregisterProjectTasksQuery(tasksQueryKey.value);
});

const tasks = computed(() => {
  let items = tasksQuery.data.value?.items ?? [];
  if (projectFilter.value !== ALL_PROJECTS_VALUE) {
    items = items.filter((t) => t.projectId === projectFilter.value);
  }
  return items;
});

const members = computed(() => membersQuery.data.value?.items ?? []);
const isTasksLoading = computed(() => tasksQuery.isPending.value);
const isTasksError = computed(() => tasksQuery.isError.value);
const isMembersLoading = computed(() => membersQuery.isPending.value);
const isTaskUpdatePending = computed(() => agencyOps.isTaskMutationPending);

const statusOptions: SelectMenuItem[] = [
  { label: "Open", value: "open" },
  { label: "In progress", value: "in_progress" },
  { label: "Done", value: "done" },
  { label: "Archived", value: "archived" },
];

const assigneeOptions = computed<SelectMenuItem[]>(() => [
  { label: "All assignees", value: ALL_ASSIGNEES_VALUE },
  ...members.value.map((m) => ({
    label: m.userName,
    value: m.userId,
    avatar: m.userAvatar ?? undefined,
  })),
]);

const rowAssigneeOptions = computed<SelectMenuItem[]>(() => [
  { label: "Unassigned", value: UNASSIGNED_ASSIGNEE_VALUE },
  ...members.value.map((m) => ({
    label: m.userName,
    value: m.userId,
    avatar: m.userAvatar ?? undefined,
  })),
]);

const projectOptions = computed<SelectMenuItem[]>(() => [
  { label: "All projects", value: ALL_PROJECTS_VALUE },
  ...props.projects.map((p) => ({
    label: `${p.clientName} · ${p.name}`,
    value: p.id,
  })),
]);

const createProjectOptions = computed<SelectMenuItem[]>(() =>
  props.projects.map((p) => ({
    label: `${p.clientName} · ${p.name}`,
    value: p.id,
  })),
);

function statusDotColor(status: string) {
  switch (status) {
    case "open":
      return "bg-muted";
    case "in_progress":
      return "bg-primary";
    case "done":
      return "bg-success";
    case "archived":
      return "bg-muted";
    default:
      return "bg-muted";
  }
}

function toDateInputValue(iso: string | null): string {
  if (!iso) return "";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10);
}

function toDueDateIso(value: string): string | null {
  if (!value) return null;
  return new Date(`${value}T12:00:00.000Z`).toISOString();
}

function formatDueDate(iso: string | null): string {
  if (!iso) return "";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function getAssigneeMenuValue(task: AgencyProjectTask) {
  return task.assigneeUserId ?? UNASSIGNED_ASSIGNEE_VALUE;
}

function getAssigneePatchValue(value: string) {
  return value === UNASSIGNED_ASSIGNEE_VALUE ? null : value;
}

function isOverdue(iso: string | null): boolean {
  if (!iso) return false;
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return false;
  return date.setHours(23, 59, 59, 999) < Date.now();
}

async function createTask() {
  const title = titleDraft.value.trim();
  const projectId = selectedProjectIdForCreate.value;
  if (!title || !projectId || !teamId.value) return;

  titleDraft.value = "";
  selectedProjectIdForCreate.value = "";

  await agencyOps.createProjectTask({
    teamId: teamId.value,
    projectId,
    title,
  });
}

function selectTask(taskId: string) {
  emit("select", taskId);
}

async function updateTask(
  task: AgencyProjectTask,
  patch: Partial<Pick<AgencyProjectTask, "status" | "assigneeUserId" | "dueDate">>,
) {
  try {
    await agencyOps.updateProjectTask({
      teamId: teamId.value,
      taskId: task.id,
      ...patch,
    });
  } catch {
    // Store surfaces the toast.
  }
}

function getProjectHue(projectId: string) {
  const index = props.projects.findIndex((p) => p.id === projectId);
  if (index === -1) return "bg-neutral-400";
  const hues = [
    "bg-rose-400",
    "bg-amber-400",
    "bg-emerald-400",
    "bg-sky-400",
    "bg-violet-400",
    "bg-fuchsia-400",
  ];
  return hues[index % hues.length];
}
</script>

<template>
  <section class="flex h-full flex-col rounded-2xl border border-default bg-default">
    <header class="border-b border-default px-4 py-3">
      <div class="flex flex-wrap items-center gap-2">
        <UInput
          v-model="search"
          icon="i-lucide-search"
          placeholder="Search tasks"
          size="sm"
          class="min-w-0 flex-1"
        />
        <USelectMenu
          v-model="statusFilter"
          :items="statusOptions"
          size="sm"
          class="w-36"
          value-key="value"
          multiple
        />
        <USelectMenu
          v-model="assigneeFilter"
          :items="assigneeOptions"
          size="sm"
          class="w-32"
          value-key="value"
        />
        <USelectMenu
          v-model="projectFilter"
          :items="projectOptions"
          size="sm"
          class="w-40"
          value-key="value"
        />
      </div>

      <form class="mt-2 flex gap-2" @submit.prevent="createTask">
        <USelectMenu
          v-model="selectedProjectIdForCreate"
          :items="createProjectOptions"
          placeholder="Project"
          size="sm"
          class="w-40"
          value-key="value"
        />
        <UInput v-model="titleDraft" placeholder="Add a task" size="sm" class="min-w-0 flex-1" />
        <UButton
          type="submit"
          icon="i-lucide-plus"
          color="primary"
          size="sm"
          aria-label="Add task"
          :loading="agencyOps.isTaskMutationPending"
          :disabled="
            !titleDraft.trim() || !selectedProjectIdForCreate || agencyOps.isTaskMutationPending
          "
        />
      </form>
    </header>

    <div v-if="isTasksLoading" class="flex-1 space-y-2 overflow-y-auto p-4">
      <div
        v-for="rowIndex in 5"
        :key="rowIndex"
        class="h-12 animate-pulse rounded-xl bg-elevated/60"
      />
    </div>

    <div
      v-else-if="isTasksError"
      class="flex flex-1 flex-col items-center justify-center p-6 text-center"
      role="alert"
    >
      <UIcon name="i-lucide-alert-triangle" class="size-5 text-error" />
      <p class="mt-3 text-sm font-bold text-highlighted">Couldn't load tasks.</p>
      <p class="mt-1 text-xs text-muted">
        {{ getErrorMessage(tasksQuery.error.value, "Try refreshing.") }}
      </p>
      <UButton
        label="Retry"
        color="neutral"
        variant="soft"
        size="xs"
        class="mt-3"
        @click="tasksQuery.refetch()"
      />
    </div>

    <div
      v-else-if="tasks.length === 0"
      class="flex flex-1 flex-col items-center justify-center p-6 text-center"
    >
      <UIcon name="i-lucide-list-checks" class="size-6 text-muted" />
      <p class="mt-3 text-xs text-muted">No tasks match your filters.</p>
    </div>

    <ul v-else class="flex-1 divide-y divide-default overflow-y-auto" role="listbox" aria-label="Tasks">
      <li
        v-for="task in tasks"
        :key="task.id"
        role="option"
        :aria-selected="task.id === selectedTaskId"
        class="cursor-pointer px-4 py-3 transition-colors hover:bg-elevated/50 focus-visible:bg-elevated/50 focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-primary/20 focus-visible:ring-inset"
        :class="task.id === selectedTaskId ? 'bg-primary/5' : ''"
        tabindex="0"
        @click="selectTask(task.id)"
        @keydown.enter.prevent="selectTask(task.id)"
        @keydown.space.prevent="selectTask(task.id)"
      >
        <div class="flex items-start gap-3">
          <span
            class="mt-1.5 size-2 shrink-0 rounded-full"
            :class="[statusDotColor(task.status)]"
            :title="task.status"
          />
          <div class="min-w-0 flex-1">
            <p class="truncate text-sm font-bold text-highlighted">{{ task.title }}</p>
            <div class="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted">
              <span class="inline-flex items-center gap-1">
                <span class="size-1.5 rounded-full" :class="getProjectHue(task.projectId)" />
                {{ projects.find((p) => p.id === task.projectId)?.name ?? "Project" }}
              </span>
              <span v-if="task.assigneeName" class="inline-flex items-center gap-1 truncate">
                ·
                <UAvatar
                  :src="task.assigneeAvatar ?? undefined"
                  :alt="task.assigneeName"
                  :text="task.assigneeName.slice(0, 2)"
                  size="3xs"
                />
                {{ task.assigneeName }}
              </span>
              <span v-if="task.dueDate" :class="isOverdue(task.dueDate) ? 'text-error' : ''">
                · {{ formatDueDate(task.dueDate) }}
              </span>
            </div>
            <div class="mt-2 grid grid-cols-4 gap-1" @click.stop>
              <USelectMenu
                :model-value="task.status"
                :items="statusOptions"
                size="xs"
                value-key="value"
                :disabled="isTaskUpdatePending"
                @update:model-value="
                  updateTask(task, { status: $event as AgencyProjectTask['status'] })
                "
              />
              <USelectMenu
                :model-value="getAssigneeMenuValue(task)"
                :items="rowAssigneeOptions"
                size="xs"
                value-key="value"
                :disabled="isMembersLoading || isTaskUpdatePending"
                @update:model-value="
                  updateTask(task, { assigneeUserId: getAssigneePatchValue($event as string) })
                "
              />
              <UInput
                type="date"
                size="xs"
                :model-value="toDateInputValue(task.dueDate)"
                :disabled="isTaskUpdatePending"
                @update:model-value="updateTask(task, { dueDate: toDueDateIso(String($event)) })"
              />
              <div @click.stop>
                <AgencyMiniTimer
                  :team-id="teamId"
                  :task-id="task.id"
                  :project-id="task.projectId"
                  :task-title="task.title"
                  :project-name="projects.find((p) => p.id === task.projectId)?.name"
                />
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </section>
</template>

// apps/web/src/components/agency/agency-task-list.tsx
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ListChecks, Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { AgencyMiniTimer } from "@/components/agency/agency-mini-timer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { authClient } from "@/lib/auth-client";
import { orpc } from "@/lib/orpc";
import { withAgencyLiveQueryOptions } from "@/lib/utils/agency-query-options";
import { getErrorMessage } from "@/lib/utils/get-error-message";
import {
  selectIsTaskMutationPending,
  useAgencyOpsStore,
} from "@/stores/agency-ops";

type Project = {
  id: string;
  clientName: string;
  name: string;
};

type AgencyProjectTask = {
  id: string;
  teamId: string;
  projectId: string;
  title: string;
  status: "open" | "in_progress" | "done" | "archived";
  assigneeUserId: string | null;
  assigneeName: string | null;
  assigneeAvatar: string | null;
  dueDate: string | null;
};

type TaskStatus = AgencyProjectTask["status"];

const ALL_ASSIGNEES_VALUE = "__all_assignees__";
const ALL_PROJECTS_VALUE = "__all_projects__";
const UNASSIGNED_ASSIGNEE_VALUE = "__unassigned__";

type AgencyTaskListProps = {
  teamId: string;
  projects: Project[];
  selectedTaskId: string;
  onSelect: (taskId: string) => void;
  onSelectProject: (projectId: string) => void;
};

const STATUS_OPTIONS: Array<{ label: string; value: TaskStatus }> = [
  { label: "Open", value: "open" },
  { label: "In progress", value: "in_progress" },
  { label: "Done", value: "done" },
  { label: "Archived", value: "archived" },
];

function statusDotColor(status: string) {
  switch (status) {
    case "open":
      return "bg-muted";
    case "in_progress":
      return "bg-primary";
    case "done":
      return "bg-success";
    case "archived":
      return "bg-muted";
    default:
      return "bg-muted";
  }
}

function toDateInputValue(iso: string | null): string {
  if (!iso) return "";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";
  return date.toISOString().slice(0, 10);
}

function toDueDateIso(value: string): string | null {
  if (!value) return null;
  return new Date(`${value}T12:00:00.000Z`).toISOString();
}

function formatDueDate(iso: string | null): string {
  if (!iso) return "";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function isOverdue(iso: string | null): boolean {
  if (!iso) return false;
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return false;
  return date.setHours(23, 59, 59, 999) < Date.now();
}

function getProjectHue(projectId: string, projects: Project[]) {
  const index = projects.findIndex((p) => p.id === projectId);
  if (index === -1) return "bg-neutral-400";
  const hues = [
    "bg-rose-400",
    "bg-amber-400",
    "bg-emerald-400",
    "bg-sky-400",
    "bg-violet-400",
    "bg-fuchsia-400",
  ];
  return hues[index % hues.length];
}

export function AgencyTaskList({
  teamId,
  projects,
  selectedTaskId,
  onSelect,
}: AgencyTaskListProps) {
  const agencyOps = useAgencyOpsStore();
  const isTaskMutationPending = useAgencyOpsStore(selectIsTaskMutationPending);
  const session = authClient.useSession();
  const currentUserId = session.data?.user?.id ?? "";

  const [statusFilter, setStatusFilter] = useState<TaskStatus[]>(["open", "in_progress"]);
  const [assigneeFilter, setAssigneeFilter] = useState(ALL_ASSIGNEES_VALUE);
  const [projectFilter, setProjectFilter] = useState(ALL_PROJECTS_VALUE);
  const [search, setSearch] = useState("");
  const [titleDraft, setTitleDraft] = useState("");
  const [selectedProjectIdForCreate, setSelectedProjectIdForCreate] = useState("");

  useEffect(() => {
    if (currentUserId && assigneeFilter === ALL_ASSIGNEES_VALUE) {
      setAssigneeFilter(currentUserId);
    }
  }, [currentUserId, assigneeFilter]);

  const selectedStatusFilter = statusFilter.length > 0 ? statusFilter : undefined;
  const selectedAssigneeFilter =
    assigneeFilter === ALL_ASSIGNEES_VALUE ? undefined : assigneeFilter;

  const membersQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.taskThreads.members.list.queryOptions({ input: { teamId } }),
      enabled: Boolean(teamId),
    }),
  );

  const tasksQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.projectTasks.list.queryOptions({
        input: {
          teamId,
          statuses: selectedStatusFilter,
          assigneeUserId: selectedAssigneeFilter,
          search: search || undefined,
        },
      }),
      enabled: Boolean(teamId),
    }),
  );

  const tasksQueryKey = orpc.agencyOps.projectTasks.list.queryOptions({
    input: {
      teamId,
      statuses: selectedStatusFilter,
      assigneeUserId: selectedAssigneeFilter,
      search: search || undefined,
    },
  }).queryKey;

  useEffect(() => {
    if (!teamId) return;
    agencyOps.registerProjectTasksQuery({ queryKey: tasksQueryKey, teamId });
    return () => agencyOps.unregisterProjectTasksQuery(tasksQueryKey);
  }, [teamId, tasksQueryKey, agencyOps]);

  const tasks = useMemo(() => {
    let items = tasksQuery.data?.items ?? [];
    if (projectFilter !== ALL_PROJECTS_VALUE) {
      items = items.filter((t) => t.projectId === projectFilter);
    }
    return items;
  }, [tasksQuery.data?.items, projectFilter]);

  const members = membersQuery.data?.items ?? [];

  async function createTask() {
    const title = titleDraft.trim();
    const projectId = selectedProjectIdForCreate;
    if (!title || !projectId || !teamId) return;

    setTitleDraft("");
    setSelectedProjectIdForCreate("");

    await agencyOps.createProjectTask({ teamId, projectId, title });
  }

  async function updateTask(
    task: AgencyProjectTask,
    patch: Partial<Pick<AgencyProjectTask, "status" | "assigneeUserId" | "dueDate">>,
  ) {
    try {
      await agencyOps.updateProjectTask({
        teamId,
        taskId: task.id,
        ...patch,
      });
    } catch {
      // Store surfaces the toast.
    }
  }

  return (
    <section className="flex h-full flex-col rounded-2xl border border-default bg-default">
      <header className="border-b border-default px-4 py-3">
        <div className="flex flex-wrap items-center gap-2">
          <div className="relative min-w-0 flex-1">
            <Search className="absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted" />
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search tasks"
              className="pl-9"
            />
          </div>
          <select
            multiple
            value={statusFilter}
            onChange={(e) =>
              setStatusFilter(
                Array.from(e.target.selectedOptions).map((opt) => opt.value as TaskStatus),
              )
            }
            className="h-9 w-36 rounded-md border border-default bg-background px-2 text-xs"
          >
            {STATUS_OPTIONS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <select
            value={assigneeFilter}
            onChange={(e) => setAssigneeFilter(e.target.value)}
            className="h-9 w-32 rounded-md border border-default bg-background px-2 text-xs"
          >
            <option value={ALL_ASSIGNEES_VALUE}>All assignees</option>
            {members.map((member) => (
              <option key={member.userId} value={member.userId}>
                {member.userName}
              </option>
            ))}
          </select>
          <select
            value={projectFilter}
            onChange={(e) => setProjectFilter(e.target.value)}
            className="h-9 w-40 rounded-md border border-default bg-background px-2 text-xs"
          >
            <option value={ALL_PROJECTS_VALUE}>All projects</option>
            {projects.map((project) => (
              <option key={project.id} value={project.id}>
                {project.clientName} · {project.name}
              </option>
            ))}
          </select>
        </div>

        <form
          className="mt-2 flex gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            void createTask();
          }}
        >
          <select
            value={selectedProjectIdForCreate}
            onChange={(e) => setSelectedProjectIdForCreate(e.target.value)}
            className="h-9 w-40 rounded-md border border-default bg-background px-2 text-xs"
          >
            <option value="">Project</option>
            {projects.map((project) => (
              <option key={project.id} value={project.id}>
                {project.clientName} · {project.name}
              </option>
            ))}
          </select>
          <Input
            value={titleDraft}
            onChange={(e) => setTitleDraft(e.target.value)}
            placeholder="Add a task"
            className="min-w-0 flex-1"
          />
          <Button
            type="submit"
            size="sm"
            aria-label="Add task"
            disabled={!titleDraft.trim() || !selectedProjectIdForCreate || isTaskMutationPending}
          >
            <Plus />
          </Button>
        </form>
      </header>

      {tasksQuery.isPending ? (
        <div className="flex-1 space-y-2 overflow-y-auto p-4">
          {[1, 2, 3, 4, 5].map((rowIndex) => (
            <Skeleton key={rowIndex} className="h-12 rounded-xl" />
          ))}
        </div>
      ) : tasksQuery.isError ? (
        <div className="flex flex-1 flex-col items-center justify-center p-6 text-center" role="alert">
          <AlertTriangle className="size-5 text-error" />
          <p className="mt-3 text-sm font-bold text-highlighted">Couldn't load tasks.</p>
          <p className="mt-1 text-xs text-muted">
            {getErrorMessage(tasksQuery.error, "Try refreshing.")}
          </p>
          <Button variant="secondary" size="sm" className="mt-3" onClick={() => void tasksQuery.refetch()}>
            Retry
          </Button>
        </div>
      ) : tasks.length === 0 ? (
        <div className="flex flex-1 flex-col items-center justify-center p-6 text-center">
          <ListChecks className="size-6 text-muted" />
          <p className="mt-3 text-xs text-muted">No tasks match your filters.</p>
        </div>
      ) : (
        <ul className="flex-1 divide-y divide-default overflow-y-auto" role="listbox" aria-label="Tasks">
          {tasks.map((task) => (
            <li
              key={task.id}
              role="option"
              aria-selected={task.id === selectedTaskId}
              className={[
                "cursor-pointer px-4 py-3 transition-colors hover:bg-elevated/50 focus-visible:bg-elevated/50 focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-primary/20 focus-visible:ring-inset",
                task.id === selectedTaskId ? "bg-primary/5" : "",
              ].join(" ")}
              tabIndex={0}
              onClick={() => onSelect(task.id)}
              onKeyDown={(event) => {
                if (event.key === "Enter" || event.key === " ") {
                  event.preventDefault();
                  onSelect(task.id);
                }
              }}
            >
              <div className="flex items-start gap-3">
                <span
                  className={["mt-1.5 size-2 shrink-0 rounded-full", statusDotColor(task.status)].join(
                    " ",
                  )}
                  title={task.status}
                />
                <div className="min-w-0 flex-1">
                  <p className="truncate text-sm font-bold text-highlighted">{task.title}</p>
                  <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted">
                    <span className="inline-flex items-center gap-1">
                      <span
                        className={["size-1.5 rounded-full", getProjectHue(task.projectId, projects)].join(
                          " ",
                        )}
                      />
                      {projects.find((p) => p.id === task.projectId)?.name ?? "Project"}
                    </span>
                    {task.assigneeName ? (
                      <span className="inline-flex items-center gap-1 truncate">
                        · {task.assigneeName}
                      </span>
                    ) : null}
                    {task.dueDate ? (
                      <span className={isOverdue(task.dueDate) ? "text-error" : ""}>
                        · {formatDueDate(task.dueDate)}
                      </span>
                    ) : null}
                  </div>
                  <div className="mt-2 grid grid-cols-4 gap-1" onClick={(e) => e.stopPropagation()}>
                    <select
                      value={task.status}
                      disabled={isTaskMutationPending}
                      onChange={(e) =>
                        void updateTask(task, {
                          status: e.target.value as AgencyProjectTask["status"],
                        })
                      }
                      className="h-8 rounded-md border border-default bg-background px-1 text-[11px]"
                    >
                      {STATUS_OPTIONS.map((option) => (
                        <option key={option.value} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                    <select
                      value={task.assigneeUserId ?? UNASSIGNED_ASSIGNEE_VALUE}
                      disabled={membersQuery.isPending || isTaskMutationPending}
                      onChange={(e) =>
                        void updateTask(task, {
                          assigneeUserId:
                            e.target.value === UNASSIGNED_ASSIGNEE_VALUE ? null : e.target.value,
                        })
                      }
                      className="h-8 rounded-md border border-default bg-background px-1 text-[11px]"
                    >
                      <option value={UNASSIGNED_ASSIGNEE_VALUE}>Unassigned</option>
                      {members.map((member) => (
                        <option key={member.userId} value={member.userId}>
                          {member.userName}
                        </option>
                      ))}
                    </select>
                    <Input
                      type="date"
                      value={toDateInputValue(task.dueDate)}
                      disabled={isTaskMutationPending}
                      onChange={(e) =>
                        void updateTask(task, { dueDate: toDueDateIso(e.target.value) })
                      }
                      className="h-8 px-1 text-[11px]"
                    />
                    <div onClick={(e) => e.stopPropagation()}>
                      <AgencyMiniTimer
                        teamId={teamId}
                        taskId={task.id}
                        projectId={task.projectId}
                        taskTitle={task.title}
                        projectName={projects.find((p) => p.id === task.projectId)?.name}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
