// apps/web/app/components/agency/AgencyVoiceRecorder.vue
<script setup lang="ts">
import AgencyTaskMediaPlayer from "~/components/agency/AgencyTaskMediaPlayer.vue";

const props = defineProps<{
  disabled?: boolean;
}>();

const emit = defineEmits<{
  recorded: [file: File, durationSeconds: number];
}>();

const isRecording = ref(false);
const recordedBlob = ref<Blob | null>(null);
const recordedUrl = ref("");
const recordingSeconds = ref(0);

let mediaRecorder: MediaRecorder | null = null;
let chunks: Blob[] = [];
let timerHandle: ReturnType<typeof setInterval> | null = null;

async function startRecording() {
  if (props.disabled) return;

  const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
  mediaRecorder = new MediaRecorder(stream);
  chunks = [];

  mediaRecorder.ondataavailable = (event) => {
    if (event.data.size > 0) {
      chunks.push(event.data);
    }
  };

  mediaRecorder.onstop = () => {
    const blob = new Blob(chunks, { type: "audio/webm" });
    recordedBlob.value = blob;
    recordedUrl.value = URL.createObjectURL(blob);
    stopTimer();
  };

  mediaRecorder.start();
  isRecording.value = true;
  recordingSeconds.value = 0;
  timerHandle = setInterval(() => {
    recordingSeconds.value += 1;
  }, 1_000);
}

function stopRecording() {
  mediaRecorder?.stop();
  mediaRecorder?.stream.getTracks().forEach((track) => track.stop());
  isRecording.value = false;
}

function stopTimer() {
  if (timerHandle) {
    clearInterval(timerHandle);
    timerHandle = null;
  }
}

function sendRecording() {
  if (!recordedBlob.value) return;
  const file = new File([recordedBlob.value], `voice-${Date.now()}.webm`, {
    type: "audio/webm",
  });
  emit("recorded", file, recordingSeconds.value);
  discardRecording();
}

function discardRecording() {
  recordedBlob.value = null;
  recordedUrl.value = "";
  recordingSeconds.value = 0;
}

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${String(secs).padStart(2, "0")}`;
}

onBeforeUnmount(() => {
  stopRecording();
  stopTimer();
});
</script>

<template>
  <div class="inline-flex items-center gap-1">
    <UButton
      v-if="!isRecording && !recordedUrl"
      icon="i-lucide-mic"
      color="neutral"
      variant="ghost"
      size="xs"
      :disabled="disabled"
      @click="startRecording"
    />

    <template v-else-if="isRecording">
      <span class="text-xs tabular-nums text-error">{{ formatDuration(recordingSeconds) }}</span>
      <UButton
        icon="i-lucide-square"
        color="error"
        variant="soft"
        size="xs"
        @click="stopRecording"
      />
    </template>

    <template v-else-if="recordedUrl">
      <AgencyTaskMediaPlayer
        :src="recordedUrl"
        mime-type="audio/webm"
        file-name="Recorded voice message"
        compact
      />
      <UButton
        icon="i-lucide-send"
        color="primary"
        variant="soft"
        size="xs"
        @click="sendRecording"
      />
      <UButton
        icon="i-lucide-trash-2"
        color="neutral"
        variant="ghost"
        size="xs"
        @click="discardRecording"
      />
    </template>
  </div>
</template>

// apps/web/src/components/agency/agency-voice-recorder.tsx
import { Mic, Send, Square, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { Button } from "@/components/ui/button";
import { AgencyTaskMediaPlayer } from "./agency-task-media-player";

type AgencyVoiceRecorderProps = {
  disabled?: boolean;
  onRecorded: (file: File, durationSeconds: number) => void;
};

function formatRecordingDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${String(secs).padStart(2, "0")}`;
}

export function AgencyVoiceRecorder({ disabled = false, onRecorded }: AgencyVoiceRecorderProps) {
  const [isRecording, setIsRecording] = useState(false);
  const [recordedBlob, setRecordedBlob] = useState<Blob | null>(null);
  const [recordedUrl, setRecordedUrl] = useState("");
  const [recordingSeconds, setRecordingSeconds] = useState(0);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const chunksRef = useRef<Blob[]>([]);
  const timerHandleRef = useRef<ReturnType<typeof setInterval> | null>(null);

  function stopTimer() {
    if (timerHandleRef.current) {
      clearInterval(timerHandleRef.current);
      timerHandleRef.current = null;
    }
  }

  function stopRecording() {
    mediaRecorderRef.current?.stop();
    mediaRecorderRef.current?.stream.getTracks().forEach((track) => track.stop());
    setIsRecording(false);
  }

  async function startRecording() {
    if (disabled) return;

    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    const mediaRecorder = new MediaRecorder(stream);
    mediaRecorderRef.current = mediaRecorder;
    chunksRef.current = [];

    mediaRecorder.ondataavailable = (event) => {
      if (event.data.size > 0) {
        chunksRef.current.push(event.data);
      }
    };

    mediaRecorder.onstop = () => {
      const blob = new Blob(chunksRef.current, { type: "audio/webm" });
      setRecordedBlob(blob);
      setRecordedUrl(URL.createObjectURL(blob));
      stopTimer();
    };

    mediaRecorder.start();
    setIsRecording(true);
    setRecordingSeconds(0);
    timerHandleRef.current = setInterval(() => {
      setRecordingSeconds((value) => value + 1);
    }, 1_000);
  }

  function sendRecording() {
    if (!recordedBlob) return;
    const file = new File([recordedBlob], `voice-${Date.now()}.webm`, {
      type: "audio/webm",
    });
    onRecorded(file, recordingSeconds);
    discardRecording();
  }

  function discardRecording() {
    if (recordedUrl) {
      URL.revokeObjectURL(recordedUrl);
    }
    setRecordedBlob(null);
    setRecordedUrl("");
    setRecordingSeconds(0);
  }

  useEffect(() => {
    return () => {
      stopRecording();
      stopTimer();
      if (recordedUrl) {
        URL.revokeObjectURL(recordedUrl);
      }
    };
  }, [recordedUrl]);

  return (
    <div className="inline-flex items-center gap-1">
      {!isRecording && !recordedUrl ? (
        <Button
          variant="ghost"
          size="sm"
          disabled={disabled}
          aria-label="Record voice message"
          onClick={() => void startRecording()}
        >
          <Mic />
        </Button>
      ) : isRecording ? (
        <>
          <span className="text-xs tabular-nums text-error">
            {formatRecordingDuration(recordingSeconds)}
          </span>
          <Button variant="secondary" size="sm" onClick={stopRecording}>
            <Square />
          </Button>
        </>
      ) : (
        <>
          <AgencyTaskMediaPlayer
            src={recordedUrl}
            mimeType="audio/webm"
            fileName="Recorded voice message"
            compact
          />
          <Button variant="secondary" size="sm" onClick={sendRecording}>
            <Send />
          </Button>
          <Button variant="ghost" size="sm" onClick={discardRecording}>
            <Trash2 />
          </Button>
        </>
      )}
    </div>
  );
}
