// apps/web/app/components/agency/AgencySegmentBar.vue
<script setup lang="ts">
/**
 * In-page agency section tabs. The shell topbar keeps team + current section;
 * this strip carries full segment navigation without crowding the shell.
 */
import type { AgencySegmentId } from "./agency-segments";
import { AGENCY_SEGMENTS } from "./agency-segments";
import {
  shellFocusRingClass,
  shellInPageSubnavClass,
  shellSegmentTabActiveClass,
  shellSegmentTabClass,
} from "~/utils/app-shell-ui";

const props = defineProps<{
  segment: AgencySegmentId;
}>();

const emit = defineEmits<{
  "update:segment": [value: AgencySegmentId];
}>();

function tabIdFor(segmentId: AgencySegmentId) {
  return `agency-tab-${segmentId}`;
}

function panelIdFor(segmentId: AgencySegmentId) {
  return `agency-panel-${segmentId}`;
}

function selectSegment(nextSegment: AgencySegmentId) {
  if (nextSegment === props.segment) return;
  emit("update:segment", nextSegment);
}

function handleTabKeydown(event: KeyboardEvent, index: number) {
  const lastIndex = AGENCY_SEGMENTS.length - 1;
  let nextIndex = index;

  if (event.key === "ArrowRight") {
    event.preventDefault();
    nextIndex = index >= lastIndex ? 0 : index + 1;
  } else if (event.key === "ArrowLeft") {
    event.preventDefault();
    nextIndex = index <= 0 ? lastIndex : index - 1;
  } else if (event.key === "Home") {
    event.preventDefault();
    nextIndex = 0;
  } else if (event.key === "End") {
    event.preventDefault();
    nextIndex = lastIndex;
  } else {
    return;
  }

  const nextSegment = AGENCY_SEGMENTS[nextIndex];
  if (nextSegment) selectSegment(nextSegment.id);
}
</script>

<template>
  <nav :class="shellInPageSubnavClass" role="tablist" aria-label="Agency sections">
    <div
      class="flex items-center gap-1 overflow-x-auto py-2.5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"
    >
      <button
        v-for="(entry, index) in AGENCY_SEGMENTS"
        :id="tabIdFor(entry.id)"
        :key="entry.id"
        type="button"
        role="tab"
        :aria-selected="entry.id === segment"
        :aria-controls="panelIdFor(entry.id)"
        :tabindex="entry.id === segment ? 0 : -1"
        :class="[
          shellSegmentTabClass,
          shellFocusRingClass,
          entry.id === segment ? shellSegmentTabActiveClass : '',
        ]"
        :title="`${entry.label} (g ${entry.shortcutKey})`"
        @click="selectSegment(entry.id)"
        @keydown="handleTabKeydown($event, index)"
      >
        <UIcon :name="entry.icon" class="size-3.5" />
        <span>{{ entry.label }}</span>
      </button>
    </div>
  </nav>
</template>

// apps/web/src/features/shared/segment/agency-segment-bar.tsx
import { useEffect } from "react";

import type { AgencySegmentId } from "@/features/shared/agency-segments";
import { AGENCY_SEGMENTS } from "@/features/shared/agency-segments";
import { LucideIcon } from "@/lib/lucide-icon";
import {
  shellFocusRingClass,
  shellInPageSubnavClass,
  shellSegmentTabActiveClass,
  shellSegmentTabClass,
} from "@/lib/utils/app-shell-ui";
import { cn } from "@/lib/utils";

type AgencySegmentBarProps = {
  segment: AgencySegmentId;
  onSegmentChange: (segment: AgencySegmentId) => void;
  /** Renders inline in the topbar breadcrumb instead of the in-page subnav strip. */
  variant?: "page" | "breadcrumb";
};

function tabIdFor(segmentId: AgencySegmentId) {
  return `agency-tab-${segmentId}`;
}

function panelIdFor(segmentId: AgencySegmentId) {
  return `agency-panel-${segmentId}`;
}

export function AgencySegmentBar({
  segment,
  onSegmentChange,
  variant = "page",
}: AgencySegmentBarProps) {
  const isBreadcrumb = variant === "breadcrumb";

  function selectSegment(nextSegment: AgencySegmentId) {
    if (nextSegment === segment) return;
    onSegmentChange(nextSegment);
  }

  function handleTabKeydown(event: React.KeyboardEvent<HTMLButtonElement>, index: number) {
    const lastIndex = AGENCY_SEGMENTS.length - 1;
    let nextIndex = index;

    if (event.key === "ArrowRight") {
      event.preventDefault();
      nextIndex = index >= lastIndex ? 0 : index + 1;
    } else if (event.key === "ArrowLeft") {
      event.preventDefault();
      nextIndex = index <= 0 ? lastIndex : index - 1;
    } else if (event.key === "Home") {
      event.preventDefault();
      nextIndex = 0;
    } else if (event.key === "End") {
      event.preventDefault();
      nextIndex = lastIndex;
    } else {
      return;
    }

    const nextSegment = AGENCY_SEGMENTS[nextIndex];
    if (nextSegment) selectSegment(nextSegment.id);
  }

  useEffect(() => {
    let pendingPrefix = false;
    let prefixTimer: ReturnType<typeof setTimeout> | null = null;

    function clearPrefix() {
      pendingPrefix = false;
      if (prefixTimer) {
        clearTimeout(prefixTimer);
        prefixTimer = null;
      }
    }

    function handleKeydown(event: KeyboardEvent) {
      if (event.metaKey || event.ctrlKey || event.altKey) {
        clearPrefix();
        return;
      }
      const target = event.target as HTMLElement | null;
      if (
        target &&
        (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.isContentEditable)
      ) {
        clearPrefix();
        return;
      }

      const key = event.key.toLowerCase();

      if (!pendingPrefix) {
        if (key === "g") {
          pendingPrefix = true;
          prefixTimer = setTimeout(clearPrefix, 1_000);
          return;
        }
        return;
      }

      const match = AGENCY_SEGMENTS.find((entry) => entry.shortcutKey === key);
      if (match) {
        event.preventDefault();
        selectSegment(match.id);
      }
      clearPrefix();
    }

    window.addEventListener("keydown", handleKeydown);
    return () => {
      window.removeEventListener("keydown", handleKeydown);
      clearPrefix();
    };
  }, [segment, onSegmentChange]);

  return (
    <nav
      className={cn(isBreadcrumb ? "min-w-0" : shellInPageSubnavClass)}
      role="tablist"
      aria-label="Agency sections"
    >
      <div
        className={cn(
          "flex items-center gap-1 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
          isBreadcrumb ? "max-w-full py-0" : "py-2.5",
        )}
      >
        {AGENCY_SEGMENTS.map((entry, index) => (
          <button
            key={entry.id}
            id={tabIdFor(entry.id)}
            type="button"
            role="tab"
            aria-selected={entry.id === segment}
            aria-controls={panelIdFor(entry.id)}
            tabIndex={entry.id === segment ? 0 : -1}
            className={cn(
              shellSegmentTabClass,
              shellFocusRingClass,
              isBreadcrumb && "shrink-0 px-2.5 py-1",
              entry.id === segment && shellSegmentTabActiveClass,
            )}
            title={`${entry.label} (g ${entry.shortcutKey})`}
            onClick={() => selectSegment(entry.id)}
            onKeyDown={(event) => handleTabKeydown(event, index)}
          >
            <LucideIcon name={entry.icon} className="size-3.5" />
            <span>{entry.label}</span>
          </button>
        ))}
      </div>
    </nav>
  );
}
