// apps/web/app/components/dashboard/DashboardAgentChatPanel.vue
<script setup lang="ts">
import type { WorkspaceNode } from "@brainiac/workspace";
import { nextTick, toRef, useTemplateRef, watch } from "vue";

const props = defineProps<{
  nodes: WorkspaceNode[];
}>();

const chatViewport = useTemplateRef<HTMLDivElement>("chatViewport");
const {
  addMentionedNode,
  activeMention,
  canSend,
  draft,
  error,
  isPending,
  mentionSuggestions,
  messages,
  promptSuggestions,
  removeMentionedNode,
  resetChat,
  selectedNodes,
  sendMessage,
} = useDashboardAgentChat(toRef(props, "nodes"));

async function scrollToBottom() {
  await nextTick();
  const element = chatViewport.value;

  if (!element) {
    return;
  }

  element.scrollTop = element.scrollHeight;
}

function handleSubmit() {
  if (activeMention.value && mentionSuggestions.value.length > 0) {
    const firstSuggestion = mentionSuggestions.value[0];

    if (firstSuggestion) {
      addMentionedNode(firstSuggestion);
    }
  }

  void sendMessage();
}

function handlePromptClick(prompt: string) {
  void sendMessage(prompt);
}

function handleMentionClick(node: WorkspaceNode) {
  addMentionedNode(node);
}

function handleEnterKeydown(event: KeyboardEvent) {
  event.preventDefault();
  handleSubmit();
}

watch(
  () => [messages.value.length, isPending.value],
  () => {
    void scrollToBottom();
  },
);
</script>

<template>
  <section
    class="flex min-h-[420px] flex-col overflow-hidden rounded-[28px] border border-muted/60 bg-default shadow-lg shadow-black/5"
  >
    <div class="border-b border-muted/60 bg-elevated/50 px-5 py-4">
      <div class="flex items-start justify-between gap-3">
        <div>
          <p class="text-[11px] font-semibold uppercase tracking-[0.28em] text-primary">
            Agent Chat
          </p>
          <h2 class="mt-2 text-lg font-semibold tracking-tight text-highlighted">
            Workspace-aware copilot
          </h2>
          <p class="mt-1 text-sm text-muted">
            Ask about priorities, gaps, node structure, or what the dashboard is signaling.
          </p>
        </div>

        <div class="flex items-center gap-2">
          <UBadge color="neutral" variant="subtle"> {{ nodes.length }} nodes </UBadge>
          <UButton
            color="neutral"
            variant="ghost"
            size="sm"
            icon="i-lucide-rotate-ccw"
            :disabled="messages.length === 0 && !draft"
            @click="resetChat"
          >
            Reset
          </UButton>
        </div>
      </div>
    </div>

    <div
      ref="chatViewport"
      class="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto bg-elevated/20 px-4 py-4"
    >
      <template v-if="messages.length === 0">
        <div class="rounded-3xl border border-dashed border-primary/30 bg-primary/5 p-4">
          <p class="text-sm font-medium text-highlighted">Start with a concrete question.</p>
          <p class="mt-1 text-sm text-muted">
            The agent can inspect live dashboard nodes, search them, and pull node details before
            answering.
          </p>
        </div>

        <div class="flex flex-wrap gap-2">
          <UButton
            v-for="prompt in promptSuggestions"
            :key="prompt"
            color="neutral"
            variant="soft"
            size="sm"
            class="rounded-full"
            @click="handlePromptClick(prompt)"
          >
            {{ prompt }}
          </UButton>
        </div>
      </template>

      <article
        v-for="message in messages"
        :key="message.id"
        class="flex"
        :class="message.role === 'user' ? 'justify-end' : 'justify-start'"
      >
        <div
          class="max-w-[92%] rounded-[24px] border px-4 py-3 text-sm shadow-sm"
          :class="
            message.role === 'user'
              ? 'border-primary/30 bg-primary/10 text-highlighted'
              : 'border-muted/70 bg-default text-toned'
          "
        >
          <p class="whitespace-pre-wrap leading-6">
            {{ message.content }}
          </p>

          <p
            v-if="message.role === 'user' && message.contextNodeTitles?.length"
            class="mt-2 text-[11px] font-medium uppercase tracking-[0.18em] opacity-70"
          >
            Context · {{ message.contextNodeTitles.join(", ") }}
          </p>

          <p
            v-if="message.role === 'assistant' && (message.model || message.toolsCalled?.length)"
            class="mt-2 text-[11px] font-medium uppercase tracking-[0.18em] opacity-70"
          >
            {{ message.model }}
            <template v-if="message.toolsCalled?.length">
              · {{ message.toolsCalled.join(", ") }}
            </template>
          </p>
        </div>
      </article>

      <article v-if="isPending" class="flex justify-start">
        <div
          class="flex items-center gap-2 rounded-[24px] border border-muted/70 bg-default px-4 py-3 text-sm text-muted shadow-sm"
        >
          <UIcon name="i-lucide-loader-2" class="size-4 animate-spin" />
          Reading the dashboard
        </div>
      </article>
    </div>

    <div class="border-t border-muted/60 bg-default px-4 py-4">
      <UAlert
        v-if="error"
        color="error"
        variant="soft"
        icon="i-lucide-alert-circle"
        title="Agent request failed"
        :description="error"
        class="mb-3"
      />

      <UTextarea
        v-model="draft"
        :rows="4"
        autoresize
        placeholder="Ask the agent about this dashboard. Type @ to narrow the turn to a node."
        @keydown.enter.exact="handleEnterKeydown"
      />

      <div v-if="selectedNodes.length > 0" class="mt-3 flex flex-wrap items-center gap-2">
        <p class="text-xs font-medium uppercase tracking-[0.18em] text-muted">Context</p>

        <button
          v-for="node in selectedNodes"
          :key="node.id"
          type="button"
          class="inline-flex items-center gap-1 rounded-full border border-primary/25 bg-primary/8 px-3 py-1 text-xs font-medium text-highlighted transition hover:border-primary/40 hover:bg-primary/12"
          @click="removeMentionedNode(node.id)"
        >
          <span>{{ node.title }}</span>
          <UIcon name="i-lucide-x" class="size-3" />
        </button>
      </div>

      <div v-if="activeMention" class="mt-3 rounded-2xl border border-muted/70 bg-elevated/40 p-2">
        <div v-if="mentionSuggestions.length > 0" class="flex flex-col gap-1">
          <button
            v-for="node in mentionSuggestions"
            :key="node.id"
            type="button"
            class="flex items-center justify-between gap-3 rounded-xl px-3 py-2 text-left text-sm text-toned transition hover:bg-default"
            @click="handleMentionClick(node)"
          >
            <span class="min-w-0 truncate font-medium text-highlighted">
              {{ node.title }}
            </span>
            <span class="truncate text-xs text-muted">
              {{ node.label || node.id }}
            </span>
          </button>
        </div>

        <p v-else class="px-3 py-2 text-sm text-muted">
          No nodes match
          <span class="font-medium text-highlighted">{{ `@${activeMention.query}` }}</span
          >.
        </p>
      </div>

      <div class="mt-3 flex items-center justify-between gap-3">
        <p class="text-xs text-muted">
          Press Enter to send. Use Shift+Enter for a new line. Type @ to scope the turn.
        </p>

        <UButton
          color="primary"
          icon="i-lucide-send"
          :loading="isPending"
          :disabled="!canSend"
          @click="handleSubmit"
        >
          Send
        </UButton>
      </div>
    </div>
  </section>
</template>

// apps/web/src/components/dashboard/dashboard-agent-chat-panel.tsx
import type { WorkspaceNode } from "@brainiac/workspace";
import { Loader2, Send, Sparkles, X } from "lucide-react";
import { useState } from "react";

import { DashboardAgentModelLibrary } from "@/components/dashboard/dashboard-agent-model-library";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useDashboardAgentChat } from "@/hooks/use-dashboard-agent-chat";
import { dashboardEmptyPanelClass, dashboardLabelClass } from "@/lib/utils/dashboard-ui";
import { renderSimpleMarkdown } from "@/lib/utils/render-simple-markdown";
import { cn } from "@/lib/utils";

type DashboardAgentChatPanelProps = {
  nodes: WorkspaceNode[];
  activeTabId?: string | null;
  scopeKind?: "nodes" | "blocks";
  onClose?: () => void;
  scopeBadges?: React.ReactNode;
};

export function DashboardAgentChatPanel({
  nodes,
  activeTabId = null,
  scopeKind = "nodes",
  onClose,
  scopeBadges,
}: DashboardAgentChatPanelProps) {
  const chat = useDashboardAgentChat(nodes, activeTabId);
  const [isModelLibraryOpen, setIsModelLibraryOpen] = useState(false);

  return (
    <div className="relative flex h-full min-h-0 flex-col">
      <DashboardAgentModelLibrary
        open={isModelLibraryOpen}
        onOpenChange={setIsModelLibraryOpen}
        modelSearch={chat.modelSearch}
        onModelSearchChange={chat.setModelSearch}
        filteredModelOptions={chat.filteredModelOptions}
        selectedModelId={chat.selectedModelId}
        onSelectModel={chat.setConversationDraftModelId}
        onToggleFavorite={chat.toggleFavoriteModel}
        isFavoriteModel={chat.isFavoriteModel}
        favoritesOnly={chat.favoritesOnly}
        onFavoritesOnlyChange={chat.setFavoritesOnly}
      />

      <header className="flex items-start justify-between gap-3 border-b border-default px-4 py-3">
        <div className="min-w-0">
          <p className={dashboardLabelClass}>Agent</p>
          <p className="truncate text-sm font-semibold text-highlighted">{chat.activeConversationTitle}</p>
          <p className="truncate text-xs text-muted">{chat.scopeLabel}</p>
        </div>
        {onClose ? (
          <Button variant="ghost" size="icon" aria-label="Close agent panel" onClick={onClose}>
            <X className="size-4" />
          </Button>
        ) : null}
      </header>

      {scopeBadges ? <div className="border-b border-default px-4 py-2">{scopeBadges}</div> : null}

      <div className="min-h-0 flex-1 space-y-3 overflow-y-auto px-4 py-4">
        {chat.messages.length === 0 ? (
          <div className={cn(dashboardEmptyPanelClass, "text-left")}>
            <Sparkles className="size-5 text-primary" />
            <p className="mt-3 text-sm font-semibold text-highlighted">
              {scopeKind === "blocks" ? "Ask about blocks in scope" : "Ask about your workspace"}
            </p>
            <div className="mt-3 space-y-2">
              {chat.promptSuggestions.map((suggestion) => (
                <button
                  key={suggestion}
                  type="button"
                  className="block w-full rounded-xl border border-muted/60 px-3 py-2 text-left text-sm text-muted transition hover:border-primary/30 hover:bg-muted/20"
                  onClick={() => void chat.sendMessage(suggestion)}
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>
        ) : (
          chat.messages.map((message) => (
            <div
              key={message.id}
              className={cn(
                "rounded-2xl border px-3 py-2 text-sm",
                message.role === "assistant"
                  ? "border-default bg-muted/20 text-highlighted"
                  : "border-primary/20 bg-primary/5 text-highlighted",
              )}
            >
              <p className="mb-1 text-[10px] font-bold uppercase tracking-widest text-muted">{message.role}</p>
              <div
                className="prose prose-sm dark:prose-invert max-w-none"
                dangerouslySetInnerHTML={{ __html: renderSimpleMarkdown(message.content) }}
              />
            </div>
          ))
        )}

        {chat.isPending ? (
          <div className="inline-flex items-center gap-2 text-sm text-muted">
            <Loader2 className="size-4 animate-spin" />
            Working…
          </div>
        ) : null}

        {chat.error ? (
          <div className="rounded-xl border border-destructive/30 bg-destructive/5 px-3 py-2 text-sm text-destructive">
            {chat.error}
          </div>
        ) : null}
      </div>

      <div className="border-t border-default p-4">
        {chat.selectedNodes.length > 0 ? (
          <div className="mb-2 flex flex-wrap gap-1.5">
            {chat.selectedNodes.map((node) => (
              <Badge key={node.id} variant="secondary" className="rounded-full">
                {node.title}
                <button type="button" className="ml-1" onClick={() => chat.removeMentionedNode(node.id)}>
                  ×
                </button>
              </Badge>
            ))}
          </div>
        ) : null}

        <div className="flex items-end gap-2">
          <Textarea
            value={chat.draft}
            rows={3}
            placeholder={scopeKind === "blocks" ? "Ask about blocks in scope" : "Ask about anything"}
            onChange={(event) => chat.setDraft(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter" && !event.shiftKey) {
                event.preventDefault();
                void chat.sendMessage();
              }
            }}
          />
          <Button disabled={!chat.canSend} onClick={() => void chat.sendMessage()}>
            {chat.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}
          </Button>
        </div>

        <div className="mt-2 flex flex-wrap items-center gap-2">
          <Button variant="ghost" size="sm" onClick={() => setIsModelLibraryOpen(true)}>
            Models
          </Button>
          <Button variant="ghost" size="sm" onClick={() => chat.startNewConversation()}>
            New chat
          </Button>
          {chat.selectedModelOption ? (
            <span className="text-xs text-muted">{chat.selectedModelOption.name}</span>
          ) : null}
        </div>
      </div>
    </div>
  );
}
