// apps/web/app/components/workspace/WorkspaceEditorModal.vue
<script setup lang="ts">
import {
  WORKSPACE_NODE_DASHBOARD_DETAIL_LIMIT,
  type WorkspaceNodeDashboardFeaturedBlock,
  type WorkspaceNodeDashboardSelectableBlock,
  type WorkspaceNodeTint,
  type WorkspaceNodeType,
} from "@brainiac/workspace";

import { getWorkspaceBlockRegistryEntry } from "~/utils/workspace-block-registry";
import {
  getWorkspaceNodeTintStyle,
  workspaceNodeTintOptions,
} from "~/utils/workspace-node-dashboard";

const props = defineProps<{
  availableBlocks: WorkspaceNodeDashboardSelectableBlock[];
  content: string;
  featuredBlocks: WorkspaceNodeDashboardFeaturedBlock[];
  mode: "create" | "edit";
  nodeType: WorkspaceNodeType;
  open: boolean;
  tint: WorkspaceNodeTint;
  title: string;
  valid: boolean;
}>();

const emit = defineEmits<{
  close: [];
  submit: [];
  "update:featured-blocks": [value: WorkspaceNodeDashboardFeaturedBlock[]];
  "update:content": [value: string];
  "update:node-type": [value: WorkspaceNodeType];
  "update:tint": [value: WorkspaceNodeTint];
  "update:title": [value: string];
}>();

const modalTitle = computed(() => (props.mode === "create" ? "Create node" : "Edit node"));
const modalDescription = computed(() =>
  props.mode === "create"
    ? "Set the title, summary, and visual identity for the new workspace node."
    : "Refine the node identity and choose which block summaries appear on the dashboard card.",
);
const selectedBlockKeys = computed(
  () => new Set(props.featuredBlocks.map((entry) => `${entry.tabId}:${entry.blockId}`)),
);
const selectedCount = computed(() => props.featuredBlocks.length);
const selectionLimitReached = computed(
  () => selectedCount.value >= WORKSPACE_NODE_DASHBOARD_DETAIL_LIMIT,
);
const selectionBadgeLabel = computed(() => {
  if (props.availableBlocks.length === 0) {
    return "No blocks";
  }

  return `${selectedCount.value}/${WORKSPACE_NODE_DASHBOARD_DETAIL_LIMIT}`;
});
const groupedBlockOptions = computed(() => {
  const groups: Array<{
    tabId: string;
    tabTitle: string;
    options: WorkspaceNodeDashboardSelectableBlock[];
  }> = [];

  for (const option of props.availableBlocks) {
    const existingGroup = groups.find((entry) => entry.tabId === option.tabId);

    if (existingGroup) {
      existingGroup.options.push(option);
      continue;
    }

    groups.push({
      tabId: option.tabId,
      tabTitle: option.tabTitle,
      options: [option],
    });
  }

  return groups;
});
const submitLabel = computed(() => (props.mode === "create" ? "Create node" : "Save changes"));

function handleOpenChange(isOpen: boolean) {
  if (!isOpen) {
    emit("close");
  }
}

function isFeaturedBlockSelected(option: WorkspaceNodeDashboardSelectableBlock) {
  return selectedBlockKeys.value.has(`${option.tabId}:${option.blockId}`);
}

function toggleFeaturedBlock(option: WorkspaceNodeDashboardSelectableBlock) {
  const isSelected = isFeaturedBlockSelected(option);

  if (isSelected) {
    emit(
      "update:featured-blocks",
      props.featuredBlocks.filter(
        (entry) => !(entry.tabId === option.tabId && entry.blockId === option.blockId),
      ),
    );
    return;
  }

  if (selectionLimitReached.value) {
    return;
  }

  emit("update:featured-blocks", [
    ...props.featuredBlocks,
    {
      tabId: option.tabId,
      blockId: option.blockId,
    },
  ]);
}

function getTintOptionStyle(value: WorkspaceNodeTint) {
  return getWorkspaceNodeTintStyle(value);
}
</script>

<template>
  <UModal
    :open="props.open"
    :title="modalTitle"
    :description="modalDescription"
    :ui="{
      content: `rounded-[28px] overflow-hidden ${props.mode === 'create' ? 'sm:max-w-2xl' : 'sm:max-w-3xl'}`,
      body: 'space-y-5 p-5',
      footer: 'flex items-center justify-end gap-3 border-t border-muted/20 bg-elevated/20 p-4',
    }"
    @update:open="handleOpenChange"
  >
    <template #body>
      <template v-if="props.mode === 'create'">
        <div class="space-y-5">
          <UFormField label="Title" name="title" required>
            <UInput
              :model-value="props.title"
              placeholder="Strategy lane"
              autofocus
              @update:model-value="emit('update:title', $event ?? '')"
            />
          </UFormField>

          <UFormField label="Summary" name="content">
            <UTextarea
              :model-value="props.content"
              :rows="3"
              autoresize
              placeholder="Add a short summary for the canvas card."
              @update:model-value="emit('update:content', $event ?? '')"
            />
          </UFormField>

          <hr class="border-muted/20">

          <div>
            <p class="mb-2 text-sm font-semibold text-highlighted">Node Type</p>
            <div class="flex overflow-hidden rounded-full border border-muted/60 bg-elevated/40 p-0.5">
              <button
                type="button"
                class="rounded-full px-3 py-1 text-xs font-semibold transition"
                :class="
                  props.nodeType === 'standard'
                    ? 'bg-primary text-white shadow-sm'
                    : 'text-muted hover:text-highlighted'
                "
                @click="emit('update:node-type', 'standard')"
              >
                Standard
              </button>
              <button
                type="button"
                class="rounded-full px-3 py-1 text-xs font-semibold transition"
                :class="
                  props.nodeType === 'orchestrator'
                    ? 'bg-primary text-white shadow-sm'
                    : 'text-muted hover:text-highlighted'
                "
                @click="emit('update:node-type', 'orchestrator')"
              >
                Orchestrator
              </button>
            </div>
          </div>

          <hr class="border-muted/20">

          <div>
            <p class="mb-2 text-sm font-semibold text-highlighted">Tint</p>
            <div class="flex flex-wrap gap-2">
              <button
                v-for="option in workspaceNodeTintOptions"
                :key="option.value"
                type="button"
                class="node-tint-option relative flex size-9 items-center justify-center rounded-full border transition"
                :class="
                  props.tint === option.value
                    ? 'border-primary/60 bg-default shadow-sm'
                    : 'border-muted/60 bg-elevated/40 hover:border-muted hover:bg-elevated/70'
                "
                :style="getTintOptionStyle(option.value)"
                :aria-label="option.label"
                :title="option.label"
                @click="emit('update:tint', option.value)"
              >
                <span class="node-tint-swatch size-4 rounded-full border" />
                <UIcon
                  v-if="props.tint === option.value"
                  name="i-lucide-check"
                  class="absolute size-3.5 text-highlighted"
                />
                <span class="sr-only">{{ option.label }}</span>
              </button>
            </div>
          </div>
        </div>
      </template>

      <template v-else>
        <div class="grid gap-5 sm:grid-cols-[1fr_1.2fr]">
          <div class="space-y-5">
            <UFormField label="Title" name="title" required>
              <UInput
                :model-value="props.title"
                placeholder="Strategy lane"
                autofocus
                @update:model-value="emit('update:title', $event ?? '')"
              />
            </UFormField>

            <UFormField label="Summary" name="content">
              <UTextarea
                :model-value="props.content"
                :rows="3"
                autoresize
                placeholder="Add a short summary for the canvas card."
                @update:model-value="emit('update:content', $event ?? '')"
              />
            </UFormField>

            <hr class="border-muted/20">

            <div>
              <p class="mb-2 text-sm font-semibold text-highlighted">Node Type</p>
              <div class="flex overflow-hidden rounded-full border border-muted/60 bg-elevated/40 p-0.5">
                <button
                  type="button"
                  class="rounded-full px-3 py-1 text-xs font-semibold transition"
                  :class="
                    props.nodeType === 'standard'
                      ? 'bg-primary text-white shadow-sm'
                      : 'text-muted hover:text-highlighted'
                  "
                  @click="emit('update:node-type', 'standard')"
                >
                  Standard
                </button>
                <button
                  type="button"
                  class="rounded-full px-3 py-1 text-xs font-semibold transition"
                  :class="
                    props.nodeType === 'orchestrator'
                      ? 'bg-primary text-white shadow-sm'
                      : 'text-muted hover:text-highlighted'
                  "
                  @click="emit('update:node-type', 'orchestrator')"
                >
                  Orchestrator
                </button>
              </div>
            </div>

            <hr class="border-muted/20">

            <div>
              <p class="mb-2 text-sm font-semibold text-highlighted">Tint</p>
              <div class="flex flex-wrap gap-2">
                <button
                  v-for="option in workspaceNodeTintOptions"
                  :key="option.value"
                  type="button"
                  class="node-tint-option relative flex size-9 items-center justify-center rounded-full border transition"
                  :class="
                    props.tint === option.value
                      ? 'border-primary/60 bg-default shadow-sm'
                      : 'border-muted/60 bg-elevated/40 hover:border-muted hover:bg-elevated/70'
                  "
                  :style="getTintOptionStyle(option.value)"
                  :aria-label="option.label"
                  :title="option.label"
                  @click="emit('update:tint', option.value)"
                >
                  <span class="node-tint-swatch size-4 rounded-full border" />
                  <UIcon
                    v-if="props.tint === option.value"
                    name="i-lucide-check"
                    class="absolute size-3.5 text-highlighted"
                  />
                  <span class="sr-only">{{ option.label }}</span>
                </button>
              </div>
            </div>
          </div>

          <div class="rounded-2xl border border-muted/30 bg-elevated/20 p-4">
            <div class="flex items-center justify-between gap-2">
              <p class="text-sm font-semibold text-highlighted">Featured Block Details</p>
              <UBadge color="neutral" variant="soft" size="sm">
                {{ selectionBadgeLabel }}
              </UBadge>
            </div>

            <div class="mt-4">
              <UAlert
                v-if="groupedBlockOptions.length === 0"
                color="neutral"
                variant="soft"
                icon="i-lucide-blocks"
                title="No blocks available yet"
                description="Open the node, add blocks to one of its tabs, then choose the ones that should appear on the dashboard card."
              />

              <template v-else>
                <div class="max-h-[24rem] space-y-3 overflow-y-auto pr-1">
                  <section
                    v-for="group in groupedBlockOptions"
                    :key="group.tabId"
                  >
                    <p class="mb-2 text-[0.65rem] font-bold uppercase tracking-[0.18em] text-muted">
                      {{ group.tabTitle }}
                    </p>

                    <div class="grid gap-1.5">
                      <button
                        v-for="option in group.options"
                        :key="option.blockId"
                        type="button"
                        class="flex items-center gap-2.5 rounded-xl border px-3 py-2 text-left transition"
                        :class="
                          isFeaturedBlockSelected(option)
                            ? 'border-primary/40 bg-primary/10'
                            : selectionLimitReached
                              ? 'border-muted/40 bg-elevated/20 opacity-60'
                              : 'border-muted/60 bg-default/80 hover:border-primary/30 hover:bg-default'
                        "
                        :disabled="selectionLimitReached && !isFeaturedBlockSelected(option)"
                        @click="toggleFeaturedBlock(option)"
                      >
                        <UIcon
                          :name="getWorkspaceBlockRegistryEntry(option.blockType).icon"
                          class="size-4 shrink-0"
                          :class="isFeaturedBlockSelected(option) ? 'text-primary' : 'text-muted'"
                        />
                        <span class="min-w-0 flex-1 truncate text-sm font-medium text-highlighted">
                          {{ option.blockTitle }}
                        </span>
                        <UIcon
                          v-if="isFeaturedBlockSelected(option)"
                          name="i-lucide-check"
                          class="size-4 shrink-0 text-primary"
                        />
                      </button>
                    </div>
                  </section>
                </div>
              </template>
            </div>
          </div>
        </div>
      </template>
    </template>

    <template #footer>
      <UButton color="neutral" variant="ghost" @click="emit('close')">Cancel</UButton>
      <UButton :disabled="!props.valid" icon="i-lucide-save" @click="emit('submit')">
        {{ submitLabel }}
      </UButton>
    </template>
  </UModal>
</template>

<style scoped>
.node-tint-option {
  --workspace-node-rgb: 148 163 184;
}

.node-tint-swatch {
  background-color: rgb(var(--workspace-node-rgb) / 0.35);
  border-color: rgb(var(--workspace-node-rgb) / 0.45);
  box-shadow: 0 0 0 6px rgb(var(--workspace-node-rgb) / 0.12);
}
</style>

// apps/web-start/src/components/workspace/workspace-editor-modal.tsx
import { useCallback, useMemo } from "react";
import {
  WORKSPACE_NODE_DASHBOARD_DETAIL_LIMIT,
  type WorkspaceNodeDashboardFeaturedBlock,
  type WorkspaceNodeDashboardSelectableBlock,
  type WorkspaceNodeTint,
  type WorkspaceNodeType,
} from "@brainiac/workspace";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

type WorkspaceEditorModalProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  mode: "create" | "edit";
  title: string;
  onTitleChange: (value: string) => void;
  content: string;
  onContentChange: (value: string) => void;
  nodeType: WorkspaceNodeType;
  onNodeTypeChange: (value: WorkspaceNodeType) => void;
  tint: WorkspaceNodeTint;
  onTintChange: (value: WorkspaceNodeTint) => void;
  featuredBlocks: WorkspaceNodeDashboardFeaturedBlock[];
  onFeaturedBlocksChange: (blocks: WorkspaceNodeDashboardFeaturedBlock[]) => void;
  availableBlocks: WorkspaceNodeDashboardSelectableBlock[];
  valid: boolean;
  onSubmit: () => void;
};

const TINT_OPTIONS: WorkspaceNodeTint[] = [
  "neutral",
  "emerald",
  "sky",
  "amber",
  "rose",
  "indigo",
];

const TINT_LABELS: Record<WorkspaceNodeTint, string> = {
  neutral: "Neutral",
  emerald: "Emerald",
  sky: "Sky",
  amber: "Amber",
  rose: "Rose",
  indigo: "Indigo",
};

const TINT_COLORS: Record<WorkspaceNodeTint, string> = {
  neutral: "bg-zinc-200",
  emerald: "bg-emerald-200",
  sky: "bg-sky-200",
  amber: "bg-amber-200",
  rose: "bg-rose-200",
  indigo: "bg-indigo-200",
};

export function WorkspaceEditorModal({
  open,
  onOpenChange,
  mode,
  title,
  onTitleChange,
  content,
  onContentChange,
  nodeType,
  onNodeTypeChange,
  tint,
  onTintChange,
  featuredBlocks,
  onFeaturedBlocksChange,
  availableBlocks,
  valid,
  onSubmit,
}: WorkspaceEditorModalProps) {
  const modalTitle = mode === "create" ? "Create node" : "Edit node";
  const modalDescription =
    mode === "create"
      ? "Set the node title, summary, and board identity before it lands on the workspace."
      : "Refine the node identity and choose which block summaries appear on the dashboard card.";

  const draftTitle =
    title.trim().length > 0
      ? title.trim()
      : mode === "create"
        ? "Untitled draft"
        : "Untitled node";

  const draftSummary =
    content.trim().length > 0
      ? content.trim()
      : "No summary yet. Add a short description for the workspace card.";

  const selectedBlockKeys = useMemo(
    () => new Set(featuredBlocks.map((entry) => `${entry.tabId}:${entry.blockId}`)),
    [featuredBlocks],
  );

  const selectedCount = featuredBlocks.length;
  const selectionLimitReached = selectedCount >= WORKSPACE_NODE_DASHBOARD_DETAIL_LIMIT;

  const selectionBadgeLabel =
    mode === "create"
      ? "Unlocks after creation"
      : availableBlocks.length === 0
        ? "No blocks yet"
        : `${selectedCount}/${WORKSPACE_NODE_DASHBOARD_DETAIL_LIMIT} selected`;

  const groupedBlockOptions = useMemo(() => {
    const groups: Array<{
      tabId: string;
      tabTitle: string;
      options: WorkspaceNodeDashboardSelectableBlock[];
    }> = [];

    for (const option of availableBlocks) {
      const existingGroup = groups.find((entry) => entry.tabId === option.tabId);

      if (existingGroup) {
        existingGroup.options.push(option);
        continue;
      }

      groups.push({
        tabId: option.tabId,
        tabTitle: option.tabTitle,
        options: [option],
      });
    }

    return groups;
  }, [availableBlocks]);

  const submitLabel = mode === "create" ? "Create node" : "Save changes";

  const isFeaturedBlockSelected = useCallback(
    (option: WorkspaceNodeDashboardSelectableBlock) => {
      return selectedBlockKeys.has(`${option.tabId}:${option.blockId}`);
    },
    [selectedBlockKeys],
  );

  const toggleFeaturedBlock = useCallback(
    (option: WorkspaceNodeDashboardSelectableBlock) => {
      const isSelected = isFeaturedBlockSelected(option);

      if (isSelected) {
        onFeaturedBlocksChange(
          featuredBlocks.filter(
            (entry) => !(entry.tabId === option.tabId && entry.blockId === option.blockId),
          ),
        );
        return;
      }

      if (selectionLimitReached) {
        return;
      }

      onFeaturedBlocksChange([
        ...featuredBlocks,
        {
          tabId: option.tabId,
          blockId: option.blockId,
        },
      ]);
    },
    [featuredBlocks, isFeaturedBlockSelected, onFeaturedBlocksChange, selectionLimitReached],
  );

  const nodeTypeDescription =
    nodeType === "orchestrator"
      ? "Can connect to standard nodes and coordinate work across the workspace."
      : "A regular workspace node with no graph links or orchestration layer.";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{modalTitle}</DialogTitle>
          <DialogDescription>{modalDescription}</DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {/* Title */}
          <div className="space-y-2">
            <Label htmlFor="node-title">Title</Label>
            <Input
              id="node-title"
              placeholder="Enter node title..."
              value={title}
              onChange={(e) => onTitleChange(e.target.value)}
              maxLength={120}
            />
            <div className="text-xs text-muted-foreground">
              Preview: <span className="font-medium">{draftTitle}</span>
            </div>
          </div>

          {/* Content */}
          <div className="space-y-2">
            <Label htmlFor="node-content">Summary</Label>
            <Textarea
              id="node-content"
              placeholder="Enter a brief description for the workspace card..."
              value={content}
              onChange={(e) => onContentChange(e.target.value)}
              maxLength={500}
              rows={4}
            />
            <div className="text-xs text-muted-foreground">
              Preview: <span className="font-medium">{draftSummary}</span>
            </div>
          </div>

          {/* Node Type */}
          <div className="space-y-2">
            <Label>Node Type</Label>
            <Select value={nodeType} onValueChange={(value) => onNodeTypeChange(value as WorkspaceNodeType)}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="standard">Standard</SelectItem>
                <SelectItem value="orchestrator">Orchestrator</SelectItem>
              </SelectContent>
            </Select>
            <div className="text-sm text-muted-foreground">{nodeTypeDescription}</div>
          </div>

          {/* Tint */}
          <div className="space-y-2">
            <Label>Color</Label>
            <div className="grid grid-cols-6 gap-2">
              {TINT_OPTIONS.map((option) => (
                <button
                  key={option}
                  onClick={() => onTintChange(option)}
                  className={`p-3 rounded-lg border-2 transition-all ${
                    tint === option ? "border-foreground" : "border-transparent hover:border-muted-foreground"
                  } ${TINT_COLORS[option]}`}
                  title={TINT_LABELS[option]}
                />
              ))}
            </div>
          </div>

          <Separator />

          {/* Featured Blocks Selection (only in edit mode) */}
          {mode === "edit" && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <Label>Featured Blocks</Label>
                <Badge variant="outline">{selectionBadgeLabel}</Badge>
              </div>

              {availableBlocks.length === 0 ? (
                <div className="text-sm text-muted-foreground italic">
                  No blocks available yet. Create some blocks in tabs first.
                </div>
              ) : (
                <div className="space-y-3">
                  {groupedBlockOptions.map((group) => (
                    <div key={group.tabId} className="space-y-2">
                      <div className="text-sm font-medium text-muted-foreground">
                        Tab: {group.tabTitle}
                      </div>
                      <div className="grid grid-cols-2 gap-2">
                        {group.options.map((option) => (
                          <div key={`${option.tabId}:${option.blockId}`} className="flex items-center space-x-2">
                            <Checkbox
                              id={`block-${option.tabId}-${option.blockId}`}
                              checked={isFeaturedBlockSelected(option)}
                              onCheckedChange={() => toggleFeaturedBlock(option)}
                              disabled={selectionLimitReached && !isFeaturedBlockSelected(option)}
                            />
                            <label
                              htmlFor={`block-${option.tabId}-${option.blockId}`}
                              className="text-sm cursor-pointer flex-1"
                            >
                              {option.blockTitle}
                            </label>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={onSubmit} disabled={!valid}>
            {submitLabel}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
