// apps/web/app/components/agency/AgencyClientsSurface.vue
<script setup lang="ts">
/**
 * Agency Clients — master/detail.
 *
 * Left rail: list of clients with project count + this-week hours per client.
 * Right pane: selected client detail — rename, project list (with hue dots,
 * inline create), and aspirational sections (contact, archive) that teach the
 * eventual shape without faking data.
 *
 * Why master/detail: agencies live in clients; switching between them is the
 * dominant motion. A two-column layout makes that motion one click instead of
 * a tab round-trip.
 */
import { useQuery } from "@tanstack/vue-query";

import { formatDuration } from "~/utils/format-duration";
import { projectHueStyle } from "~/utils/project-palette";
import { useAgencyOpsStore } from "~/stores/agency-ops";
const props = defineProps<{
  teamId: string;
}>();

const orpc = useOrpc();
const agencyOps = useAgencyOpsStore();

const teamId = computed(() => props.teamId);

const filterTerm = ref("");
const selectedClientId = ref("");
const renameDraft = ref("");
const renameOpen = ref(false);
const newClientOpen = ref(false);
const newClientName = ref("");
const newProjectName = ref("");

// Contact form state
const contactName = ref("");
const contactEmail = ref("");
const contactPhone = ref("");
const contactDirty = ref(false);

const clientsQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.clients.list.queryOptions({ input: { teamId: teamId.value } }),
    enabled: Boolean(teamId.value),
  })),
);
const projectsQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.projects.list.queryOptions({ input: { teamId: teamId.value } }),
    enabled: Boolean(teamId.value),
  })),
);
const entriesQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.timeEntries.listMine.queryOptions({
      input: { teamId: teamId.value, page: 1, pageSize: 100 },
    }),
    enabled: Boolean(teamId.value),
  })),
);
const contactQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.contacts.get.queryOptions({
      input: { teamId: teamId.value, clientId: selectedClientId.value },
    }),
    enabled: Boolean(teamId.value) && Boolean(selectedClientId.value),
  })),
);

// Register queries with the store so optimistic patches reach this component.
const clientsQueryKey = computed(
  () => orpc.agencyOps.clients.list.queryOptions({ input: { teamId: teamId.value } }).queryKey,
);
const projectsQueryKey = computed(
  () => orpc.agencyOps.projects.list.queryOptions({ input: { teamId: teamId.value } }).queryKey,
);

watch(
  clientsQueryKey,
  (next, prev) => {
    if (prev) agencyOps.unregisterClientsQuery(prev);
    if (teamId.value) agencyOps.registerClientsQuery({ queryKey: next, teamId: teamId.value });
  },
  { immediate: true },
);

watch(
  projectsQueryKey,
  (next, prev) => {
    if (prev) agencyOps.unregisterProjectsQuery(prev);
    if (teamId.value) agencyOps.registerProjectsQuery({ queryKey: next, teamId: teamId.value });
  },
  { immediate: true },
);

onUnmounted(() => {
  agencyOps.unregisterClientsQuery(clientsQueryKey.value);
  agencyOps.unregisterProjectsQuery(projectsQueryKey.value);
});

const clients = computed(() => clientsQuery.data.value?.items ?? []);
const projects = computed(() => projectsQuery.data.value?.items ?? []);
const entries = computed(() => entriesQuery.data.value?.items ?? []);

function getWeekStartUtc(): Date {
  const now = new Date();
  const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const day = date.getUTCDay();
  const diff = (day + 6) % 7;
  date.setUTCDate(date.getUTCDate() - diff);
  return date;
}

const weekHoursByClient = computed(() => {
  const weekStartMs = getWeekStartUtc().getTime();
  const totals = new Map<string, number>();
  for (const entry of entries.value) {
    if (new Date(entry.startedAt).getTime() < weekStartMs) continue;
    totals.set(entry.clientId, (totals.get(entry.clientId) ?? 0) + entry.durationSeconds);
  }
  return totals;
});

const projectsByClient = computed(() => {
  const map = new Map<string, typeof projects.value>();
  for (const project of projects.value) {
    const list = map.get(project.clientId) ?? [];
    list.push(project);
    map.set(project.clientId, list);
  }
  return map;
});

const filteredClients = computed(() => {
  const term = filterTerm.value.trim().toLowerCase();
  if (!term) return clients.value;
  return clients.value.filter((client) => client.name.toLowerCase().includes(term));
});

// Auto-select first client when list resolves.
watch(
  filteredClients,
  (next) => {
    if (next.length === 0) {
      selectedClientId.value = "";
      return;
    }
    if (!next.some((client) => client.id === selectedClientId.value)) {
      selectedClientId.value = next[0]!.id;
    }
  },
  { immediate: true },
);

const selectedClient = computed(
  () => clients.value.find((client) => client.id === selectedClientId.value) ?? null,
);
const selectedClientProjects = computed(
  () => projectsByClient.value.get(selectedClientId.value) ?? [],
);

// --- Mutations (via store for optimistic updates) -----------------------

async function createClient() {
  const name = newClientName.value.trim();
  if (!name || !teamId.value) return;
  newClientName.value = "";
  newClientOpen.value = false;
  await agencyOps.createClient(
    { teamId: teamId.value, name },
    {
      onSuccess: (clientId) => {
        selectedClientId.value = clientId;
      },
    },
  );
}

async function renameClient() {
  if (!selectedClient.value || !teamId.value) return;
  const name = renameDraft.value.trim();
  if (!name || name === selectedClient.value.name) {
    renameOpen.value = false;
    return;
  }
  renameOpen.value = false;
  await agencyOps.updateClient({
    teamId: teamId.value,
    clientId: selectedClient.value.id,
    name,
  });
}

async function createProject() {
  const name = newProjectName.value.trim();
  if (!name || !teamId.value || !selectedClient.value) return;
  newProjectName.value = "";
  await agencyOps.createProject({
    teamId: teamId.value,
    clientId: selectedClient.value.id,
    clientName: selectedClient.value.name,
    name,
  });
}

watch(renameOpen, (open) => {
  if (open && selectedClient.value) {
    renameDraft.value = selectedClient.value.name;
  }
});

const isLoading = computed(() => clientsQuery.isPending.value || projectsQuery.isPending.value);

// Populate contact form fields whenever the selected client changes.
watch(
  () => contactQuery.data.value,
  (contact) => {
    if (contact) {
      contactName.value = contact.name;
      contactEmail.value = contact.email;
      contactPhone.value = contact.phone;
    } else {
      contactName.value = "";
      contactEmail.value = "";
      contactPhone.value = "";
    }
    contactDirty.value = false;
  },
  { immediate: true },
);

// Reset dirty flag when switching clients.
watch(selectedClientId, () => {
  contactDirty.value = false;
});

async function saveContact() {
  if (!teamId.value || !selectedClientId.value) return;
  await agencyOps.upsertContact(
    {
      teamId: teamId.value,
      clientId: selectedClientId.value,
      name: contactName.value.trim(),
      email: contactEmail.value.trim(),
      phone: contactPhone.value.trim(),
    },
    {
      onSuccess: () => {
        contactDirty.value = false;
      },
    },
  );
}

async function archiveClient() {
  if (!selectedClient.value || !teamId.value) return;
  await agencyOps.archiveClient({
    teamId: teamId.value,
    clientId: selectedClient.value.id,
    clientName: selectedClient.value.name,
  });
  selectedClientId.value = "";
}
</script>

<template>
  <div class="agency-clients">
    <!-- Loading -->
    <div v-if="isLoading" class="grid gap-4 lg:grid-cols-[18rem,1fr]">
      <div class="space-y-2">
        <div v-for="i in 5" :key="i" class="h-12 animate-pulse rounded-2xl bg-elevated/60" />
      </div>
      <div class="h-64 animate-pulse rounded-2xl bg-elevated/60" />
    </div>

    <!-- Empty -->
    <div
      v-else-if="clients.length === 0"
      class="rounded-2xl border border-dashed border-default bg-muted/20 p-10 text-center"
    >
      <UIcon name="i-lucide-building-2" class="mx-auto size-7 text-muted" />
      <p class="mt-4 text-sm font-bold text-highlighted">No clients yet.</p>
      <p class="mt-1 text-xs text-muted">
        Add your first client to start grouping projects and time.
      </p>
      <UPopover v-model:open="newClientOpen" :content="{ align: 'center' }">
        <UButton
          label="Add client"
          color="primary"
          variant="soft"
          size="xs"
          icon="i-lucide-plus"
          class="mt-4"
        />
        <template #content>
          <form class="w-72 space-y-2 p-3" @submit.prevent="createClient">
            <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">New client</p>
            <UInput v-model="newClientName" placeholder="Client name" size="sm" autofocus />
            <UButton
              type="submit"
              label="Create"
              color="primary"
              size="xs"
              block
              :loading="agencyOps.isClientMutationPending"
              :disabled="!newClientName.trim()"
            />
          </form>
        </template>
      </UPopover>
    </div>

    <div v-else class="grid gap-4 lg:grid-cols-[18rem,1fr]">
      <!-- Master: client list -->
      <aside class="space-y-3">
        <div class="flex items-center gap-2">
          <UInput
            v-model="filterTerm"
            icon="i-lucide-search"
            placeholder="Filter clients"
            size="sm"
            class="flex-1"
          />
          <UPopover v-model:open="newClientOpen" :content="{ align: 'end' }">
            <UButton
              icon="i-lucide-plus"
              color="primary"
              size="xs"
              square
              aria-label="New client"
            />
            <template #content>
              <form class="w-72 space-y-2 p-3" @submit.prevent="createClient">
                <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">
                  New client
                </p>
                <UInput v-model="newClientName" placeholder="Client name" size="sm" autofocus />
                <UButton
                  type="submit"
                  label="Create"
                  color="primary"
                  size="xs"
                  block
                  :loading="agencyOps.isClientMutationPending"
                  :disabled="!newClientName.trim()"
                />
              </form>
            </template>
          </UPopover>
        </div>

        <ul class="space-y-1">
          <li v-for="client in filteredClients" :key="client.id">
            <button
              type="button"
              class="agency-clients__row group flex w-full items-center justify-between gap-2 rounded-xl border border-transparent px-3 py-2.5 text-left transition-colors"
              :class="
                client.id === selectedClientId
                  ? 'border-default bg-elevated'
                  : 'hover:bg-elevated/60'
              "
              @click="selectedClientId = client.id"
            >
              <div class="min-w-0">
                <p class="truncate text-xs font-bold text-highlighted">{{ client.name }}</p>
                <p class="text-[11px] text-muted">
                  {{ projectsByClient.get(client.id)?.length ?? 0 }} projects
                </p>
              </div>
              <span class="font-mono text-[11px] tabular-nums text-muted">
                {{ formatDuration(weekHoursByClient.get(client.id) ?? 0, "short") }}
              </span>
            </button>
          </li>
        </ul>

        <p v-if="filteredClients.length === 0" class="px-3 py-4 text-center text-xs text-muted">
          No matches.
        </p>
      </aside>

      <!-- Detail -->
      <section v-if="selectedClient" class="space-y-4">
        <div
          class="flex flex-wrap items-baseline justify-between gap-3 rounded-2xl border border-default bg-default p-5"
        >
          <div class="min-w-0">
            <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Client</p>
            <h2 class="mt-1 truncate text-lg font-bold text-highlighted">
              {{ selectedClient.name }}
            </h2>
            <p class="mt-1 font-mono text-[11px] tabular-nums text-muted">
              {{ formatDuration(weekHoursByClient.get(selectedClient.id) ?? 0, "short") }} this week
              · {{ selectedClientProjects.length }} projects
            </p>
          </div>
          <div class="flex items-center gap-2">
            <UPopover v-model:open="renameOpen" :content="{ align: 'end' }">
              <UButton label="Rename" color="neutral" variant="ghost" size="xs" />
              <template #content>
                <form class="w-72 space-y-2 p-3" @submit.prevent="renameClient">
                  <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">
                    Rename client
                  </p>
                  <UInput v-model="renameDraft" size="sm" autofocus />
                  <UButton
                    type="submit"
                    label="Save"
                    color="primary"
                    size="xs"
                    block
                    :loading="agencyOps.isClientMutationPending"
                    :disabled="!renameDraft.trim()"
                  />
                </form>
              </template>
            </UPopover>
          </div>
        </div>

        <!-- Projects under this client -->
        <div class="rounded-2xl border border-default bg-default">
          <div class="flex items-center justify-between border-b border-default px-4 py-3">
            <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Projects</p>
          </div>

          <ul v-if="selectedClientProjects.length > 0">
            <li
              v-for="project in selectedClientProjects"
              :key="project.id"
              class="flex items-center gap-3 border-b border-default px-4 py-3 last:border-b-0"
            >
              <span
                class="agency-clients__dot inline-block size-2 shrink-0 rounded-full"
                aria-hidden="true"
                :style="projectHueStyle(project.id)"
              />
              <span class="flex-1 truncate text-xs font-bold text-highlighted">
                {{ project.name }}
              </span>
              <span class="text-[11px] text-dimmed">Active</span>
            </li>
          </ul>

          <div v-else class="px-4 py-6 text-center">
            <p class="text-xs text-muted">No projects yet for this client.</p>
          </div>

          <form
            class="flex items-center gap-2 border-t border-default px-4 py-3"
            @submit.prevent="createProject"
          >
            <UInput v-model="newProjectName" placeholder="Add a project" size="sm" class="flex-1" />
            <UButton
              type="submit"
              label="Add"
              color="primary"
              size="xs"
              :loading="agencyOps.isProjectMutationPending"
              :disabled="!newProjectName.trim()"
            />
          </form>
        </div>

        <!-- Primary contact + archive -->
        <div
          class="space-y-0 divide-y divide-default overflow-hidden rounded-2xl border border-default bg-default"
        >
          <!-- Primary contact -->
          <section class="px-5 py-4">
            <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">
              Primary contact
            </p>
            <div class="mt-3 grid gap-3 sm:grid-cols-3">
              <div>
                <label class="text-[11px] font-bold text-muted">Name</label>
                <UInput
                  v-model="contactName"
                  placeholder="Contact name"
                  size="sm"
                  class="mt-1"
                  @input="contactDirty = true"
                />
              </div>
              <div>
                <label class="text-[11px] font-bold text-muted">Email</label>
                <UInput
                  v-model="contactEmail"
                  type="email"
                  placeholder="contact@example.com"
                  size="sm"
                  class="mt-1"
                  @input="contactDirty = true"
                />
              </div>
              <div>
                <label class="text-[11px] font-bold text-muted">Phone</label>
                <UInput
                  v-model="contactPhone"
                  type="tel"
                  placeholder="+1 555 000 0000"
                  size="sm"
                  class="mt-1"
                  @input="contactDirty = true"
                />
              </div>
            </div>
            <div class="mt-3 flex items-center gap-3">
              <UButton
                label="Save contact"
                color="primary"
                size="xs"
                :loading="agencyOps.isContactMutationPending"
                :disabled="!contactDirty"
                @click="saveContact"
              />
            </div>
          </section>

          <!-- Archive -->
          <section class="flex flex-wrap items-center justify-between gap-3 px-5 py-4">
            <div class="min-w-0">
              <p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Archive</p>
              <p class="mt-1 text-xs text-muted">
                Archive {{ selectedClient?.name ?? "this client" }} to remove them from active
                filters and billing without losing their history.
              </p>
            </div>
            <UButton
              label="Archive client"
              color="neutral"
              variant="ghost"
              size="xs"
              icon="i-lucide-archive"
              :loading="agencyOps.isClientMutationPending"
              @click="archiveClient"
            />
          </section>
        </div>
      </section>
    </div>
  </div>
</template>

<style scoped>
.agency-clients__dot {
  background-color: var(--project-hue, var(--ui-color-primary-500));
}
:global(.dark) .agency-clients__dot {
  background-color: var(--project-hue-dark, var(--ui-color-primary-400));
}
</style>

// apps/web/src/features/clients/agency-clients-surface.tsx
import { AlertTriangle, Archive, Building2, Plus } from "lucide-react";
import { cn } from "@/lib/utils";
import { useEffect, useMemo, useState } from "react";

import { Button } from "@/ui/button";
import { Input } from "@/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/ui/popover";
import { Skeleton } from "@/ui/skeleton";
import { AgencyProjectCreateDialog } from "@/features/projects/agency-project-create-dialog";
import { AgencySearchHighlight } from "@/features/shared/agency-search-highlight";
import { useAgencyClientsActions } from "@/features/shared/agency-segment-filters";
import type { AgencyListFiltersApplied } from "@/features/shared/use-agency-list-filters";
import {
  agencyEmptyPanelClass,
  agencyErrorPanelClass,
  agencyLabelClass,
} from "@/features/shared/agency-ui";
import { getErrorMessage } from "@/lib/utils/get-error-message";
import { getTaskGroupKey } from "@/features/task-management/agency-task-utils";
import { agencyListSearchMatches } from "@/features/shared/agency-list-search";
import {
  useAgencyClientsQuery,
  useAgencyContactQuery,
  useAgencyProjectTasksQuery,
  useAgencyProjectsQuery,
  useAgencyTimeEntriesQuery,
} from "@/features/shared/agency-queries";
import { formatDuration } from "@/lib/utils/format-duration";
import { formatRate, parseBillableRateCents } from "@/lib/utils/format-rate";
import { projectHueStyle } from "@/lib/utils/project-palette";
import {
  selectIsClientMutationPending,
  selectIsContactMutationPending,
  useAgencyOpsStore,
} from "@/features/shared/stores/agency-ops";

type AgencyClientsSurfaceProps = {
  teamId: string;
  filters: AgencyListFiltersApplied;
};

type AgencyClientCategory = "internal" | "external";

function ClientCategoryBadge({ category }: { category: AgencyClientCategory }) {
  const isInternal = category === "internal";
  return (
    <span
      className={cn(
        "inline-flex rounded-full px-2 py-1 text-[11px] font-bold capitalize",
        isInternal ? "border border-default bg-default text-muted" : "bg-elevated text-highlighted",
      )}
    >
      {isInternal ? "Internal" : "External"}
    </span>
  );
}

function getWeekStartUtc(): Date {
  const now = new Date();
  const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const day = date.getUTCDay();
  const diff = (day + 6) % 7;
  date.setUTCDate(date.getUTCDate() - diff);
  return date;
}

export function AgencyClientsSurface({ teamId, filters }: AgencyClientsSurfaceProps) {
  const { openNewClient } = useAgencyClientsActions();
  const agencyOps = useAgencyOpsStore();
  const isClientMutationPending = useAgencyOpsStore(selectIsClientMutationPending);
  const isContactMutationPending = useAgencyOpsStore(selectIsContactMutationPending);

  const [editClientId, setEditClientId] = useState("");
  const [createProjectClientId, setCreateProjectClientId] = useState("");
  const [contactClientId, setContactClientId] = useState("");
  const [editNameDraft, setEditNameDraft] = useState("");
  const [editCategoryDraft, setEditCategoryDraft] = useState<AgencyClientCategory>("external");
  const [editBillableRateDraft, setEditBillableRateDraft] = useState("");
  const [contactName, setContactName] = useState("");
  const [contactEmail, setContactEmail] = useState("");
  const [contactPhone, setContactPhone] = useState("");
  const [contactDirty, setContactDirty] = useState(false);

  const clientsQuery = useAgencyClientsQuery(teamId, { archiveFilter: filters.archiveFilter });
  const projectsQuery = useAgencyProjectsQuery(teamId);
  const entriesQuery = useAgencyTimeEntriesQuery(teamId, 1, 100);
  const tasksQuery = useAgencyProjectTasksQuery(teamId, {
    search: filters.filterTerm.trim() || undefined,
    pageSize: 100,
  });
  const contactQuery = useAgencyContactQuery(teamId, contactClientId);

  const clients = clientsQuery.data?.items ?? [];
  const projects = projectsQuery.data?.items ?? [];
  const entries = entriesQuery.data?.items ?? [];
  const tasks = tasksQuery.data?.items ?? [];

  const weekHoursByClient = useMemo(() => {
    const weekStartMs = getWeekStartUtc().getTime();
    const totals = new Map<string, number>();
    for (const entry of entries) {
      if (new Date(entry.startedAt).getTime() < weekStartMs) continue;
      totals.set(entry.clientId, (totals.get(entry.clientId) ?? 0) + entry.durationSeconds);
    }
    return totals;
  }, [entries]);

  const projectsByClient = useMemo(() => {
    const map = new Map<string, typeof projects>();
    for (const project of projects) {
      const list = map.get(project.clientId) ?? [];
      list.push(project);
      map.set(project.clientId, list);
    }
    return map;
  }, [projects]);

  const filteredClients = useMemo(() => {
    const term = filters.filterTerm;
    const { peopleSet, clientsSet, projectsSet, tasksSet } = filters;
    return clients.filter((client) => {
      const clientProjects = projects.filter((project) => project.clientId === client.id);
      if (
        term &&
        !agencyListSearchMatches(
          term,
          client.name,
          ...clientProjects.map((project) => project.name),
        )
      ) {
        return false;
      }
      if (clientsSet.size > 0 && !clientsSet.has(client.id)) return false;

      if (projectsSet.size > 0 && !clientProjects.some((project) => projectsSet.has(project.id))) {
        return false;
      }
      if (
        peopleSet.size > 0 &&
        !clientProjects.some((project) =>
          entries.some((entry) => entry.projectId === project.id && peopleSet.has(entry.userId)),
        )
      ) {
        return false;
      }
      if (
        tasksSet.size > 0 &&
        !clientProjects.some((project) =>
          tasks.some(
            (task) => task.projectId === project.id && tasksSet.has(getTaskGroupKey(task)),
          ),
        )
      ) {
        return false;
      }
      return true;
    });
  }, [clients, entries, filters, projects, tasks]);

  const contactClient = clients.find((client) => client.id === contactClientId) ?? null;

  useEffect(() => {
    const contact = contactQuery.data;
    if (contact) {
      setContactName(contact.name);
      setContactEmail(contact.email);
      setContactPhone(contact.phone);
    } else {
      setContactName("");
      setContactEmail("");
      setContactPhone("");
    }
    setContactDirty(false);
  }, [contactQuery.data]);

  useEffect(() => {
    setContactDirty(false);
  }, [contactClientId]);

  useEffect(() => {
    const client = clients.find((entry) => entry.id === editClientId);
    if (client) {
      setEditNameDraft(client.name);
      setEditCategoryDraft(client.category);
      setEditBillableRateDraft(
        client.billableRateCents === null ? "" : String(client.billableRateCents / 100),
      );
    }
  }, [clients, editClientId]);

  async function saveClientEdits(clientId: string) {
    const client = clients.find((entry) => entry.id === clientId);
    if (!client || !teamId) return;

    const name = editNameDraft.trim();
    if (!name) return;

    const billableRateCents = parseBillableRateCents(editBillableRateDraft);
    if (editBillableRateDraft.trim() && billableRateCents === null) return;

    const patch: {
      teamId: string;
      clientId: string;
      name?: string;
      category?: AgencyClientCategory;
      billableRateCents?: number | null;
    } = { teamId, clientId };

    if (name !== client.name) {
      patch.name = name;
    }
    if (editCategoryDraft !== client.category) {
      patch.category = editCategoryDraft;
    }
    if (billableRateCents !== client.billableRateCents) {
      patch.billableRateCents = billableRateCents;
    }

    if (Object.keys(patch).length === 2) {
      setEditClientId("");
      return;
    }

    setEditClientId("");
    await agencyOps.updateClient(patch);
  }

  async function saveContact() {
    if (!teamId || !contactClientId) return;
    await agencyOps.upsertContact(
      {
        teamId,
        clientId: contactClientId,
        name: contactName.trim(),
        email: contactEmail.trim(),
        phone: contactPhone.trim(),
      },
      { onSuccess: () => setContactDirty(false) },
    );
  }

  async function archiveClient(clientId: string) {
    const client = clients.find((entry) => entry.id === clientId);
    if (!client || !teamId) return;
    await agencyOps.archiveClient({
      teamId,
      clientId: client.id,
      clientName: client.name,
    });
  }

  const isLoading = clientsQuery.isPending || projectsQuery.isPending;
  const isError = clientsQuery.isError || projectsQuery.isError;

  return (
    <div className="agency-clients">
      {isLoading ? (
        <div className="overflow-hidden rounded-2xl border border-default bg-default">
          {[1, 2, 3, 4, 5, 6].map((rowIndex) => (
            <div key={rowIndex} className="border-b border-default px-4 py-4 last:border-b-0">
              <Skeleton className="h-4 w-full" />
            </div>
          ))}
        </div>
      ) : isError ? (
        <div className={agencyErrorPanelClass} role="alert">
          <AlertTriangle className="mx-auto size-5 text-error" />
          <p className="mt-3 text-sm font-bold text-highlighted">Couldn't load clients.</p>
          <p className="mt-1 text-xs text-muted">
            {getErrorMessage(clientsQuery.error ?? projectsQuery.error, "Try refreshing.")}
          </p>
          <Button
            variant="secondary"
            size="sm"
            className="mt-3"
            onClick={() => {
              void clientsQuery.refetch();
              void projectsQuery.refetch();
            }}
          >
            Retry
          </Button>
        </div>
      ) : clients.length === 0 ? (
        <div className={agencyEmptyPanelClass}>
          <Building2 className="mx-auto size-6 text-muted" />
          <p className="mt-3 text-sm font-bold text-highlighted">No clients yet.</p>
          <p className="mt-1 text-xs text-muted">
            Add your first client to start grouping projects and time.
          </p>
          <Button variant="secondary" size="sm" className="mt-4" onClick={openNewClient}>
            <Plus />
            New client
          </Button>
        </div>
      ) : filteredClients.length === 0 ? (
        <div className="rounded-2xl border border-default bg-default p-8 text-center">
          <p className="text-sm font-bold text-highlighted">No clients match.</p>
          <p className="mt-1 text-xs text-muted">Try a different search.</p>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-2xl border border-default bg-default">
          <table className="w-full min-w-[68rem] text-xs">
            <thead className="border-b border-default bg-muted">
              <tr className={agencyLabelClass}>
                <th scope="col" className="px-4 py-2.5 font-bold">
                  Client
                </th>
                <th scope="col" className="px-3 py-2.5 font-bold">
                  Category
                </th>
                <th scope="col" className="px-3 py-2.5 font-bold">
                  Billable / hour
                </th>
                <th scope="col" className="px-3 py-2.5 font-bold">
                  Projects
                </th>
                <th scope="col" className="px-3 py-2.5 text-right font-bold">
                  Hours · this week
                </th>
                <th scope="col" className="px-3 py-2.5 font-bold">
                  Contact
                </th>
                <th scope="col" className="px-4 py-2.5 text-right font-bold">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody>
              {filteredClients.map((client) => {
                const clientProjects = projectsByClient.get(client.id) ?? [];
                const searchTerm = filters.filterTerm;
                const visibleProjects =
                  searchTerm.trim() === ""
                    ? clientProjects.slice(0, 3)
                    : [...clientProjects]
                        .sort(
                          (left, right) =>
                            Number(agencyListSearchMatches(searchTerm, right.name)) -
                            Number(agencyListSearchMatches(searchTerm, left.name)),
                        )
                        .slice(0, 3);

                return (
                  <tr
                    key={client.id}
                    className="border-b border-default transition-colors last:border-b-0 hover:bg-elevated/40"
                  >
                    <td className="px-4 py-3">
                      <span className="truncate font-bold text-highlighted">
                        <AgencySearchHighlight text={client.name} query={filters.filterTerm} />
                      </span>
                    </td>
                    <td className="px-3 py-3">
                      <ClientCategoryBadge category={client.category} />
                    </td>
                    <td className="px-3 py-3">
                      <span
                        className={cn(
                          "font-mono font-bold tabular-nums",
                          client.billableRateCents === null ? "text-dimmed" : "text-highlighted",
                        )}
                      >
                        {formatRate(client.billableRateCents, client.currency, { perHour: true })}
                      </span>
                    </td>
                    <td className="px-3 py-3">
                      {clientProjects.length > 0 ? (
                        <div className="flex min-w-0 flex-wrap items-center gap-1.5">
                          {visibleProjects.map((project) => (
                            <span
                              key={project.id}
                              className="inline-flex max-w-36 items-center gap-1.5 rounded-full bg-elevated px-2 py-1 text-[11px] font-bold text-muted"
                            >
                              <span
                                className="inline-block size-1.5 shrink-0 rounded-full"
                                aria-hidden="true"
                                style={projectHueStyle(project.id)}
                              />
                              <span className="truncate">
                                <AgencySearchHighlight
                                  text={project.name}
                                  query={filters.filterTerm}
                                />
                              </span>
                            </span>
                          ))}
                          {clientProjects.length > visibleProjects.length ? (
                            <span className="text-[11px] text-dimmed">
                              +{clientProjects.length - visibleProjects.length} more
                            </span>
                          ) : null}
                        </div>
                      ) : (
                        <span className="text-dimmed">No projects</span>
                      )}
                    </td>
                    <td className="px-3 py-3 text-right">
                      <span
                        className={cn(
                          "font-mono font-bold tabular-nums",
                          (weekHoursByClient.get(client.id) ?? 0) > 0
                            ? "text-highlighted"
                            : "text-dimmed",
                        )}
                      >
                        {formatDuration(weekHoursByClient.get(client.id) ?? 0, "short")}
                      </span>
                    </td>
                    <td className="px-3 py-3 text-muted">
                      <Popover
                        open={contactClientId === client.id}
                        onOpenChange={(open) => setContactClientId(open ? client.id : "")}
                      >
                        <PopoverTrigger asChild>
                          <Button variant="ghost" size="sm">
                            Contact
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent align="start" className="w-80 space-y-3 p-3">
                          <form
                            onSubmit={(e) => {
                              e.preventDefault();
                              void saveContact();
                            }}
                          >
                            <p className="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">
                              {contactClient?.name ?? client.name}
                            </p>
                            <div className="mt-3 space-y-2">
                              <div>
                                <label className="text-[11px] font-bold text-muted">Name</label>
                                <Input
                                  value={contactName}
                                  onChange={(e) => {
                                    setContactName(e.target.value);
                                    setContactDirty(true);
                                  }}
                                  placeholder="Contact name"
                                  className="mt-1"
                                />
                              </div>
                              <div>
                                <label className="text-[11px] font-bold text-muted">Email</label>
                                <Input
                                  value={contactEmail}
                                  onChange={(e) => {
                                    setContactEmail(e.target.value);
                                    setContactDirty(true);
                                  }}
                                  type="email"
                                  placeholder="contact@example.com"
                                  className="mt-1"
                                />
                              </div>
                              <div>
                                <label className="text-[11px] font-bold text-muted">Phone</label>
                                <Input
                                  value={contactPhone}
                                  onChange={(e) => {
                                    setContactPhone(e.target.value);
                                    setContactDirty(true);
                                  }}
                                  type="tel"
                                  placeholder="+1 555 000 0000"
                                  className="mt-1"
                                />
                              </div>
                            </div>
                            <Button
                              type="submit"
                              size="sm"
                              className="mt-3 w-full"
                              disabled={
                                !contactDirty || contactQuery.isFetching || isContactMutationPending
                              }
                            >
                              Save contact
                            </Button>
                          </form>
                        </PopoverContent>
                      </Popover>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex justify-end gap-1.5">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => setCreateProjectClientId(client.id)}
                        >
                          <Plus />
                          Project
                        </Button>

                        <Popover
                          open={editClientId === client.id}
                          onOpenChange={(open) => setEditClientId(open ? client.id : "")}
                        >
                          <PopoverTrigger asChild>
                            <Button variant="ghost" size="sm">
                              Edit
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent align="end" className="w-72 space-y-2 p-3">
                            <form
                              onSubmit={(e) => {
                                e.preventDefault();
                                void saveClientEdits(client.id);
                              }}
                            >
                              <p className="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">
                                Edit client
                              </p>
                              <div className="mt-2 space-y-2">
                                <div>
                                  <label className="text-[11px] font-bold text-muted">Name</label>
                                  <Input
                                    value={editNameDraft}
                                    onChange={(e) => setEditNameDraft(e.target.value)}
                                    className="mt-1"
                                    autoFocus
                                  />
                                </div>
                                <div>
                                  <label className="text-[11px] font-bold text-muted">
                                    Category
                                  </label>
                                  <select
                                    value={editCategoryDraft}
                                    onChange={(e) =>
                                      setEditCategoryDraft(e.target.value as AgencyClientCategory)
                                    }
                                    className="mt-1 flex h-9 w-full rounded-md border border-default bg-default px-3 text-sm text-highlighted"
                                  >
                                    <option value="external">External</option>
                                    <option value="internal">Internal</option>
                                  </select>
                                </div>
                                <div>
                                  <label className="text-[11px] font-bold text-muted">
                                    Billable rate / hour
                                  </label>
                                  <Input
                                    value={editBillableRateDraft}
                                    onChange={(e) => setEditBillableRateDraft(e.target.value)}
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    placeholder="Leave blank if not set"
                                    className="mt-1"
                                  />
                                </div>
                              </div>
                              <Button
                                type="submit"
                                size="sm"
                                className="mt-2 w-full"
                                disabled={
                                  !editNameDraft.trim() ||
                                  isClientMutationPending ||
                                  Boolean(
                                    editBillableRateDraft.trim() &&
                                    parseBillableRateCents(editBillableRateDraft) === null,
                                  )
                                }
                              >
                                Save
                              </Button>
                            </form>
                          </PopoverContent>
                        </Popover>

                        <Button
                          variant="ghost"
                          size="sm"
                          disabled={isClientMutationPending}
                          onClick={() => void archiveClient(client.id)}
                        >
                          <Archive />
                          Archive
                        </Button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
      <AgencyProjectCreateDialog
        open={Boolean(createProjectClientId)}
        onOpenChange={(open) => {
          if (!open) setCreateProjectClientId("");
        }}
        teamId={teamId}
        clients={clients}
        lockClientId={createProjectClientId || undefined}
      />
    </div>
  );
}
