// apps/web/app/components/workspace/node/blocks/WorkspaceScorecardBlockEditor.vue
<script setup lang="ts">
import type { WorkspaceScorecardBlock } from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
    block: WorkspaceScorecardBlock;
    tabId: string;
}>();

const { addScorecardMetric, mutateScorecardMetric, removeScorecardMetric } =
    useWorkspaceNodeEditorContext();

const summary = computed(() => {
    const metricCount = props.block.metrics.length;
    const atTarget = props.block.metrics.filter(
        (metric) => metric.value >= metric.target,
    ).length;
    const avgProgress =
        metricCount === 0
            ? 0
            : Math.round(
                  props.block.metrics.reduce(
                      (sum, metric) =>
                          sum + getMetricProgress(metric.value, metric.target),
                      0,
                  ) / metricCount,
              );

    return {
        metricCount,
        atTarget,
        behindTarget: Math.max(metricCount - atTarget, 0),
        avgProgress,
    };
});

function toNumber(value: string | number | undefined, fallback = 0) {
    const numeric = Number(value);
    return Number.isFinite(numeric) ? numeric : fallback;
}

function getMetricProgress(value: number, target: number) {
    if (target === 0) {
        return value > 0 ? 100 : 0;
    }

    return Math.max(0, Math.min(100, Math.round((value / target) * 100)));
}

function getMetricStatus(value: number, target: number) {
    const progress = getMetricProgress(value, target);

    if (progress >= 100) {
        return {
            label: "At target",
            tone: "success" as const,
            textClass: "text-success",
            badgeColor: "success" as const,
            cardClass: "border-success/20 bg-success/5",
        };
    }

    if (progress >= 50) {
        return {
            label: "On track",
            tone: "warning" as const,
            textClass: "text-warning",
            badgeColor: "warning" as const,
            cardClass: "border-warning/20 bg-warning/5",
        };
    }

    return {
        label: "Behind",
        tone: "error" as const,
        textClass: "text-error",
        badgeColor: "error" as const,
        cardClass: "border-error/20 bg-error/5",
    };
}

function updateMetricLabel(
    metricId: string,
    value: string | number | undefined,
) {
    mutateScorecardMetric(props.tabId, props.block.id, metricId, (entry) => {
        entry.label = String(value ?? "").slice(0, 120);
    });
}

function updateMetricValue(
    metricId: string,
    value: string | number | undefined,
) {
    mutateScorecardMetric(props.tabId, props.block.id, metricId, (entry) => {
        entry.value = toNumber(value, 0);
    });
}

function updateMetricTarget(
    metricId: string,
    value: string | number | undefined,
) {
    mutateScorecardMetric(props.tabId, props.block.id, metricId, (entry) => {
        entry.target = toNumber(value, 100);
    });
}

function updateMetricUnit(
    metricId: string,
    value: string | number | undefined,
) {
    mutateScorecardMetric(props.tabId, props.block.id, metricId, (entry) => {
        entry.unit = String(value ?? "").slice(0, 24);
    });
}

function removeMetric(metricId: string) {
    removeScorecardMetric(props.tabId, props.block.id, metricId);
}
</script>

<template>
    <div class="space-y-8">
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div
                class="flex flex-col items-center justify-center rounded-3xl border border-primary/10 bg-primary/5 p-5 text-center"
            >
                <p
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                >
                    Total Metrics
                </p>
                <p
                    class="mt-1 text-2xl font-black tracking-tight text-primary sm:text-3xl"
                >
                    {{ summary.metricCount }}
                </p>
            </div>

            <div
                class="flex flex-col items-center justify-center rounded-3xl border border-success/10 bg-success/5 p-5 text-center"
            >
                <p
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                >
                    At Target
                </p>
                <p
                    class="mt-1 text-2xl font-black tracking-tight text-success sm:text-3xl"
                >
                    {{ summary.atTarget }}
                </p>
            </div>

            <div
                class="flex flex-col items-center justify-center rounded-3xl border border-error/10 bg-error/5 p-5 text-center"
            >
                <p
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                >
                    Needs Attention
                </p>
                <p
                    class="mt-1 text-2xl font-black tracking-tight text-error sm:text-3xl"
                >
                    {{ summary.behindTarget }}
                </p>
            </div>

            <div
                class="flex flex-col items-center justify-center rounded-3xl border border-warning/10 bg-warning/5 p-5 text-center"
            >
                <p
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                >
                    Avg Progress
                </p>
                <p
                    class="mt-1 text-2xl font-black tracking-tight text-warning sm:text-3xl"
                >
                    {{ summary.avgProgress }}%
                </p>
            </div>
        </div>

        <div class="space-y-4">
            <div class="flex items-center justify-between gap-3 px-2">
                <div>
                    <h3
                        class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                    >
                        Key Performance Indicators
                    </h3>
                    <p class="mt-1 text-sm text-muted">
                        Track the current value, target, and unit for each
                        metric in one place.
                    </p>
                </div>

                <UButton
                    color="primary"
                    variant="soft"
                    size="sm"
                    icon="i-lucide-plus"
                    class="rounded-full px-4"
                    aria-label="Add scorecard metric"
                    @click="addScorecardMetric(tabId, block.id)"
                >
                    Add Metric
                </UButton>
            </div>

            <div
                v-if="block.metrics.length > 0"
                class="grid gap-4 md:grid-cols-2"
            >
                <article
                    v-for="metric in block.metrics"
                    :key="metric.id"
                    class="rounded-3xl border p-5 transition-colors"
                    :class="
                        getMetricStatus(metric.value, metric.target).cardClass
                    "
                >
                    <div class="flex items-start justify-between gap-4">
                        <div class="min-w-0 flex-1 space-y-2">
                            <UInput
                                :model-value="metric.label"
                                variant="none"
                                placeholder="Metric title"
                                class="w-full"
                                :ui="{
                                    base: 'px-0 text-lg font-bold text-highlighted placeholder:text-muted/40',
                                }"
                                :aria-label="`Metric title for ${metric.label || 'scorecard metric'}`"
                                @update:model-value="
                                    updateMetricLabel(metric.id, $event)
                                "
                            />

                            <div class="flex flex-wrap items-center gap-2">
                                <UBadge
                                    :color="
                                        getMetricStatus(
                                            metric.value,
                                            metric.target,
                                        ).badgeColor
                                    "
                                    variant="soft"
                                    class="rounded-2xl"
                                >
                                    {{
                                        getMetricStatus(
                                            metric.value,
                                            metric.target,
                                        ).label
                                    }}
                                </UBadge>
                                <UBadge
                                    color="neutral"
                                    variant="soft"
                                    class="rounded-2xl"
                                >
                                    {{
                                        getMetricProgress(
                                            metric.value,
                                            metric.target,
                                        )
                                    }}% progress
                                </UBadge>
                            </div>
                        </div>

                        <UButton
                            color="neutral"
                            variant="ghost"
                            size="xs"
                            icon="i-lucide-trash-2"
                            class="rounded-xl hover:text-error"
                            :aria-label="`Remove ${metric.label || 'scorecard'} metric`"
                            @click="removeMetric(metric.id)"
                        />
                    </div>

                    <div
                        class="mt-6 flex flex-wrap items-end justify-between gap-4"
                    >
                        <div>
                            <p
                                class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                            >
                                Current vs Target
                            </p>
                            <div class="mt-2 flex items-end gap-2">
                                <span
                                    class="text-3xl font-black tracking-tight sm:text-4xl"
                                    :class="
                                        getMetricStatus(
                                            metric.value,
                                            metric.target,
                                        ).textClass
                                    "
                                >
                                    {{ metric.value }}
                                </span>
                                <span
                                    class="pb-1 text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                                >
                                    / {{ metric.target }}
                                    {{ metric.unit || "units" }}
                                </span>
                            </div>
                        </div>
                    </div>

                    <div class="mt-5 space-y-3">
                        <div
                            class="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.2em]"
                        >
                            <span class="text-muted/60">Progress</span>
                            <span
                                :class="
                                    getMetricStatus(metric.value, metric.target)
                                        .textClass
                                "
                            >
                                {{
                                    getMetricProgress(
                                        metric.value,
                                        metric.target,
                                    )
                                }}%
                            </span>
                        </div>

                        <UProgress
                            :model-value="
                                getMetricProgress(metric.value, metric.target)
                            "
                            size="sm"
                            class="rounded-full"
                        />
                    </div>

                    <div class="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3">
                        <div class="space-y-1">
                            <p
                                class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                            >
                                Current
                            </p>
                            <UInput
                                :model-value="String(metric.value)"
                                type="number"
                                size="sm"
                                class="rounded-xl"
                                :aria-label="`Current value for ${metric.label || 'scorecard metric'}`"
                                @update:model-value="
                                    updateMetricValue(metric.id, $event)
                                "
                            />
                        </div>

                        <div class="space-y-1">
                            <p
                                class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                            >
                                Target
                            </p>
                            <UInput
                                :model-value="String(metric.target)"
                                type="number"
                                size="sm"
                                class="rounded-xl"
                                :aria-label="`Target value for ${metric.label || 'scorecard metric'}`"
                                @update:model-value="
                                    updateMetricTarget(metric.id, $event)
                                "
                            />
                        </div>

                        <div class="space-y-1">
                            <p
                                class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                            >
                                Unit
                            </p>
                            <UInput
                                :model-value="metric.unit"
                                size="sm"
                                placeholder="%"
                                class="rounded-xl"
                                :aria-label="`Unit for ${metric.label || 'scorecard metric'}`"
                                @update:model-value="
                                    updateMetricUnit(metric.id, $event)
                                "
                            />
                        </div>
                    </div>
                </article>
            </div>

            <div
                v-else
                class="rounded-3xl border border-dashed border-muted/20 bg-elevated/5 py-12 text-center"
            >
                <div class="mb-4 flex items-center justify-center">
                    <UIcon
                        name="i-lucide-bar-chart-3"
                        class="size-8 text-muted/40"
                    />
                </div>
                <p
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                >
                    No metrics defined
                </p>
                <p class="mt-2 text-sm text-muted">
                    Add a metric to track performance against a target.
                </p>
                <UButton
                    color="primary"
                    variant="soft"
                    size="sm"
                    icon="i-lucide-plus"
                    class="mt-4 rounded-full px-4"
                    aria-label="Add first scorecard metric"
                    @click="addScorecardMetric(tabId, block.id)"
                >
                    Add Metric
                </UButton>
            </div>
        </div>
    </div>
</template>

// apps/web/src/features/workspace/node/blocks/workspace-scorecard-block-editor.tsx
import type { WorkspaceScorecardBlock } from "@brainiac/workspace";
import { BarChart3, Plus, Trash2 } from "lucide-react";
import { useMemo } from "react";

import type { WorkspaceBlockEditorProps } from "@/features/workspace/node/block-editor-props";
import { BlockProgressBar } from "@/features/workspace/node/blocks/shared/block-progress-bar";
import { useWorkspaceNodeEditorContext } from "@/features/workspace/node/context";
import { Badge } from "@/ui/badge";
import { Button } from "@/ui/button";
import { Input } from "@/ui/input";
import { cn } from "@/lib/utils";

function toNumber(value: string, fallback = 0) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : fallback;
}

function getMetricProgress(value: number, target: number) {
  if (target === 0) {
    return value > 0 ? 100 : 0;
  }
  return Math.max(0, Math.min(100, Math.round((value / target) * 100)));
}

function getMetricStatus(value: number, target: number) {
  const progress = getMetricProgress(value, target);

  if (progress >= 100) {
    return {
      label: "At target",
      textClass: "text-success",
      badgeVariant: "success" as const,
      cardClass: "border-success/20 bg-success/5",
    };
  }

  if (progress >= 50) {
    return {
      label: "On track",
      textClass: "text-warning",
      badgeVariant: "secondary" as const,
      cardClass: "border-warning/20 bg-warning/5",
    };
  }

  return {
    label: "Behind",
    textClass: "text-destructive",
    badgeVariant: "destructive" as const,
    cardClass: "border-destructive/20 bg-destructive/5",
  };
}

export function WorkspaceScorecardBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceScorecardBlock>) {
  const { addScorecardMetric, mutateScorecardMetric, removeScorecardMetric } =
    useWorkspaceNodeEditorContext();

  const summary = useMemo(() => {
    const metricCount = block.metrics.length;
    const atTarget = block.metrics.filter((metric) => metric.value >= metric.target).length;
    const avgProgress =
      metricCount === 0
        ? 0
        : Math.round(
            block.metrics.reduce(
              (sum, metric) => sum + getMetricProgress(metric.value, metric.target),
              0,
            ) / metricCount,
          );

    return {
      metricCount,
      atTarget,
      behindTarget: Math.max(metricCount - atTarget, 0),
      avgProgress,
    };
  }, [block.metrics]);

  return (
    <div className="space-y-8">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {[
          ["Total Metrics", summary.metricCount, "border-primary/10 bg-primary/5 text-primary"],
          ["At Target", summary.atTarget, "border-success/10 bg-success/5 text-success"],
          [
            "Needs Attention",
            summary.behindTarget,
            "border-destructive/10 bg-destructive/5 text-destructive",
          ],
          [
            "Avg Progress",
            `${summary.avgProgress}%`,
            "border-warning/10 bg-warning/5 text-warning",
          ],
        ].map(([label, value, className]) => (
          <div
            key={String(label)}
            className={cn(
              "flex flex-col items-center justify-center rounded-3xl border p-5 text-center",
              className,
            )}
          >
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
              {label}
            </p>
            <p className={cn("mt-1 text-2xl font-black tracking-tight sm:text-3xl")}>{value}</p>
          </div>
        ))}
      </div>

      <div className="space-y-4">
        <div className="flex items-center justify-between gap-3 px-2">
          <div>
            <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
              Key Performance Indicators
            </h3>
            <p className="mt-1 text-sm text-muted-foreground">
              Track the current value, target, and unit for each metric in one place.
            </p>
          </div>

          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="rounded-full px-4"
            aria-label="Add scorecard metric"
            onClick={() => addScorecardMetric(tabId, block.id)}
          >
            <Plus />
            Add Metric
          </Button>
        </div>

        {block.metrics.length > 0 ? (
          <div className="grid gap-4 md:grid-cols-2">
            {block.metrics.map((metric) => {
              const status = getMetricStatus(metric.value, metric.target);
              const progress = getMetricProgress(metric.value, metric.target);

              return (
                <article
                  key={metric.id}
                  className={cn("rounded-3xl border p-5 transition-colors", status.cardClass)}
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="min-w-0 flex-1 space-y-2">
                      <Input
                        value={metric.label}
                        placeholder="Metric title"
                        className="w-full border-0 bg-transparent px-0 text-lg font-bold shadow-none focus-visible:ring-0"
                        aria-label={`Metric title for ${metric.label || "scorecard metric"}`}
                        onChange={(event) =>
                          mutateScorecardMetric(tabId, block.id, metric.id, (entry) => {
                            entry.label = event.target.value.slice(0, 120);
                          })
                        }
                      />

                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant={status.badgeVariant} className="rounded-2xl">
                          {status.label}
                        </Badge>
                        <Badge variant="secondary" className="rounded-2xl">
                          {progress}% progress
                        </Badge>
                      </div>
                    </div>

                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="rounded-xl hover:text-destructive"
                      aria-label={`Remove ${metric.label || "scorecard"} metric`}
                      onClick={() => removeScorecardMetric(tabId, block.id, metric.id)}
                    >
                      <Trash2 />
                    </Button>
                  </div>

                  <div className="mt-6 flex flex-wrap items-end justify-between gap-4">
                    <div>
                      <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                        Current vs Target
                      </p>
                      <div className="mt-2 flex items-end gap-2">
                        <span
                          className={cn(
                            "text-3xl font-black tracking-tight sm:text-4xl",
                            status.textClass,
                          )}
                        >
                          {metric.value}
                        </span>
                        <span className="pb-1 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                          / {metric.target} {metric.unit || "units"}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="mt-5 space-y-3">
                    <div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.2em]">
                      <span className="text-muted-foreground/60">Progress</span>
                      <span className={status.textClass}>{progress}%</span>
                    </div>
                    <BlockProgressBar value={progress} max={100} />
                  </div>

                  <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-3">
                    {(
                      [
                        [
                          "Current",
                          String(metric.value),
                          "number",
                          (value: string) =>
                            mutateScorecardMetric(tabId, block.id, metric.id, (entry) => {
                              entry.value = toNumber(value, 0);
                            }),
                        ],
                        [
                          "Target",
                          String(metric.target),
                          "number",
                          (value: string) =>
                            mutateScorecardMetric(tabId, block.id, metric.id, (entry) => {
                              entry.target = toNumber(value, 100);
                            }),
                        ],
                        [
                          "Unit",
                          metric.unit,
                          "text",
                          (value: string) =>
                            mutateScorecardMetric(tabId, block.id, metric.id, (entry) => {
                              entry.unit = value.slice(0, 24);
                            }),
                        ],
                      ] as const
                    ).map(([label, value, type, onChange]) => (
                      <div key={label} className="space-y-1">
                        <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                          {label}
                        </p>
                        <Input
                          type={type}
                          value={value}
                          placeholder={label === "Unit" ? "%" : undefined}
                          className="rounded-xl"
                          aria-label={`${label} for ${metric.label || "scorecard metric"}`}
                          onChange={(event) => onChange(event.target.value)}
                        />
                      </div>
                    ))}
                  </div>
                </article>
              );
            })}
          </div>
        ) : (
          <div className="rounded-3xl border border-dashed border-muted/20 bg-muted/5 py-12 text-center">
            <BarChart3 className="mx-auto mb-4 size-8 text-muted-foreground/40" />
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
              No metrics defined
            </p>
            <p className="mt-2 text-sm text-muted-foreground">
              Add a metric to track performance against a target.
            </p>
            <Button
              type="button"
              variant="secondary"
              size="sm"
              className="mt-4 rounded-full px-4"
              aria-label="Add first scorecard metric"
              onClick={() => addScorecardMetric(tabId, block.id)}
            >
              <Plus />
              Add Metric
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
