// apps/web/app/components/workspace/node/blocks/WorkspaceContentPipelineBlockEditor.vue
<script setup lang="ts">
import {
    WORKSPACE_CONTENT_PIPELINE_STATUSES,
    WORKSPACE_CONTENT_PLATFORMS,
    createWorkspaceContentPipelineItem,
    getContentPipelineSummary,
    workspaceContentPipelineStatusLabels,
    workspaceContentPlatformLabels,
    type WorkspaceContentPipelineBlock,
    type WorkspaceContentPipelineStatus,
    type WorkspaceContentPlatform,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
    block: WorkspaceContentPipelineBlock;
    tabId: string;
}>();

const { mutateTypedBlock } = useWorkspaceNodeEditorContext();

const summary = computed(() => getContentPipelineSummary(props.block));
const platformOptions = WORKSPACE_CONTENT_PLATFORMS.map((platform) => ({
    label: workspaceContentPlatformLabels[platform],
    value: platform,
    icon: getPlatformIcon(platform),
})) satisfies Array<{
    label: string;
    value: WorkspaceContentPlatform;
    icon: string;
}>;

function getPlatformIcon(platform: WorkspaceContentPlatform) {
    switch (platform) {
        case "instagram":
            return "i-simple-icons-instagram";
        case "linkedin":
            return "i-simple-icons-linkedin";
        default:
            return "i-lucide-share-2";
        case "youtube":
            return "i-simple-icons-youtube";
        case "tiktok":
            return "i-simple-icons-tiktok";
    }
}

const columnConfigs: Array<{
    status: WorkspaceContentPipelineStatus;
    className: string;
    dotClass: string;
    icon: string;
}> = [
    {
        status: "ideas",
        className: "border-muted/10 bg-muted/5",
        dotClass: "bg-muted/60",
        icon: "i-lucide-lightbulb",
    },
    {
        status: "draft",
        className: "border-warning/10 bg-warning/5",
        dotClass: "bg-warning",
        icon: "i-lucide-pencil-line",
    },
    {
        status: "review",
        className: "border-primary/10 bg-primary/5",
        dotClass: "bg-primary",
        icon: "i-lucide-eye",
    },
    {
        status: "approved",
        className: "border-success/10 bg-success/5",
        dotClass: "bg-success",
        icon: "i-lucide-check-circle-2",
    },
    {
        status: "published",
        className: "border-secondary/10 bg-secondary/5",
        dotClass: "bg-secondary",
        icon: "i-lucide-rocket",
    },
];

const itemsByStatus = computed(
    () =>
        Object.fromEntries(
            WORKSPACE_CONTENT_PIPELINE_STATUSES.map((status) => [
                status,
                props.block.items.filter((item) => item.status === status),
            ]),
        ) as Record<
            WorkspaceContentPipelineStatus,
            WorkspaceContentPipelineBlock["items"]
        >,
);
const draggingItemId = ref<string | null>(null);
const dragOverStatus = ref<WorkspaceContentPipelineStatus | null>(null);

function addItem() {
    mutateTypedBlock(
        props.tabId,
        props.block.id,
        "content-pipeline",
        (entry) => {
            entry.items.unshift(
                createWorkspaceContentPipelineItem({
                    title: "",
                    status: "ideas",
                }),
            );
        },
    );
}

function mutateItem(
    itemId: string,
    mutator: (item: WorkspaceContentPipelineBlock["items"][number]) => void,
) {
    mutateTypedBlock(
        props.tabId,
        props.block.id,
        "content-pipeline",
        (entry) => {
            const target = entry.items.find(
                (candidate) => candidate.id === itemId,
            );

            if (!target) {
                return;
            }

            mutator(target);
        },
    );
}

function moveItem(itemId: string, status: WorkspaceContentPipelineStatus) {
    mutateItem(itemId, (item) => {
        item.status = status;
    });
}

function onItemDragStart(itemId: string, event: DragEvent) {
    draggingItemId.value = itemId;

    if (!event.dataTransfer) {
        return;
    }

    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("application/x-workspace-content-item", itemId);
    event.dataTransfer.setData("text/plain", itemId);
}

function clearDragState() {
    draggingItemId.value = null;
    dragOverStatus.value = null;
}

function onColumnDragOver(
    status: WorkspaceContentPipelineStatus,
    event: DragEvent,
) {
    if (!draggingItemId.value) {
        return;
    }

    event.preventDefault();

    if (event.dataTransfer) {
        event.dataTransfer.dropEffect = "move";
    }

    dragOverStatus.value = status;
}

function onColumnDragLeave(
    status: WorkspaceContentPipelineStatus,
    event: DragEvent,
) {
    const currentTarget = event.currentTarget;
    const nextTarget = event.relatedTarget;

    if (
        currentTarget instanceof HTMLElement &&
        nextTarget instanceof Node &&
        currentTarget.contains(nextTarget)
    ) {
        return;
    }

    if (dragOverStatus.value === status) {
        dragOverStatus.value = null;
    }
}

function onColumnDrop(
    status: WorkspaceContentPipelineStatus,
    event: DragEvent,
) {
    event.preventDefault();
    const itemId =
        draggingItemId.value ||
        event.dataTransfer?.getData("application/x-workspace-content-item") ||
        "";

    if (!itemId) {
        clearDragState();
        return;
    }

    moveItem(itemId, status);
    clearDragState();
}

function removeItem(itemId: string) {
    mutateTypedBlock(
        props.tabId,
        props.block.id,
        "content-pipeline",
        (entry) => {
            entry.items = entry.items.filter((item) => item.id !== itemId);
        },
    );
}

function moveItemByOffset(itemId: string, offset: -1 | 1) {
    const currentStatus = props.block.items.find(
        (item) => item.id === itemId,
    )?.status;

    if (!currentStatus) {
        return;
    }

    const currentIndex =
        WORKSPACE_CONTENT_PIPELINE_STATUSES.indexOf(currentStatus);

    if (currentIndex === -1) {
        return;
    }

    const nextStatus =
        WORKSPACE_CONTENT_PIPELINE_STATUSES[currentIndex + offset];

    if (!nextStatus) {
        return;
    }

    moveItem(itemId, nextStatus);
}

function canMoveItem(
    itemStatus: WorkspaceContentPipelineStatus,
    offset: -1 | 1,
) {
    const currentIndex =
        WORKSPACE_CONTENT_PIPELINE_STATUSES.indexOf(itemStatus);

    return (
        currentIndex + offset >= 0 &&
        currentIndex + offset < WORKSPACE_CONTENT_PIPELINE_STATUSES.length
    );
}

function getTopPlatformLabel() {
    return summary.value.topPlatform
        ? workspaceContentPlatformLabels[summary.value.topPlatform]
        : "None";
}
</script>

<template>
    <div class="space-y-8">
        <!-- Summary Metrics -->
        <div class="grid gap-4 grid-cols-2 lg:grid-cols-4">
            <div
                class="group relative overflow-hidden rounded-[24px] bg-elevated/5 p-5 border border-muted/10 transition-all hover:bg-elevated/10"
            >
                <div class="flex items-start justify-between">
                    <div>
                        <p
                            class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/50"
                        >
                            Total Pieces
                        </p>
                        <p
                            class="mt-2 text-3xl font-black tracking-tight text-highlighted"
                        >
                            {{ summary.totalItems }}
                        </p>
                    </div>
                    <div
                        class="size-10 rounded-2xl bg-primary/10 flex items-center justify-center"
                    >
                        <UIcon
                            name="i-lucide-layers"
                            class="size-5 text-primary"
                        />
                    </div>
                </div>
                <p class="mt-4 text-xs text-muted/60 leading-relaxed">
                    Active items in pipeline
                </p>
            </div>

            <div
                class="group relative overflow-hidden rounded-[24px] bg-elevated/5 p-5 border border-muted/10 transition-all hover:bg-elevated/10"
            >
                <div class="flex items-start justify-between">
                    <div>
                        <p
                            class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/50"
                        >
                            Review Queue
                        </p>
                        <p
                            class="mt-2 text-3xl font-black tracking-tight text-highlighted"
                        >
                            {{ summary.reviewCount }}
                        </p>
                    </div>
                    <div
                        class="size-10 rounded-2xl bg-warning/10 flex items-center justify-center"
                    >
                        <UIcon
                            name="i-lucide-clipboard-check"
                            class="size-5 text-warning"
                        />
                    </div>
                </div>
                <p class="mt-4 text-xs text-muted/60 leading-relaxed">
                    Awaiting approval
                </p>
            </div>

            <div
                class="group relative overflow-hidden rounded-[24px] bg-elevated/5 p-5 border border-muted/10 transition-all hover:bg-elevated/10"
            >
                <div class="flex items-start justify-between">
                    <div>
                        <p
                            class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/50"
                        >
                            Published
                        </p>
                        <p
                            class="mt-2 text-3xl font-black tracking-tight text-highlighted"
                        >
                            {{ summary.publishedCount }}
                        </p>
                    </div>
                    <div
                        class="size-10 rounded-2xl bg-success/10 flex items-center justify-center"
                    >
                        <UIcon
                            name="i-lucide-rocket"
                            class="size-5 text-success"
                        />
                    </div>
                </div>
                <p class="mt-4 text-xs text-muted/60 leading-relaxed">
                    Live content pieces
                </p>
            </div>

            <div
                class="group relative overflow-hidden rounded-[24px] bg-elevated/5 p-5 border border-muted/10 transition-all hover:bg-elevated/10"
            >
                <div class="flex items-start justify-between">
                    <div>
                        <p
                            class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/50"
                        >
                            Top Platform
                        </p>
                        <p
                            class="mt-2 text-3xl font-black tracking-tight text-highlighted"
                        >
                            {{
                                summary.topPlatform
                                    ? summary.topPlatform
                                          .slice(0, 3)
                                          .toUpperCase()
                                    : "N/A"
                            }}
                        </p>
                    </div>
                    <div
                        class="size-10 rounded-2xl bg-secondary/10 flex items-center justify-center"
                    >
                        <UIcon
                            :name="
                                summary.topPlatform
                                    ? getPlatformIcon(summary.topPlatform)
                                    : 'i-lucide-trending-up'
                            "
                            class="size-5 text-secondary"
                        />
                    </div>
                </div>
                <p class="mt-4 text-xs text-muted/60 leading-relaxed">
                    {{ getTopPlatformLabel() }}
                </p>
            </div>
        </div>

        <!-- Actions Bar -->
        <div class="flex flex-wrap items-center justify-between gap-4 px-1">
            <div class="space-y-1">
                <h3 class="text-base font-bold text-highlighted">
                    Content Pipeline
                </h3>
                <p class="text-xs text-muted">
                    Drag items between stages or use the move buttons for
                    keyboard-safe updates.
                </p>
            </div>

            <UButton
                color="primary"
                variant="solid"
                icon="i-lucide-plus"
                class="rounded-full px-5 py-2.5 font-bold shadow-lg shadow-primary/20"
                @click="addItem"
            >
                New Piece
            </UButton>
        </div>

        <!-- Pipeline Board -->
        <div
            class="overflow-x-auto pb-6 -mx-4 px-4 sm:mx-0 sm:px-0 scrollbar-thin scrollbar-thumb-muted/20 snap-x snap-mandatory"
        >
            <div class="flex gap-6">
                <section
                    v-for="column in columnConfigs"
                    :key="column.status"
                    class="flex flex-col flex-shrink-0 w-[300px] snap-start rounded-[32px] border p-4 transition-all duration-300"
                    :class="[
                        column.className,
                        dragOverStatus === column.status
                            ? 'ring-2 ring-primary/30 brightness-110 shadow-xl'
                            : '',
                    ]"
                    @dragover="onColumnDragOver(column.status, $event)"
                    @dragleave="onColumnDragLeave(column.status, $event)"
                    @drop="onColumnDrop(column.status, $event)"
                >
                    <!-- Column Header -->
                    <div class="p-4 flex items-center justify-between">
                        <div class="flex items-center gap-3">
                            <div
                                class="size-8 rounded-xl bg-default/80 flex items-center justify-center border border-muted/10 shadow-sm"
                            >
                                <UIcon
                                    :name="column.icon"
                                    class="size-4"
                                    :class="
                                        column.dotClass.replace('bg-', 'text-')
                                    "
                                />
                            </div>
                            <div>
                                <p
                                    class="text-[10px] font-black uppercase tracking-[0.2em] text-muted/50 leading-none"
                                >
                                    {{
                                        workspaceContentPipelineStatusLabels[
                                            column.status
                                        ]
                                    }}
                                </p>
                                <p
                                    class="mt-1 text-xs font-bold text-highlighted/60 leading-none"
                                >
                                    {{
                                        itemsByStatus[column.status]?.length ??
                                        0
                                    }}
                                    items
                                </p>
                            </div>
                        </div>
                    </div>

                    <!-- Items Container -->
                    <div class="flex-1 space-y-3 p-2 min-h-[400px]">
                        <article
                            v-for="item in itemsByStatus[column.status]"
                            :key="item.id"
                            class="group relative rounded-[24px] border border-muted/10 bg-default/80 p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md hover:bg-default"
                            :class="
                                draggingItemId === item.id
                                    ? 'pointer-events-none scale-95 opacity-40 grayscale'
                                    : 'cursor-grab active:cursor-grabbing'
                            "
                            draggable="true"
                            @dragstart="onItemDragStart(item.id, $event)"
                            @dragend="clearDragState"
                        >
                            <!-- Card Header -->
                            <div class="flex items-start gap-2">
                                <UTextarea
                                    :model-value="item.title"
                                    variant="none"
                                    placeholder="Untitled content piece"
                                    class="flex-1"
                                    autoresize
                                    :rows="1"
                                    :ui="{
                                        base: 'p-0 text-sm font-bold text-highlighted placeholder:text-muted/30 focus:ring-0',
                                    }"
                                    @update:model-value="
                                        mutateItem(item.id, (entry) => {
                                            entry.title = ($event ?? '').slice(
                                                0,
                                                240,
                                            );
                                        })
                                    "
                                />

                                <div class="flex items-center gap-1">
                                    <UButton
                                        color="neutral"
                                        variant="ghost"
                                        icon="i-lucide-arrow-left"
                                        size="xs"
                                        class="rounded-lg"
                                        :disabled="
                                            !canMoveItem(item.status, -1)
                                        "
                                        :aria-label="`Move ${item.title || 'content item'} to the previous stage`"
                                        @click="moveItemByOffset(item.id, -1)"
                                    />
                                    <UButton
                                        color="neutral"
                                        variant="ghost"
                                        icon="i-lucide-arrow-right"
                                        size="xs"
                                        class="rounded-lg"
                                        :disabled="!canMoveItem(item.status, 1)"
                                        :aria-label="`Move ${item.title || 'content item'} to the next stage`"
                                        @click="moveItemByOffset(item.id, 1)"
                                    />
                                    <UButton
                                        color="neutral"
                                        variant="ghost"
                                        icon="i-lucide-trash"
                                        size="xs"
                                        class="rounded-lg hover:text-error"
                                        :aria-label="`Remove ${item.title || 'content item'}`"
                                        @click="removeItem(item.id)"
                                    />
                                </div>
                            </div>

                            <!-- Card Meta -->
                            <div class="mt-4 flex flex-wrap items-center gap-2">
                                <USelectMenu
                                    :model-value="
                                        platformOptions.find(
                                            (option) =>
                                                option.value === item.platform,
                                        )
                                    "
                                    :items="platformOptions"
                                    value-attribute="value"
                                    size="xs"
                                    class="w-[110px]"
                                    :ui-menu="{ base: 'rounded-xl' }"
                                    :ui="{
                                        base: 'rounded-full bg-elevated/5 border-muted/10',
                                    }"
                                    @update:model-value="
                                        mutateItem(item.id, (entry) => {
                                            entry.platform =
                                                (
                                                    $event as
                                                        | {
                                                              label: string;
                                                              value: WorkspaceContentPlatform;
                                                              icon: string;
                                                          }
                                                        | undefined
                                                )?.value ?? 'instagram';
                                        })
                                    "
                                >
                                    <template #leading>
                                        <UIcon
                                            :name="
                                                getPlatformIcon(item.platform)
                                            "
                                            class="size-3.5"
                                        />
                                    </template>
                                </USelectMenu>

                                <div class="flex-1 min-w-0">
                                    <UInput
                                        :model-value="item.assignee"
                                        size="xs"
                                        icon="i-lucide-user"
                                        placeholder="Assignee"
                                        class="w-full"
                                        :ui="{
                                            base: 'rounded-full bg-elevated/5 border-muted/10',
                                        }"
                                        @update:model-value="
                                            mutateItem(item.id, (entry) => {
                                                entry.assignee = (
                                                    $event ?? ''
                                                ).slice(0, 120);
                                            })
                                        "
                                    />
                                </div>
                            </div>
                        </article>

                        <!-- Empty State -->
                        <div
                            v-if="
                                (itemsByStatus[column.status]?.length ?? 0) ===
                                0
                            "
                            class="h-full flex flex-col items-center justify-center border-2 border-dashed border-muted/5 rounded-[24px] bg-default/10 p-6 text-center"
                        >
                            <div
                                class="size-10 rounded-full bg-muted/5 flex items-center justify-center mb-2"
                            >
                                <UIcon
                                    :name="column.icon"
                                    class="size-5 text-muted/20"
                                />
                            </div>
                            <p
                                class="text-[10px] font-bold uppercase tracking-wider text-muted/30"
                            >
                                No {{ column.status }}
                            </p>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</template>

// apps/web/src/features/workspace/node/blocks/workspace-content-pipeline-block-editor.tsx
import {
  WORKSPACE_CONTENT_PIPELINE_STATUSES,
  WORKSPACE_CONTENT_PLATFORMS,
  createWorkspaceContentPipelineItem,
  getContentPipelineSummary,
  workspaceContentPipelineStatusLabels,
  workspaceContentPlatformLabels,
  type WorkspaceContentPipelineBlock,
  type WorkspaceContentPipelineStatus,
  type WorkspaceContentPlatform,
} from "@brainiac/workspace";
import {
  ArrowLeft,
  ArrowRight,
  CheckCircle2,
  Eye,
  Camera,
  Layers,
  Lightbulb,
  Link,
  Music2,
  PencilLine,
  Play,
  Plus,
  Rocket,
  Trash2,
  TrendingUp,
  User,
  type LucideIcon,
} from "lucide-react";
import { useMemo, useState } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { BlockSelect } from "@/components/workspace/node/blocks/shared/block-select";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { Button } from "@/ui/button";
import { Input } from "@/ui/input";
import { Textarea } from "@/ui/textarea";
import { cn } from "@/lib/utils";

const columnConfigs: Array<{
  status: WorkspaceContentPipelineStatus;
  className: string;
  dotClass: string;
  icon: LucideIcon;
}> = [
  {
    status: "ideas",
    className: "border-muted/10 bg-muted/5",
    dotClass: "bg-muted-foreground/60",
    icon: Lightbulb,
  },
  {
    status: "draft",
    className: "border-warning/10 bg-warning/5",
    dotClass: "bg-warning",
    icon: PencilLine,
  },
  {
    status: "review",
    className: "border-primary/10 bg-primary/5",
    dotClass: "bg-primary",
    icon: Eye,
  },
  {
    status: "approved",
    className: "border-success/10 bg-success/5",
    dotClass: "bg-success",
    icon: CheckCircle2,
  },
  {
    status: "published",
    className: "border-secondary/10 bg-secondary/5",
    dotClass: "bg-secondary",
    icon: Rocket,
  },
];

const platformOptions = WORKSPACE_CONTENT_PLATFORMS.map((platform) => ({
  label: workspaceContentPlatformLabels[platform],
  value: platform,
}));

function getPlatformIcon(platform: WorkspaceContentPlatform): LucideIcon {
  switch (platform) {
    case "instagram":
      return Camera;
    case "linkedin":
      return Link;
    case "youtube":
      return Play;
    case "tiktok":
      return Music2;
    default: {
      const exhaustiveCheck: never = platform;
      return exhaustiveCheck;
    }
  }
}

export function WorkspaceContentPipelineBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceContentPipelineBlock>) {
  const { mutateTypedBlock } = useWorkspaceNodeEditorContext();
  const [draggingItemId, setDraggingItemId] = useState<string | null>(null);
  const [dragOverStatus, setDragOverStatus] = useState<WorkspaceContentPipelineStatus | null>(null);

  const summary = useMemo(() => getContentPipelineSummary(block), [block]);

  const itemsByStatus = useMemo(
    () =>
      Object.fromEntries(
        WORKSPACE_CONTENT_PIPELINE_STATUSES.map((status) => [
          status,
          block.items.filter((item) => item.status === status),
        ]),
      ) as Record<WorkspaceContentPipelineStatus, WorkspaceContentPipelineBlock["items"]>,
    [block.items],
  );

  function mutatePipelineBlock(mutator: (entry: WorkspaceContentPipelineBlock) => void) {
    mutateTypedBlock(tabId, block.id, "content-pipeline", mutator);
  }

  function mutateItem(
    itemId: string,
    mutator: (item: WorkspaceContentPipelineBlock["items"][number]) => void,
  ) {
    mutatePipelineBlock((entry) => {
      const target = entry.items.find((candidate) => candidate.id === itemId);
      if (target) {
        mutator(target);
      }
    });
  }

  function addItem() {
    mutatePipelineBlock((entry) => {
      entry.items.unshift(
        createWorkspaceContentPipelineItem({
          title: "",
          status: "ideas",
        }),
      );
    });
  }

  function moveItem(itemId: string, status: WorkspaceContentPipelineStatus) {
    mutateItem(itemId, (item) => {
      item.status = status;
    });
  }

  function removeItem(itemId: string) {
    mutatePipelineBlock((entry) => {
      entry.items = entry.items.filter((item) => item.id !== itemId);
    });
  }

  function moveItemByOffset(itemId: string, offset: -1 | 1) {
    const currentStatus = block.items.find((item) => item.id === itemId)?.status;
    if (!currentStatus) {
      return;
    }

    const currentIndex = WORKSPACE_CONTENT_PIPELINE_STATUSES.indexOf(currentStatus);
    if (currentIndex === -1) {
      return;
    }

    const nextStatus = WORKSPACE_CONTENT_PIPELINE_STATUSES[currentIndex + offset];
    if (!nextStatus) {
      return;
    }

    moveItem(itemId, nextStatus);
  }

  function canMoveItem(itemStatus: WorkspaceContentPipelineStatus, offset: -1 | 1) {
    const currentIndex = WORKSPACE_CONTENT_PIPELINE_STATUSES.indexOf(itemStatus);
    return (
      currentIndex + offset >= 0 &&
      currentIndex + offset < WORKSPACE_CONTENT_PIPELINE_STATUSES.length
    );
  }

  function clearDragState() {
    setDraggingItemId(null);
    setDragOverStatus(null);
  }

  function onItemDragStart(itemId: string, event: React.DragEvent<HTMLElement>) {
    setDraggingItemId(itemId);
    event.dataTransfer.effectAllowed = "move";
    event.dataTransfer.setData("application/x-workspace-content-item", itemId);
    event.dataTransfer.setData("text/plain", itemId);
  }

  function onColumnDragOver(
    status: WorkspaceContentPipelineStatus,
    event: React.DragEvent<HTMLElement>,
  ) {
    if (!draggingItemId) {
      return;
    }

    event.preventDefault();
    event.dataTransfer.dropEffect = "move";
    setDragOverStatus(status);
  }

  function onColumnDragLeave(
    status: WorkspaceContentPipelineStatus,
    event: React.DragEvent<HTMLElement>,
  ) {
    const currentTarget = event.currentTarget;
    const nextTarget = event.relatedTarget;

    if (
      currentTarget instanceof HTMLElement &&
      nextTarget instanceof Node &&
      currentTarget.contains(nextTarget)
    ) {
      return;
    }

    if (dragOverStatus === status) {
      setDragOverStatus(null);
    }
  }

  function onColumnDrop(
    status: WorkspaceContentPipelineStatus,
    event: React.DragEvent<HTMLElement>,
  ) {
    event.preventDefault();
    const itemId =
      draggingItemId || event.dataTransfer.getData("application/x-workspace-content-item") || "";

    if (!itemId) {
      clearDragState();
      return;
    }

    moveItem(itemId, status);
    clearDragState();
  }

  function getTopPlatformLabel() {
    return summary.topPlatform ? workspaceContentPlatformLabels[summary.topPlatform] : "None";
  }

  const TopPlatformIcon = summary.topPlatform ? getPlatformIcon(summary.topPlatform) : TrendingUp;

  return (
    <div className="space-y-8">
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <div className="group relative overflow-hidden rounded-[24px] border border-muted/10 bg-muted/5 p-5 transition-all hover:bg-muted/10">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/50">
                Total Pieces
              </p>
              <p className="mt-2 text-3xl font-black tracking-tight text-foreground">
                {summary.totalItems}
              </p>
            </div>
            <div className="flex size-10 items-center justify-center rounded-2xl bg-primary/10">
              <Layers className="size-5 text-primary" />
            </div>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-muted-foreground/60">
            Active items in pipeline
          </p>
        </div>

        <div className="group relative overflow-hidden rounded-[24px] border border-muted/10 bg-muted/5 p-5 transition-all hover:bg-muted/10">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/50">
                Review Queue
              </p>
              <p className="mt-2 text-3xl font-black tracking-tight text-foreground">
                {summary.reviewCount}
              </p>
            </div>
            <div className="flex size-10 items-center justify-center rounded-2xl bg-warning/10">
              <Eye className="size-5 text-warning" />
            </div>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-muted-foreground/60">Awaiting approval</p>
        </div>

        <div className="group relative overflow-hidden rounded-[24px] border border-muted/10 bg-muted/5 p-5 transition-all hover:bg-muted/10">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/50">
                Published
              </p>
              <p className="mt-2 text-3xl font-black tracking-tight text-foreground">
                {summary.publishedCount}
              </p>
            </div>
            <div className="flex size-10 items-center justify-center rounded-2xl bg-success/10">
              <Rocket className="size-5 text-success" />
            </div>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-muted-foreground/60">
            Live content pieces
          </p>
        </div>

        <div className="group relative overflow-hidden rounded-[24px] border border-muted/10 bg-muted/5 p-5 transition-all hover:bg-muted/10">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/50">
                Top Platform
              </p>
              <p className="mt-2 text-3xl font-black tracking-tight text-foreground">
                {summary.topPlatform ? summary.topPlatform.slice(0, 3).toUpperCase() : "N/A"}
              </p>
            </div>
            <div className="flex size-10 items-center justify-center rounded-2xl bg-secondary/10">
              <TopPlatformIcon className="size-5 text-secondary" />
            </div>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-muted-foreground/60">
            {getTopPlatformLabel()}
          </p>
        </div>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-4 px-1">
        <div className="space-y-1">
          <h3 className="text-base font-bold text-foreground">Content Pipeline</h3>
          <p className="text-xs text-muted-foreground">
            Drag items between stages or use the move buttons for keyboard-safe updates.
          </p>
        </div>

        <Button
          type="button"
          size="sm"
          className="rounded-full px-5 py-2.5 font-bold shadow-lg shadow-primary/20"
          onClick={addItem}
        >
          <Plus />
          New Piece
        </Button>
      </div>

      <div className="-mx-4 overflow-x-auto px-4 pb-6 sm:mx-0 sm:px-0">
        <div className="flex gap-6">
          {columnConfigs.map((column) => {
            const ColumnIcon = column.icon;
            const columnItems = itemsByStatus[column.status] ?? [];

            return (
              <section
                key={column.status}
                className={cn(
                  "flex w-[300px] shrink-0 snap-start flex-col rounded-[32px] border p-4 transition-all duration-300",
                  column.className,
                  dragOverStatus === column.status
                    ? "shadow-xl ring-2 ring-primary/30 brightness-110"
                    : "",
                )}
                onDragOver={(event) => onColumnDragOver(column.status, event)}
                onDragLeave={(event) => onColumnDragLeave(column.status, event)}
                onDrop={(event) => onColumnDrop(column.status, event)}
              >
                <div className="flex items-center justify-between p-4">
                  <div className="flex items-center gap-3">
                    <div className="flex size-8 items-center justify-center rounded-xl border border-muted/10 bg-background/80 shadow-sm">
                      <ColumnIcon
                        className={cn("size-4", column.dotClass.replace("bg-", "text-"))}
                      />
                    </div>
                    <div>
                      <p className="text-[10px] font-black uppercase leading-none tracking-[0.2em] text-muted-foreground/50">
                        {workspaceContentPipelineStatusLabels[column.status]}
                      </p>
                      <p className="mt-1 text-xs font-bold leading-none text-foreground/60">
                        {columnItems.length} items
                      </p>
                    </div>
                  </div>
                </div>

                <div className="min-h-[400px] flex-1 space-y-3 p-2">
                  {columnItems.map((item) => {
                    const PlatformIcon = getPlatformIcon(item.platform);

                    return (
                      <article
                        key={item.id}
                        draggable
                        className={cn(
                          "group relative rounded-[24px] border border-muted/10 bg-background/80 p-4 shadow-sm transition-all hover:border-primary/30 hover:bg-background hover:shadow-md",
                          draggingItemId === item.id
                            ? "pointer-events-none scale-95 opacity-40 grayscale"
                            : "cursor-grab active:cursor-grabbing",
                        )}
                        onDragStart={(event) => onItemDragStart(item.id, event)}
                        onDragEnd={clearDragState}
                      >
                        <div className="flex items-start gap-2">
                          <Textarea
                            value={item.title}
                            placeholder="Untitled content piece"
                            rows={1}
                            className="min-h-0 flex-1 resize-none border-0 bg-transparent p-0 text-sm font-bold text-foreground shadow-none placeholder:text-muted-foreground/30 focus-visible:ring-0"
                            onChange={(event) =>
                              mutateItem(item.id, (entry) => {
                                entry.title = event.target.value.slice(0, 240);
                              })
                            }
                          />

                          <div className="flex items-center gap-1">
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              className="rounded-lg"
                              disabled={!canMoveItem(item.status, -1)}
                              aria-label={`Move ${item.title || "content item"} to the previous stage`}
                              onClick={() => moveItemByOffset(item.id, -1)}
                            >
                              <ArrowLeft />
                            </Button>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              className="rounded-lg"
                              disabled={!canMoveItem(item.status, 1)}
                              aria-label={`Move ${item.title || "content item"} to the next stage`}
                              onClick={() => moveItemByOffset(item.id, 1)}
                            >
                              <ArrowRight />
                            </Button>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              className="rounded-lg hover:text-destructive"
                              aria-label={`Remove ${item.title || "content item"}`}
                              onClick={() => removeItem(item.id)}
                            >
                              <Trash2 />
                            </Button>
                          </div>
                        </div>

                        <div className="mt-4 flex flex-wrap items-center gap-2">
                          <div className="flex w-[110px] items-center gap-1.5">
                            <PlatformIcon className="size-3.5 shrink-0 text-muted-foreground" />
                            <BlockSelect
                              value={item.platform}
                              options={platformOptions}
                              className="h-8 rounded-full border-muted/10 bg-muted/5 text-xs"
                              aria-label={`Platform for ${item.title || "content item"}`}
                              onValueChange={(value) =>
                                mutateItem(item.id, (entry) => {
                                  entry.platform = value as WorkspaceContentPlatform;
                                })
                              }
                            />
                          </div>

                          <div className="min-w-0 flex-1">
                            <div className="relative">
                              <User className="pointer-events-none absolute top-1/2 left-3 size-3.5 -translate-y-1/2 text-muted-foreground" />
                              <Input
                                value={item.assignee}
                                placeholder="Assignee"
                                className="h-8 rounded-full border-muted/10 bg-muted/5 pl-9 text-xs"
                                onChange={(event) =>
                                  mutateItem(item.id, (entry) => {
                                    entry.assignee = event.target.value.slice(0, 120);
                                  })
                                }
                              />
                            </div>
                          </div>
                        </div>
                      </article>
                    );
                  })}

                  {columnItems.length === 0 ? (
                    <div className="flex h-full flex-col items-center justify-center rounded-[24px] border-2 border-dashed border-muted/5 bg-background/10 p-6 text-center">
                      <div className="mb-2 flex size-10 items-center justify-center rounded-full bg-muted/5">
                        <ColumnIcon className="size-5 text-muted-foreground/20" />
                      </div>
                      <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/30">
                        No {column.status}
                      </p>
                    </div>
                  ) : null}
                </div>
              </section>
            );
          })}
        </div>
      </div>
    </div>
  );
}
