// apps/web/src/components/agency/agency-time-tracker.tsx
import { Link, MoreVertical, Search, Tag, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { AgencyTaskChooser } from "@/components/agency/agency-task-chooser";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import {
  useAgencyActiveTimerQuery,
  useAgencyProjectTasksQuery,
  useAgencyProjectsQuery,
  useAgencyTagsQuery,
  type AgencyProjectTaskStatus,
} from "@/hooks/use-agency-queries";
import { formatDuration } from "@/lib/utils/format-duration";
import {
  getAgencyLinkUrlDisplayLabel,
  normalizeAgencyLinkUrl,
} from "@/lib/utils/normalize-agency-link-url";
import {
  selectIsTimerMutationPending,
  useAgencyTimeTrackingStore,
} from "@/stores/agency-time-tracking";

type AgencyTimeTrackerProps = {
  teamId: string;
};

const OPEN_TASK_STATUSES: AgencyProjectTaskStatus[] = ["open", "in_progress"];

export function AgencyTimeTracker({ teamId }: AgencyTimeTrackerProps) {
  const agencyTimeTrackingStore = useAgencyTimeTrackingStore();
  const isTimerMutationPending = useAgencyTimeTrackingStore(selectIsTimerMutationPending);
  const [now, setNow] = useState(Date.now());
  const [tagSearch, setTagSearch] = useState("");

  useEffect(() => {
    const tickerHandle = setInterval(() => setNow(Date.now()), 1_000);
    return () => clearInterval(tickerHandle);
  }, []);

  const projectsQuery = useAgencyProjectsQuery(teamId);

  const tasksQuery = useAgencyProjectTasksQuery(teamId, {
    statuses: OPEN_TASK_STATUSES,
  });

  const tagsQuery = useAgencyTagsQuery(teamId);

  const activeTimerQuery = useAgencyActiveTimerQuery(teamId);

  const projects = projectsQuery.data?.items ?? [];
  const tasks = tasksQuery.data?.items ?? [];
  const tags = tagsQuery.data?.items ?? [];
  const activeTimer = activeTimerQuery.data?.timer ?? null;
  const trackerDraft = teamId ? agencyTimeTrackingStore.getDraft(teamId) : null;

  const filteredTags = useMemo(() => {
    const query = tagSearch.trim().toLowerCase();
    if (!query) return tags;
    return tags.filter((tag) => tag.name.toLowerCase().includes(query));
  }, [tagSearch, tags]);

  const selectedTaskId = trackerDraft?.taskId ?? "";
  const selectedTagIds = trackerDraft?.selectedTagIds ?? [];
  const timerDescription = trackerDraft?.description ?? "";
  const timerLinkUrl = trackerDraft?.linkUrl ?? "";

  const selectedTask = tasks.find((task) => task.id === selectedTaskId) ?? null;
  const selectedProject = selectedTask
    ? (projects.find((project) => project.id === selectedTask.projectId) ?? null)
    : null;
  const selectedTags = tags.filter((tag) => selectedTagIds.includes(tag.id));
  const linkUrlState = normalizeAgencyLinkUrl(timerLinkUrl);
  const hasValidLinkUrl = Boolean(linkUrlState.normalizedUrl);
  const linkUrlDisplayLabel = getAgencyLinkUrlDisplayLabel(linkUrlState.normalizedUrl);

  useEffect(() => {
    if (!teamId) return;
    agencyTimeTrackingStore.ensureTrackerDraft(teamId);
  }, [teamId, agencyTimeTrackingStore]);

  useEffect(() => {
    if (!teamId) return;
    agencyTimeTrackingStore.syncDraftFromActiveTimer(teamId, activeTimer);
  }, [teamId, activeTimer, agencyTimeTrackingStore]);

  const elapsedSeconds = useMemo(() => {
    if (!activeTimer) return 0;
    const startedAt = new Date(activeTimer.startedAt).getTime();
    if (Number.isNaN(startedAt)) return 0;
    return Math.max(0, Math.floor((now - startedAt) / 1_000));
  }, [activeTimer, now]);

  const canStartTimer = Boolean(teamId && selectedTask && selectedProject && !activeTimer);
  const canStopTimer = Boolean(activeTimer);

  const timerValidationHint = useMemo(() => {
    if (activeTimer ? canStopTimer : canStartTimer) return "";

    if (!activeTimer && !selectedTask) {
      return "Select a task to start this timer.";
    }

    return "";
  }, [activeTimer, canStartTimer, canStopTimer, selectedTask]);

  async function startTimer() {
    if (!teamId || !selectedProject || !selectedTask) return;

    await agencyTimeTrackingStore.startTimer({
      teamId,
      project: selectedProject,
      task: selectedTask,
      tagIds: [...selectedTagIds],
      selectedTags: [...selectedTags],
      description: timerDescription,
      linkUrl: timerLinkUrl,
    });
  }

  async function stopTimer(discard = false) {
    if (!teamId || !activeTimer || (!discard && !canStopTimer)) return;

    await agencyTimeTrackingStore.stopTimer({
      teamId,
      activeTimer,
      tagIds: [...selectedTagIds],
      selectedTags: [...selectedTags],
      description: timerDescription,
      linkUrl: timerLinkUrl,
      discard,
    });
  }

  return (
    <div className="space-y-2">
      <div className="flex flex-wrap items-center gap-2">
        <Input
          value={timerDescription}
          onChange={(e) =>
            teamId && agencyTimeTrackingStore.setTrackerDescription(teamId, e.target.value)
          }
          placeholder="What are you working on?"
          className="min-w-0 flex-1"
          disabled={isTimerMutationPending || !teamId}
        />

        <AgencyTaskChooser
          value={selectedTaskId}
          onValueChange={(value) =>
            teamId && agencyTimeTrackingStore.setTrackerTaskId(teamId, value || "")
          }
          projects={projects}
          tasks={tasks}
          placeholder={!teamId ? "Team first" : "Task"}
          className="w-64 shrink-0 max-sm:w-full"
          loading={projectsQuery.isPending || tasksQuery.isPending}
          disabled={
            !teamId ||
            projectsQuery.isPending ||
            tasksQuery.isPending ||
            Boolean(activeTimer)
          }
        />

        <Popover>
          <PopoverTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              disabled={isTimerMutationPending || !teamId || tagsQuery.isPending}
              aria-label="Select timer tags"
            >
              <Tag className={selectedTagIds.length > 0 ? "text-primary" : ""} />
            </Button>
          </PopoverTrigger>
          <PopoverContent align="end" className="w-64 space-y-2 p-2">
            <div className="relative">
              <Search className="absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted" />
              <Input
                value={tagSearch}
                onChange={(e) => setTagSearch(e.target.value)}
                placeholder="Search tags"
                className="h-8 pl-8 text-xs"
                disabled={tags.length === 0}
              />
            </div>
            <div className="flex max-h-52 flex-wrap gap-1 overflow-y-auto">
              {filteredTags.map((tag) => (
                <Button
                  key={tag.id}
                  variant={selectedTagIds.includes(tag.id) ? "secondary" : "ghost"}
                  size="sm"
                  className="rounded-full"
                  onClick={() => teamId && agencyTimeTrackingStore.toggleTrackerTag(teamId, tag.id)}
                >
                  {tag.name}
                </Button>
              ))}
              {tags.length === 0 ? (
                <div className="px-1 py-2 text-xs text-muted">
                  No tags yet. Add tags in Agency settings.
                </div>
              ) : filteredTags.length === 0 ? (
                <div className="px-1 py-2 text-xs text-muted">No matching tags.</div>
              ) : null}
            </div>
          </PopoverContent>
        </Popover>

        <Popover>
          <PopoverTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              disabled={isTimerMutationPending || !teamId}
            >
              <Link className={hasValidLinkUrl ? "text-primary" : ""} />
            </Button>
          </PopoverTrigger>
          <PopoverContent align="end" className="w-72 space-y-2 p-2">
            <div className="relative">
              <Link className="absolute top-1/2 left-2.5 size-3.5 -translate-y-1/2 text-muted" />
              <Input
                value={timerLinkUrl}
                onChange={(e) =>
                  teamId && agencyTimeTrackingStore.setTrackerLinkUrl(teamId, e.target.value)
                }
                placeholder="Paste a task, ticket, or brief URL"
                className="h-8 pl-8 text-xs"
              />
            </div>
            <div className="flex items-center justify-between gap-2">
              {linkUrlState.error ? (
                <p className="text-[11px] text-error">{linkUrlState.error}</p>
              ) : hasValidLinkUrl ? (
                <p className="truncate text-[11px] text-muted">{linkUrlState.normalizedUrl}</p>
              ) : (
                <span className="text-[11px] text-muted">Link this entry to a task or brief.</span>
              )}
              <Button
                variant="ghost"
                size="sm"
                disabled={!timerLinkUrl}
                onClick={() => teamId && agencyTimeTrackingStore.setTrackerLinkUrl(teamId, "")}
              >
                Clear
              </Button>
            </div>
          </PopoverContent>
        </Popover>

        <Button
          variant={activeTimer ? "secondary" : "default"}
          className="min-w-28 shrink-0 font-mono tabular-nums font-bold"
          disabled={activeTimer ? !canStopTimer : !canStartTimer}
          onClick={() => void (activeTimer ? stopTimer() : startTimer())}
        >
          {isTimerMutationPending
            ? "…"
            : activeTimer
              ? formatDuration(elapsedSeconds)
              : "Start"}
        </Button>

        {activeTimer ? (
          <Button variant="ghost" size="sm" onClick={() => void stopTimer(true)}>
            <MoreVertical />
          </Button>
        ) : null}
      </div>

      {selectedTags.length > 0 || hasValidLinkUrl ? (
        <div className="flex flex-wrap items-center gap-1.5">
          {linkUrlState.normalizedUrl ? (
            <a
              href={linkUrlState.normalizedUrl}
              target="_blank"
              rel="noreferrer"
              className="inline-flex min-w-0 max-w-full items-center gap-1 rounded-full border border-primary/20 bg-primary/10 px-2 py-1 text-xs text-primary transition hover:border-primary/40 hover:bg-primary/15"
            >
              <Link className="size-3 shrink-0" />
              <span className="truncate">{linkUrlDisplayLabel}</span>
            </a>
          ) : null}
          {selectedTags.map((tag) => (
            <Badge key={tag.id} variant="secondary" className="rounded-full">
              {tag.name}
            </Badge>
          ))}
        </div>
      ) : null}

      {timerValidationHint ? (
        <p className="text-xs text-warning">{timerValidationHint}</p>
      ) : null}

      {activeTimer ? (
        <Button
          variant="ghost"
          size="sm"
          className="text-error"
          onClick={() => void stopTimer(true)}
        >
          <Trash2 />
          Discard timer
        </Button>
      ) : null}
    </div>
  );
}

// apps/web/app/components/agency/AgencyTimeTracker.vue
<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
import { storeToRefs } from "pinia";

import AgencyTaskChooser from "~/components/agency/AgencyTaskChooser.vue";
import { useAgencyTimeTrackingStore } from "~/stores/agency-time-tracking";
import { formatDuration } from "~/utils/format-duration";
import {
  getAgencyLinkUrlDisplayLabel,
  normalizeAgencyLinkUrl,
} from "~/utils/normalize-agency-link-url";

const props = defineProps<{
  teamId: string;
}>();

const orpc = useOrpc();
const agencyTimeTrackingStore = useAgencyTimeTrackingStore();
const { draftByTeam, isTimerMutationPending } = storeToRefs(agencyTimeTrackingStore);

const now = ref(Date.now());
const tagSearch = ref("");

let tickerHandle: ReturnType<typeof setInterval> | null = null;

onMounted(() => {
  tickerHandle = setInterval(() => {
    now.value = Date.now();
  }, 1_000);
});

onBeforeUnmount(() => {
  if (tickerHandle) {
    clearInterval(tickerHandle);
    tickerHandle = null;
  }
});

const effectiveTeamId = computed(() => props.teamId);

const projectsQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.projects.list.queryOptions({
      input: {
        teamId: effectiveTeamId.value,
      },
    }),
    enabled: Boolean(effectiveTeamId.value),
  })),
);

const projects = computed(() => projectsQuery.data.value?.items ?? []);

const tasksQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.projectTasks.list.queryOptions({
      input: {
        teamId: effectiveTeamId.value,
        statuses: ["open", "in_progress"],
      },
    }),
    enabled: Boolean(effectiveTeamId.value),
  })),
);

const tasks = computed(() => tasksQuery.data.value?.items ?? []);

const tagsQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.tags.list.queryOptions({
      input: {
        teamId: effectiveTeamId.value,
      },
    }),
    enabled: Boolean(effectiveTeamId.value),
  })),
);

const tags = computed(() => tagsQuery.data.value?.items ?? []);
const filteredTags = computed(() => {
  const query = tagSearch.value.trim().toLowerCase();
  if (!query) {
    return tags.value;
  }

  return tags.value.filter((tag) => tag.name.toLowerCase().includes(query));
});

const activeTimerQuery = useQuery(
  computed(() => ({
    ...orpc.agencyOps.timer.getActive.queryOptions({
      input: {
        teamId: effectiveTeamId.value || undefined,
      },
    }),
    enabled: Boolean(effectiveTeamId.value),
    refetchInterval: 10_000,
  })),
);

const activeTimer = computed(() => activeTimerQuery.data.value?.timer ?? null);
const activeTimerQueryKey = computed(
  () =>
    orpc.agencyOps.timer.getActive.queryOptions({
      input: {
        teamId: effectiveTeamId.value || undefined,
      },
    }).queryKey,
);
const trackerDraft = computed(() =>
  effectiveTeamId.value ? (draftByTeam.value[effectiveTeamId.value] ?? null) : null,
);
const timerDescription = computed({
  get: () => trackerDraft.value?.description ?? "",
  set: (value: string) => {
    if (!effectiveTeamId.value) {
      return;
    }

    agencyTimeTrackingStore.setTrackerDescription(effectiveTeamId.value, value);
  },
});
const selectedTaskId = computed({
  get: () => trackerDraft.value?.taskId ?? "",
  set: (value: string) => {
    if (!effectiveTeamId.value) {
      return;
    }

    agencyTimeTrackingStore.setTrackerTaskId(effectiveTeamId.value, value || "");
  },
});
const selectedTagIds = computed({
  get: () => trackerDraft.value?.selectedTagIds ?? [],
  set: (value: string[]) => {
    if (!effectiveTeamId.value) {
      return;
    }

    agencyTimeTrackingStore.setTrackerSelectedTagIds(effectiveTeamId.value, value ?? []);
  },
});
const timerLinkUrl = computed({
  get: () => trackerDraft.value?.linkUrl ?? "",
  set: (value: string) => {
    if (!effectiveTeamId.value) {
      return;
    }

    agencyTimeTrackingStore.setTrackerLinkUrl(effectiveTeamId.value, value);
  },
});
const selectedTask = computed(
  () => tasks.value.find((task) => task.id === selectedTaskId.value) ?? null,
);
const selectedProject = computed(() =>
  selectedTask.value
    ? (projects.value.find((project) => project.id === selectedTask.value?.projectId) ?? null)
    : null,
);
const selectedTags = computed(() => {
  const selectedIds = new Set(selectedTagIds.value);

  return tags.value.filter((tag) => selectedIds.has(tag.id));
});
const linkUrlState = computed(() => normalizeAgencyLinkUrl(timerLinkUrl.value));
const hasValidLinkUrl = computed(() => Boolean(linkUrlState.value.normalizedUrl));
const linkUrlDisplayLabel = computed(() =>
  getAgencyLinkUrlDisplayLabel(linkUrlState.value.normalizedUrl),
);

watch(
  effectiveTeamId,
  (teamId) => {
    if (!teamId) {
      return;
    }

    agencyTimeTrackingStore.ensureTrackerDraft(teamId);
  },
  { immediate: true },
);

watch(
  activeTimer,
  (timer) => {
    if (!effectiveTeamId.value) {
      return;
    }

    agencyTimeTrackingStore.syncDraftFromActiveTimer(effectiveTeamId.value, timer);
  },
  { immediate: true },
);

watch(
  () => ({
    teamId: effectiveTeamId.value,
    queryKey: activeTimerQueryKey.value,
  }),
  (next, previous) => {
    if (previous?.teamId) {
      agencyTimeTrackingStore.unregisterActiveTimerQuery(previous.queryKey);
    }

    if (!next.teamId) {
      return;
    }

    agencyTimeTrackingStore.registerActiveTimerQuery({
      teamId: next.teamId,
      queryKey: next.queryKey,
    });
  },
  { immediate: true },
);

const elapsedSeconds = computed(() => {
  if (!activeTimer.value) {
    return 0;
  }
  const startedAt = new Date(activeTimer.value.startedAt).getTime();
  if (Number.isNaN(startedAt)) {
    return 0;
  }
  return Math.max(0, Math.floor((now.value - startedAt) / 1_000));
});

const canStartTimer = computed(() =>
  Boolean(
    effectiveTeamId.value &&
    selectedTask.value &&
    selectedProject.value &&
    selectedTagIds.value.length > 0 &&
    !activeTimer.value,
  ),
);
const canStopTimer = computed(() => Boolean(activeTimer.value && selectedTagIds.value.length > 0));
const timerValidationHint = computed(() => {
  if (activeTimer.value ? canStopTimer.value : canStartTimer.value) {
    return "";
  }

  const missingRequirements: string[] = [];

  if (!activeTimer.value && !selectedTask.value) {
    missingRequirements.push("a task");
  }

  if (selectedTagIds.value.length === 0) {
    missingRequirements.push("at least one tag");
  }

  if (missingRequirements.length === 0) {
    return "";
  }

  return `Select ${missingRequirements.join(" and ")} to ${activeTimer.value ? "stop and save" : "start"} this timer.`;
});

const trackerBusy = computed(() => isTimerMutationPending.value);

const discardMenuItems = computed(() => [
  [
    {
      label: "Discard timer",
      icon: "i-lucide-trash-2",
      color: "error" as const,
      onSelect: () => {
        void discardTimer();
      },
    },
  ],
]);

onBeforeUnmount(() => {
  agencyTimeTrackingStore.unregisterActiveTimerQuery(activeTimerQueryKey.value);
});

async function startTimer() {
  const teamId = effectiveTeamId.value;
  const project = selectedProject.value;
  const task = selectedTask.value;

  if (!teamId || !project || !task) {
    return;
  }

  await agencyTimeTrackingStore.startTimer({
    teamId,
    project,
    task,
    tagIds: [...selectedTagIds.value],
    selectedTags: [...selectedTags.value],
    description: timerDescription.value,
    linkUrl: timerLinkUrl.value,
  });
}

async function stopTimer() {
  const teamId = effectiveTeamId.value;

  if (!teamId || !activeTimer.value || !canStopTimer.value) {
    return;
  }

  await agencyTimeTrackingStore.stopTimer({
    teamId,
    activeTimer: activeTimer.value,
    tagIds: [...selectedTagIds.value],
    selectedTags: [...selectedTags.value],
    description: timerDescription.value,
    linkUrl: timerLinkUrl.value,
  });
}

async function discardTimer() {
  if (!effectiveTeamId.value) {
    return;
  }

  await agencyTimeTrackingStore.stopTimer({
    teamId: effectiveTeamId.value,
    activeTimer: activeTimer.value,
    tagIds: [...selectedTagIds.value],
    selectedTags: [...selectedTags.value],
    description: timerDescription.value,
    linkUrl: timerLinkUrl.value,
    discard: true,
  });
}

function toggleTag(tagId: string) {
  if (!effectiveTeamId.value || trackerBusy.value) {
    return;
  }

  agencyTimeTrackingStore.toggleTrackerTag(effectiveTeamId.value, tagId);
}
</script>

<template>
  <div class="space-y-2">
    <div class="flex flex-wrap items-center gap-2">
      <UInput
        v-model="timerDescription"
        placeholder="What are you working on?"
        size="sm"
        class="min-w-0 flex-1"
        :disabled="trackerBusy || !effectiveTeamId"
      />

      <AgencyTaskChooser
        v-model="selectedTaskId"
        :projects="projects"
        :tasks="tasks"
        :placeholder="!effectiveTeamId ? 'Team first' : 'Task'"
        class="w-64 shrink-0 max-sm:w-full"
        :loading="projectsQuery.isPending.value || tasksQuery.isPending.value"
        :disabled="
          !effectiveTeamId ||
          projectsQuery.isPending.value ||
          tasksQuery.isPending.value ||
          Boolean(activeTimer)
        "
      />

      <UPopover :content="{ align: 'end' }">
        <UButton
          icon="i-lucide-tag"
          size="xs"
          variant="ghost"
          :color="selectedTagIds.length > 0 ? 'primary' : 'neutral'"
          :disabled="trackerBusy || !effectiveTeamId || tagsQuery.isPending.value"
          aria-label="Select timer tags"
        />

        <template #content>
          <div class="w-64 space-y-2 p-2">
            <UInput
              v-model="tagSearch"
              icon="i-lucide-search"
              placeholder="Search tags"
              size="xs"
              :disabled="tags.length === 0"
            />

            <div class="flex max-h-52 flex-wrap gap-1 overflow-y-auto">
              <UButton
                v-for="tag in filteredTags"
                :key="tag.id"
                :variant="selectedTagIds.includes(tag.id) ? 'soft' : 'ghost'"
                :color="selectedTagIds.includes(tag.id) ? 'primary' : 'neutral'"
                size="xs"
                class="rounded-full"
                @click="toggleTag(tag.id)"
              >
                {{ tag.name }}
              </UButton>

              <div v-if="tags.length === 0" class="px-1 py-2 text-xs text-muted">
                No tags yet. Add tags in Agency settings.
              </div>
              <div v-else-if="filteredTags.length === 0" class="px-1 py-2 text-xs text-muted">
                No matching tags.
              </div>
            </div>
          </div>
        </template>
      </UPopover>

      <div class="shrink-0">
        <UPopover :content="{ align: 'end' }">
          <UButton
            icon="i-lucide-link"
            size="xs"
            variant="ghost"
            :color="hasValidLinkUrl ? 'primary' : 'neutral'"
            :disabled="trackerBusy || !effectiveTeamId"
          />

          <template #content>
            <div class="w-72 space-y-2 p-2">
              <UInput
                v-model="timerLinkUrl"
                icon="i-lucide-link"
                placeholder="Paste a task, ticket, or brief URL"
                size="xs"
              />

              <div class="flex items-center justify-between gap-2">
                <p v-if="linkUrlState.error" class="text-[11px] text-error">
                  {{ linkUrlState.error }}
                </p>
                <p v-else-if="hasValidLinkUrl" class="truncate text-[11px] text-muted">
                  {{ linkUrlState.normalizedUrl }}
                </p>
                <span v-else class="text-[11px] text-muted">
                  Link this entry to a task or brief.
                </span>

                <UButton
                  label="Clear"
                  color="neutral"
                  variant="ghost"
                  size="xs"
                  :disabled="!timerLinkUrl"
                  @click="timerLinkUrl = ''"
                />
              </div>
            </div>
          </template>
        </UPopover>
      </div>

      <UButton
        :label="activeTimer ? formatDuration(elapsedSeconds) : 'Start'"
        :color="activeTimer ? 'warning' : 'primary'"
        size="md"
        class="min-w-28 shrink-0 font-mono tabular-nums font-bold"
        :disabled="activeTimer ? !canStopTimer : !canStartTimer"
        :loading="trackerBusy"
        @click="activeTimer ? stopTimer() : startTimer()"
      />

      <UDropdownMenu v-if="activeTimer" :items="discardMenuItems" :content="{ align: 'end' }">
        <UButton icon="i-lucide-more-vertical" color="neutral" variant="ghost" size="sm" />
      </UDropdownMenu>
    </div>

    <div
      v-if="selectedTags.length > 0 || hasValidLinkUrl"
      class="flex flex-wrap items-center gap-1.5"
    >
      <a
        v-if="linkUrlState.normalizedUrl"
        :href="linkUrlState.normalizedUrl"
        target="_blank"
        rel="noreferrer"
        class="inline-flex min-w-0 max-w-full items-center gap-1 rounded-full border border-primary/20 bg-primary/10 px-2 py-1 text-xs text-primary transition hover:border-primary/40 hover:bg-primary/15"
      >
        <UIcon name="i-lucide-link" class="size-3 shrink-0" />
        <span class="truncate">
          {{ linkUrlDisplayLabel }}
        </span>
      </a>

      <UBadge
        v-for="tag in selectedTags"
        :key="tag.id"
        color="primary"
        variant="soft"
        class="rounded-full"
      >
        {{ tag.name }}
      </UBadge>
    </div>

    <p v-if="timerValidationHint" class="text-xs text-warning">
      {{ timerValidationHint }}
    </p>
  </div>
</template>
