// apps/web/src/components/agency/agency-task-media-player.tsx
type AgencyTaskMediaPlayerProps = {
  src: string | null | undefined;
  mimeType: string;
  fileName?: string;
  compact?: boolean;
};

function isHlsSource(src: string, mimeType: string): boolean {
  const normalizedSource = src.toLowerCase().split(/[?#]/, 1)[0] ?? "";
  const normalizedMimeType = mimeType.toLowerCase();

  return (
    normalizedSource.endsWith(".m3u8") ||
    normalizedMimeType === "application/vnd.apple.mpegurl" ||
    normalizedMimeType === "application/x-mpegurl"
  );
}

export function AgencyTaskMediaPlayer({
  src,
  mimeType,
  fileName,
  compact = false,
}: AgencyTaskMediaPlayerProps) {
  const source = src ?? "";
  const label = fileName ?? "Task attachment";

  if (!source) {
    return null;
  }

  const hls = isHlsSource(source, mimeType);
  const isAudio = mimeType.startsWith("audio/") && !hls;
  const isVideo = mimeType.startsWith("video/") || hls;

  return (
    <div className={["agency-task-media-player w-full", compact ? "is-compact" : ""].join(" ")}>
      {isAudio ? (
        <audio
          src={source}
          aria-label={label}
          preload="metadata"
          controls
          className="w-full max-w-sm"
        />
      ) : isVideo ? (
        <video
          src={source}
          aria-label={label}
          preload="metadata"
          playsInline
          controls
          className="w-full max-w-xl rounded-lg"
        />
      ) : null}
    </div>
  );
}

// apps/web/app/components/agency/AgencyTaskMediaPlayer.vue
<script setup lang="ts">
const props = defineProps<{
  src: string | null | undefined;
  mimeType: string;
  fileName?: string;
  compact?: boolean;
}>();

const source = computed(() => props.src ?? "");
const label = computed(() => props.fileName ?? "Task attachment");
const isHls = computed(() => {
  const normalizedSource = source.value.toLowerCase().split(/[?#]/, 1)[0] ?? "";
  const normalizedMimeType = props.mimeType.toLowerCase();

  return (
    normalizedSource.endsWith(".m3u8") ||
    normalizedMimeType === "application/vnd.apple.mpegurl" ||
    normalizedMimeType === "application/x-mpegurl"
  );
});
const isAudio = computed(() => props.mimeType.startsWith("audio/") && !isHls.value);
const isVideo = computed(() => props.mimeType.startsWith("video/") || isHls.value);
</script>

<template>
  <div v-if="source" class="agency-task-media-player" :class="{ 'is-compact': compact }">
    <audio-player v-if="isAudio">
      <audio-skin>
        <audio slot="media" :src="source" :aria-label="label" preload="metadata" />
      </audio-skin>
    </audio-player>

    <video-player v-else-if="isVideo">
      <video-skin>
        <hls-video
          v-if="isHls"
          slot="media"
          :src="source"
          :aria-label="label"
          preload="metadata"
          playsinline
        />
        <video
          v-else
          slot="media"
          :src="source"
          :aria-label="label"
          preload="metadata"
          playsinline
        />
      </video-skin>
    </video-player>
  </div>
</template>
