// apps/web/src/components/agency/agency-settings-surface.tsx
import { useEffect } from "react";
import { useSearchParams } from "react-router-dom";

import { AgencySettingsColorsPane } from "@/components/agency/settings/agency-settings-colors-pane";
import { AgencySettingsIntegrationsPane } from "@/components/agency/settings/agency-settings-integrations-pane";
import { AgencySettingsRatesPane } from "@/components/agency/settings/agency-settings-rates-pane";
import { AgencySettingsTagsPane } from "@/components/agency/settings/agency-settings-tags-pane";
import { AgencySettingsTenurePane } from "@/components/agency/settings/agency-settings-tenure-pane";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import {
  AGENCY_SETTINGS_PANES,
  isAgencySettingsPaneId,
  type AgencySettingsPaneId,
} from "@/lib/agency-settings-sections";
import { LucideIcon } from "@/lib/lucide-icon";

type AgencySettingsSurfaceProps = {
  teamId: string;
};

export function AgencySettingsSurface({ teamId }: AgencySettingsSurfaceProps) {
  const [searchParams, setSearchParams] = useSearchParams();

  const paneFromRoute: AgencySettingsPaneId = isAgencySettingsPaneId(searchParams.get("pane"))
    ? (searchParams.get("pane") as AgencySettingsPaneId)
    : "tags";

  const activePane = paneFromRoute;

  useEffect(() => {
    const section = searchParams.get("section");
    if (section === "settings" && !isAgencySettingsPaneId(searchParams.get("pane"))) {
      const next = new URLSearchParams(searchParams);
      next.set("pane", "tags");
      setSearchParams(next, { replace: true });
      return;
    }
    if (section !== "settings" && searchParams.get("pane")) {
      const next = new URLSearchParams(searchParams);
      next.delete("pane");
      setSearchParams(next, { replace: true });
    }
  }, [searchParams, setSearchParams]);

  function setActivePane(nextPane: AgencySettingsPaneId) {
    const next = new URLSearchParams(searchParams);
    next.set("pane", nextPane);
    setSearchParams(next, { replace: true });
  }

  return (
    <div className="flex min-h-0 flex-1 flex-col gap-4">
      <Tabs
        value={activePane}
        onValueChange={(value) => {
          if (isAgencySettingsPaneId(value)) setActivePane(value);
        }}
      >
        <TabsList>
          {AGENCY_SETTINGS_PANES.map((pane) => (
            <TabsTrigger key={pane.id} value={pane.id}>
              <LucideIcon name={pane.icon} className="size-3.5" />
              <span>{pane.label}</span>
              {pane.status === "soon" ? (
                <Badge variant="secondary" className="ml-1 rounded-full px-1.5 py-0 text-[10px]">
                  Soon
                </Badge>
              ) : null}
            </TabsTrigger>
          ))}
        </TabsList>

        <div className="min-h-0 flex-1 pb-4">
          <TabsContent value="tags">
            <AgencySettingsTagsPane teamId={teamId} active={activePane === "tags"} />
          </TabsContent>
          <TabsContent value="rates">
            <AgencySettingsRatesPane teamId={teamId} active={activePane === "rates"} />
          </TabsContent>
          <TabsContent value="tenure">
            <AgencySettingsTenurePane teamId={teamId} active={activePane === "tenure"} />
          </TabsContent>
          <TabsContent value="integrations">
            <AgencySettingsIntegrationsPane teamId={teamId} active={activePane === "integrations"} />
          </TabsContent>
          <TabsContent value="colors">
            <AgencySettingsColorsPane />
          </TabsContent>
        </div>
      </Tabs>
    </div>
  );
}

// apps/web/app/components/agency/AgencySettingsSurface.vue
<script setup lang="ts">
import AgencySettingsColorsPane from "~/components/agency/settings/AgencySettingsColorsPane.vue";
import AgencySettingsIntegrationsPane from "~/components/agency/settings/AgencySettingsIntegrationsPane.vue";
import AgencySettingsRatesPane from "~/components/agency/settings/AgencySettingsRatesPane.vue";
import AgencySettingsTagsPane from "~/components/agency/settings/AgencySettingsTagsPane.vue";
import AgencySettingsTenurePane from "~/components/agency/settings/AgencySettingsTenurePane.vue";
import {
  AGENCY_SETTINGS_PANES,
  agencySettingsPaneIndex,
  isAgencySettingsPaneId,
  type AgencySettingsPaneId,
} from "~/components/agency/agency-settings-sections";

defineProps<{
  teamId: string;
}>();

const route = useRoute();
const router = useRouter();

const paneFromRoute = computed((): AgencySettingsPaneId => {
  const queryPane = route.query.pane;
  return isAgencySettingsPaneId(queryPane) ? queryPane : "tags";
});

const selectedTabIndex = ref(agencySettingsPaneIndex(paneFromRoute.value));

const settingsTabs = computed(() =>
  AGENCY_SETTINGS_PANES.map((pane) => ({
    label: pane.label,
    icon: pane.icon,
    badge: pane.status === "soon" ? "Soon" : undefined,
  })),
);

const activePane = computed(
  () => AGENCY_SETTINGS_PANES[selectedTabIndex.value]?.id ?? "tags",
);

watch(paneFromRoute, (next) => {
  const index = agencySettingsPaneIndex(next);
  if (selectedTabIndex.value !== index) {
    selectedTabIndex.value = index;
  }
});

watch(selectedTabIndex, (nextIndex) => {
  const nextPane = AGENCY_SETTINGS_PANES[nextIndex]?.id ?? "tags";
  if (route.query.pane === nextPane) return;
  router.replace({ query: { ...route.query, pane: nextPane } });
});

watch(
  () => route.query.section,
  (section) => {
    if (section === "settings" && !isAgencySettingsPaneId(route.query.pane)) {
      router.replace({ query: { ...route.query, pane: "tags" } });
      return;
    }
    if (section !== "settings" && route.query.pane) {
      const next = { ...route.query };
      delete next.pane;
      router.replace({ query: next });
    }
  },
  { immediate: true },
);
</script>

<template>
  <div class="flex min-h-0 flex-1 flex-col gap-4">
    <UTabs v-model="selectedTabIndex" :items="settingsTabs" variant="pill" size="sm" />

    <div class="min-h-0 flex-1 pb-4">
      <AgencySettingsTagsPane
        v-if="activePane === 'tags'"
        :team-id="teamId"
        :active="activePane === 'tags'"
      />
      <AgencySettingsRatesPane
        v-else-if="activePane === 'rates'"
        :team-id="teamId"
        :active="activePane === 'rates'"
      />
      <AgencySettingsTenurePane
        v-else-if="activePane === 'tenure'"
        :team-id="teamId"
        :active="activePane === 'tenure'"
      />
      <AgencySettingsIntegrationsPane
        v-else-if="activePane === 'integrations'"
        :team-id="teamId"
        :active="activePane === 'integrations'"
      />
      <AgencySettingsColorsPane v-else-if="activePane === 'colors'" />
    </div>
  </div>
</template>
