// apps/web/src/components/agency/settings/agency-settings-tenure-pane.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

import {
  AgencySettingsTenureMemberDetail,
  type TenureExemptionDraft,
  type TenureProfileDraft,
} from "@/components/agency/settings/agency-settings-tenure-member-detail";
import {
  AgencySettingsTenurePolicy,
  type TenurePolicyDraft,
} from "@/components/agency/settings/agency-settings-tenure-policy";
import { AgencySettingsTenureRoster } from "@/components/agency/settings/agency-settings-tenure-roster";
import { Skeleton } from "@/components/ui/skeleton";
import { orpc } from "@/lib/orpc";
import type { FiscalMonth } from "@/lib/tenure-utils";
import { withAgencyLiveQueryOptions } from "@/lib/utils/agency-query-options";
import { agencySectionTitleClass } from "@/lib/utils/agency-ui";
import { getErrorMessage } from "@/lib/utils/get-error-message";

type AgencySettingsTenurePaneProps = {
  teamId: string;
  active: boolean;
};

export function AgencySettingsTenurePane({ teamId, active }: AgencySettingsTenurePaneProps) {
  const queryClient = useQueryClient();

  const teamQuery = useQuery({
    ...orpc.team.get.queryOptions({ input: { teamId } }),
    enabled: Boolean(teamId) && active,
  });

  const isOwner = teamQuery.data?.role === "owner";

  const policyQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.policy.get.queryOptions({ input: { teamId } }),
      enabled: Boolean(teamId) && active,
    }),
  );

  const summaryQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.summary.list.queryOptions({ input: { teamId } }),
      enabled: Boolean(teamId) && active,
    }),
  );

  const exemptionsQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.exemptions.list.queryOptions({ input: { teamId } }),
      enabled: Boolean(teamId) && active,
    }),
  );

  const policy = policyQuery.data?.policy ?? null;
  const members = summaryQuery.data?.items ?? [];
  const policyEnabled = summaryQuery.data?.policyEnabled ?? false;
  const exemptions = exemptionsQuery.data?.items ?? [];

  const [policyDraft, setPolicyDraft] = useState<TenurePolicyDraft>({
    fiscalYearStartMonth: 1,
    fiscalYearStartDay: "1",
    quarterlyMinHours: "525",
    penaltyMonths: "6",
    internDurationMonths: "4",
    internDurationWeeks: "0",
    policyEffectiveFrom: new Date().toISOString().slice(0, 10),
    enabled: false,
  });

  useEffect(() => {
    if (!policy) return;
    setPolicyDraft({
      fiscalYearStartMonth: policy.fiscalYearStartMonth as FiscalMonth,
      fiscalYearStartDay: String(policy.fiscalYearStartDay),
      quarterlyMinHours: String(policy.quarterlyMinHours),
      penaltyMonths: String(policy.penaltyMonths),
      internDurationMonths: String(policy.internDurationMonths),
      internDurationWeeks: String(policy.internDurationWeeks),
      policyEffectiveFrom: policy.policyEffectiveFrom.slice(0, 10),
      enabled: policy.enabled,
    });
  }, [policy]);

  const savePolicyMutation = useMutation(orpc.agencyOps.tenure.policy.upsert.mutationOptions());
  const saveProfileMutation = useMutation(orpc.agencyOps.tenure.profiles.upsert.mutationOptions());
  const saveExemptionMutation = useMutation(orpc.agencyOps.tenure.exemptions.upsert.mutationOptions());
  const deleteExemptionMutation = useMutation(
    orpc.agencyOps.tenure.exemptions.delete.mutationOptions(),
  );

  const [selectedUserId, setSelectedUserId] = useState<string | null>(null);

  const memberDetailQuery = useQuery(
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.member.get.queryOptions({
        input: { teamId, userId: selectedUserId ?? "" },
      }),
      enabled: Boolean(teamId && selectedUserId && active),
    }),
  );

  const memberDetail = memberDetailQuery.data?.member ?? null;

  const selectedMemberName = useMemo(() => {
    if (!selectedUserId) return "";
    return members.find((member) => member.userId === selectedUserId)?.userName ?? "Member";
  }, [members, selectedUserId]);

  const [profileDraft, setProfileDraft] = useState<TenureProfileDraft>({
    internStart: "",
    internEnd: "",
    internCountsTowardTenure: false,
    internExemptFromQuarterMin: true,
    notes: "",
  });

  useEffect(() => {
    if (!memberDetail) return;
    setProfileDraft({
      internStart: memberDetail.internStart?.slice(0, 10) ?? "",
      internEnd: memberDetail.internEnd?.slice(0, 10) ?? "",
      internCountsTowardTenure: memberDetail.internCountsTowardTenure,
      internExemptFromQuarterMin: memberDetail.internExemptFromQuarterMin,
      notes: memberDetail.notes ?? "",
    });
  }, [memberDetail]);

  const [exemptionDraft, setExemptionDraft] = useState<TenureExemptionDraft>({
    type: "member_waiver",
    fiscalYear: String(new Date().getUTCFullYear()),
    fiscalQuarter: "1",
    userId: "",
    reducedMinHours: "",
    frozenMonth: 1,
    reason: "",
  });

  async function invalidateTenureQueries() {
    if (!teamId) return;
    await Promise.all([
      queryClient.invalidateQueries({
        queryKey: orpc.agencyOps.tenure.policy.get.key({ input: { teamId } }),
      }),
      queryClient.invalidateQueries({
        queryKey: orpc.agencyOps.tenure.summary.list.key({ input: { teamId } }),
      }),
      queryClient.invalidateQueries({
        queryKey: orpc.agencyOps.tenure.exemptions.list.key({ input: { teamId } }),
      }),
      queryClient.invalidateQueries({
        queryKey: orpc.agencyOps.tenure.profiles.list.key({ input: { teamId } }),
      }),
    ]);
    if (selectedUserId) {
      await queryClient.invalidateQueries({
        queryKey: orpc.agencyOps.tenure.member.get.key({
          input: { teamId, userId: selectedUserId },
        }),
      });
    }
  }

  async function savePolicy() {
    if (!teamId || !isOwner) return;
    try {
      await savePolicyMutation.mutateAsync({
        teamId,
        fiscalYearStartMonth: policyDraft.fiscalYearStartMonth,
        fiscalYearStartDay: Number.parseInt(policyDraft.fiscalYearStartDay, 10),
        quarterlyMinHours: Number.parseInt(policyDraft.quarterlyMinHours, 10),
        penaltyMonths: Number.parseInt(policyDraft.penaltyMonths, 10),
        internDurationMonths: Number.parseInt(policyDraft.internDurationMonths, 10),
        internDurationWeeks: Number.parseInt(policyDraft.internDurationWeeks, 10),
        policyEffectiveFrom: new Date(policyDraft.policyEffectiveFrom).toISOString(),
        enabled: policyDraft.enabled,
      });
      await invalidateTenureQueries();
      toast.success("Tenure policy saved");
    } catch (error) {
      toast.error("Couldn't save policy", {
        description: getErrorMessage(error, "Try again."),
      });
    }
  }

  const memberExemptions = useMemo(() => {
    if (!selectedUserId) return [];
    return exemptions.filter(
      (exemption) =>
        exemption.type === "team_holiday" || exemption.userId === selectedUserId,
    );
  }, [exemptions, selectedUserId]);

  async function saveProfile() {
    if (!teamId || !isOwner || !selectedUserId) return;
    try {
      await saveProfileMutation.mutateAsync({
        teamId,
        userId: selectedUserId,
        internStart: profileDraft.internStart
          ? new Date(profileDraft.internStart).toISOString()
          : null,
        internEnd: profileDraft.internEnd ? new Date(profileDraft.internEnd).toISOString() : null,
        internCountsTowardTenure: profileDraft.internCountsTowardTenure,
        internExemptFromQuarterMin: profileDraft.internExemptFromQuarterMin,
        notes: profileDraft.notes || null,
      });
      await invalidateTenureQueries();
      toast.success("Member profile saved");
    } catch (error) {
      toast.error("Couldn't save profile", {
        description: getErrorMessage(error, "Try again."),
      });
    }
  }

  async function addExemption() {
    if (!teamId || !isOwner) return;
    try {
      const type = exemptionDraft.type;
      await saveExemptionMutation.mutateAsync({
        teamId,
        type,
        fiscalYear: Number.parseInt(exemptionDraft.fiscalYear, 10),
        fiscalQuarter: Number.parseInt(exemptionDraft.fiscalQuarter, 10) as 1 | 2 | 3 | 4,
        userId: type === "team_holiday" ? null : exemptionDraft.userId || selectedUserId,
        reducedMinHours:
          type === "member_reduced_min"
            ? Number.parseInt(exemptionDraft.reducedMinHours, 10)
            : null,
        frozenMonth: type === "member_frozen_month" ? exemptionDraft.frozenMonth : null,
        reason: exemptionDraft.reason || null,
      });
      await invalidateTenureQueries();
      toast.success("Exemption saved");
    } catch (error) {
      toast.error("Couldn't save exemption", {
        description: getErrorMessage(error, "Try again."),
      });
    }
  }

  async function removeExemption(exemptionId: string) {
    if (!teamId || !isOwner) return;
    try {
      await deleteExemptionMutation.mutateAsync({ teamId, exemptionId });
      await invalidateTenureQueries();
      toast.success("Exemption removed");
    } catch (error) {
      toast.error("Couldn't remove exemption", {
        description: getErrorMessage(error, "Try again."),
      });
    }
  }

  const fiscalYearPreview = useMemo(() => {
    const month = policyDraft.fiscalYearStartMonth;
    const day = Number.parseInt(policyDraft.fiscalYearStartDay, 10) || 1;
    const year = new Date().getUTCFullYear();
    const start = new Date(Date.UTC(year, month - 1, day));
    const endExclusive = new Date(Date.UTC(year + 1, month - 1, day));
    endExclusive.setUTCDate(endExclusive.getUTCDate() - 1);
    const fmt = (date: Date) =>
      date.toLocaleDateString(undefined, {
        timeZone: "UTC",
        month: "numeric",
        day: "numeric",
        year: "numeric",
      });
    return `Example fiscal year: ${fmt(start)} – ${fmt(endExclusive)} (UTC).`;
  }, [policyDraft.fiscalYearStartDay, policyDraft.fiscalYearStartMonth]);

  const isLoading =
    policyQuery.isPending || summaryQuery.isPending || teamQuery.isPending;

  return (
    <div className="space-y-4">
      <div>
        <h2 className={agencySectionTitleClass}>Agency tenure and quarterly hour requirements</h2>
      </div>

      {isLoading ? (
        <div className="space-y-2">
          <Skeleton className="h-24 rounded-xl" />
          <Skeleton className="h-40 rounded-xl" />
        </div>
      ) : (
        <>
          <AgencySettingsTenurePolicy
            policyDraft={policyDraft}
            onPolicyDraftChange={setPolicyDraft}
            isOwner={isOwner}
            fiscalYearPreview={fiscalYearPreview}
            saving={savePolicyMutation.isPending}
            onSave={() => void savePolicy()}
          />

          {selectedUserId ? (
            <AgencySettingsTenureMemberDetail
              memberName={selectedMemberName}
              memberDetail={memberDetail}
              loading={memberDetailQuery.isPending}
              isOwner={isOwner}
              exemptions={memberExemptions}
              profileDraft={profileDraft}
              onProfileDraftChange={setProfileDraft}
              exemptionDraft={exemptionDraft}
              onExemptionDraftChange={setExemptionDraft}
              savingProfile={saveProfileMutation.isPending}
              savingExemption={saveExemptionMutation.isPending}
              onClose={() => setSelectedUserId(null)}
              onSaveProfile={() => void saveProfile()}
              onAddExemption={() => void addExemption()}
              onRemoveExemption={(exemptionId) => void removeExemption(exemptionId)}
            />
          ) : (
            <AgencySettingsTenureRoster
              members={members}
              policyEnabled={policyEnabled}
              onSelect={setSelectedUserId}
            />
          )}
        </>
      )}
    </div>
  );
}

// apps/web/app/components/agency/settings/AgencySettingsTenurePane.vue
<script setup lang="ts">
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";

import AgencySettingsTenureMemberDetail from "~/components/agency/settings/AgencySettingsTenureMemberDetail.vue";
import AgencySettingsTenurePolicy from "~/components/agency/settings/AgencySettingsTenurePolicy.vue";
import AgencySettingsTenureRoster from "~/components/agency/settings/AgencySettingsTenureRoster.vue";
import { getErrorMessage } from "~/utils/get-error-message";
import { withAgencyLiveQueryOptions } from "~/utils/agency-query-options";
import { agencySectionTitleClass } from "~/utils/agency-ui";

import type { FiscalMonth } from "./tenure-utils";

const props = defineProps<{
  teamId: string;
  active: boolean;
}>();

const orpc = useOrpc();
const toast = useToast();
const queryClient = useQueryClient();

const teamId = computed(() => props.teamId);

const teamQuery = useQuery(
  computed(() => ({
    ...orpc.team.get.queryOptions({ input: { teamId: teamId.value } }),
    enabled: Boolean(teamId.value) && props.active,
  })),
);

const isOwner = computed(() => teamQuery.data.value?.role === "owner");

const policyQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.policy.get.queryOptions({ input: { teamId: teamId.value } }),
      enabled: Boolean(teamId.value) && props.active,
    }),
  ),
);

const summaryQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.summary.list.queryOptions({ input: { teamId: teamId.value } }),
      enabled: Boolean(teamId.value) && props.active,
    }),
  ),
);

const exemptionsQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.exemptions.list.queryOptions({ input: { teamId: teamId.value } }),
      enabled: Boolean(teamId.value) && props.active,
    }),
  ),
);

const policy = computed(() => policyQuery.data.value?.policy ?? null);
const members = computed(() => summaryQuery.data.value?.items ?? []);
const policyEnabled = computed(() => summaryQuery.data.value?.policyEnabled ?? false);
const exemptions = computed(() => exemptionsQuery.data.value?.items ?? []);

const policyDraft = ref({
  fiscalYearStartMonth: 1 as FiscalMonth,
  fiscalYearStartDay: "1",
  quarterlyMinHours: "525",
  penaltyMonths: "6",
  internDurationMonths: "4",
  internDurationWeeks: "0",
  policyEffectiveFrom: new Date().toISOString().slice(0, 10),
  enabled: false,
});

watch(
  policy,
  (next) => {
    if (!next) return;
    policyDraft.value = {
      fiscalYearStartMonth: next.fiscalYearStartMonth as FiscalMonth,
      fiscalYearStartDay: String(next.fiscalYearStartDay),
      quarterlyMinHours: String(next.quarterlyMinHours),
      penaltyMonths: String(next.penaltyMonths),
      internDurationMonths: String(next.internDurationMonths),
      internDurationWeeks: String(next.internDurationWeeks),
      policyEffectiveFrom: next.policyEffectiveFrom.slice(0, 10),
      enabled: next.enabled,
    };
  },
  { immediate: true },
);

const savePolicyMutation = useMutation(orpc.agencyOps.tenure.policy.upsert.mutationOptions());
const saveProfileMutation = useMutation(orpc.agencyOps.tenure.profiles.upsert.mutationOptions());
const saveExemptionMutation = useMutation(
  orpc.agencyOps.tenure.exemptions.upsert.mutationOptions(),
);
const deleteExemptionMutation = useMutation(
  orpc.agencyOps.tenure.exemptions.delete.mutationOptions(),
);

const selectedUserId = ref<string | null>(null);

const memberDetailQuery = useQuery(
  computed(() =>
    withAgencyLiveQueryOptions({
      ...orpc.agencyOps.tenure.member.get.queryOptions({
        input: { teamId: teamId.value, userId: selectedUserId.value ?? "" },
      }),
      enabled: Boolean(teamId.value && selectedUserId.value && props.active),
    }),
  ),
);

const memberDetail = computed(() => memberDetailQuery.data.value?.member ?? null);

const selectedMemberName = computed(() => {
  if (!selectedUserId.value) return "";
  return members.value.find((member) => member.userId === selectedUserId.value)?.userName ?? "Member";
});

const profileDraft = ref({
  internStart: "",
  internEnd: "",
  internCountsTowardTenure: false,
  internExemptFromQuarterMin: true,
  notes: "",
});

watch(memberDetail, (next) => {
  if (!next) return;
  profileDraft.value = {
    internStart: next.internStart?.slice(0, 10) ?? "",
    internEnd: next.internEnd?.slice(0, 10) ?? "",
    internCountsTowardTenure: next.internCountsTowardTenure,
    internExemptFromQuarterMin: next.internExemptFromQuarterMin,
    notes: next.notes ?? "",
  };
});

const exemptionDraft = ref({
  type: "member_waiver" as
    | "team_holiday"
    | "member_waiver"
    | "member_reduced_min"
    | "member_frozen_month",
  fiscalYear: String(new Date().getUTCFullYear()),
  fiscalQuarter: "1" as "1" | "2" | "3" | "4",
  userId: "",
  reducedMinHours: "",
  frozenMonth: 1 as FiscalMonth,
  reason: "",
});

async function invalidateTenureQueries() {
  if (!teamId.value) return;
  await Promise.all([
    queryClient.invalidateQueries({
      queryKey: orpc.agencyOps.tenure.policy.get.key({ input: { teamId: teamId.value } }),
    }),
    queryClient.invalidateQueries({
      queryKey: orpc.agencyOps.tenure.summary.list.key({ input: { teamId: teamId.value } }),
    }),
    queryClient.invalidateQueries({
      queryKey: orpc.agencyOps.tenure.exemptions.list.key({ input: { teamId: teamId.value } }),
    }),
    queryClient.invalidateQueries({
      queryKey: orpc.agencyOps.tenure.profiles.list.key({ input: { teamId: teamId.value } }),
    }),
  ]);
  if (selectedUserId.value) {
    await queryClient.invalidateQueries({
      queryKey: orpc.agencyOps.tenure.member.get.key({
        input: { teamId: teamId.value, userId: selectedUserId.value },
      }),
    });
  }
}

async function savePolicy() {
  if (!teamId.value || !isOwner.value) return;
  try {
    await savePolicyMutation.mutateAsync({
      teamId: teamId.value,
      fiscalYearStartMonth: policyDraft.value.fiscalYearStartMonth,
      fiscalYearStartDay: Number.parseInt(policyDraft.value.fiscalYearStartDay, 10),
      quarterlyMinHours: Number.parseInt(policyDraft.value.quarterlyMinHours, 10),
      penaltyMonths: Number.parseInt(policyDraft.value.penaltyMonths, 10),
      internDurationMonths: Number.parseInt(policyDraft.value.internDurationMonths, 10),
      internDurationWeeks: Number.parseInt(policyDraft.value.internDurationWeeks, 10),
      policyEffectiveFrom: new Date(policyDraft.value.policyEffectiveFrom).toISOString(),
      enabled: policyDraft.value.enabled,
    });
    await invalidateTenureQueries();
    toast.add({ title: "Tenure policy saved", color: "success" });
  } catch (error) {
    toast.add({
      title: "Couldn't save policy",
      description: getErrorMessage(error, "Try again."),
      color: "error",
    });
  }
}

function selectMember(userId: string) {
  selectedUserId.value = userId;
}

const memberExemptions = computed(() => {
  if (!selectedUserId.value) return [];
  return exemptions.value.filter(
    (exemption) =>
      exemption.type === "team_holiday" || exemption.userId === selectedUserId.value,
  );
});

function closeMemberDetail() {
  selectedUserId.value = null;
}

async function saveProfile() {
  if (!teamId.value || !isOwner.value || !selectedUserId.value) return;
  try {
    await saveProfileMutation.mutateAsync({
      teamId: teamId.value,
      userId: selectedUserId.value,
      internStart: profileDraft.value.internStart
        ? new Date(profileDraft.value.internStart).toISOString()
        : null,
      internEnd: profileDraft.value.internEnd
        ? new Date(profileDraft.value.internEnd).toISOString()
        : null,
      internCountsTowardTenure: profileDraft.value.internCountsTowardTenure,
      internExemptFromQuarterMin: profileDraft.value.internExemptFromQuarterMin,
      notes: profileDraft.value.notes || null,
    });
    await invalidateTenureQueries();
    toast.add({ title: "Member profile saved", color: "success" });
  } catch (error) {
    toast.add({
      title: "Couldn't save profile",
      description: getErrorMessage(error, "Try again."),
      color: "error",
    });
  }
}

async function addExemption() {
  if (!teamId.value || !isOwner.value) return;
  try {
    const type = exemptionDraft.value.type;
    await saveExemptionMutation.mutateAsync({
      teamId: teamId.value,
      type,
      fiscalYear: Number.parseInt(exemptionDraft.value.fiscalYear, 10),
      fiscalQuarter: Number.parseInt(exemptionDraft.value.fiscalQuarter, 10) as 1 | 2 | 3 | 4,
      userId: type === "team_holiday" ? null : exemptionDraft.value.userId || selectedUserId.value,
      reducedMinHours:
        type === "member_reduced_min"
          ? Number.parseInt(exemptionDraft.value.reducedMinHours, 10)
          : null,
      frozenMonth:
        type === "member_frozen_month" ? exemptionDraft.value.frozenMonth : null,
      reason: exemptionDraft.value.reason || null,
    });
    await invalidateTenureQueries();
    toast.add({ title: "Exemption saved", color: "success" });
  } catch (error) {
    toast.add({
      title: "Couldn't save exemption",
      description: getErrorMessage(error, "Try again."),
      color: "error",
    });
  }
}

async function removeExemption(exemptionId: string) {
  if (!teamId.value || !isOwner.value) return;
  try {
    await deleteExemptionMutation.mutateAsync({ teamId: teamId.value, exemptionId });
    await invalidateTenureQueries();
    toast.add({ title: "Exemption removed", color: "success" });
  } catch (error) {
    toast.add({
      title: "Couldn't remove exemption",
      description: getErrorMessage(error, "Try again."),
      color: "error",
    });
  }
}

const fiscalYearPreview = computed(() => {
  const month = policyDraft.value.fiscalYearStartMonth;
  const day = Number.parseInt(policyDraft.value.fiscalYearStartDay, 10) || 1;
  const year = new Date().getUTCFullYear();
  const start = new Date(Date.UTC(year, month - 1, day));
  const endExclusive = new Date(Date.UTC(year + 1, month - 1, day));
  endExclusive.setUTCDate(endExclusive.getUTCDate() - 1);
  const fmt = (date: Date) =>
    date.toLocaleDateString(undefined, {
      timeZone: "UTC",
      month: "numeric",
      day: "numeric",
      year: "numeric",
    });
  return `Example fiscal year: ${fmt(start)} – ${fmt(endExclusive)} (UTC).`;
});

const isLoading = computed(
  () => policyQuery.isPending.value || summaryQuery.isPending.value || teamQuery.isPending.value,
);
</script>

<template>
  <div class="space-y-4">
    <div>
      <h2 :class="agencySectionTitleClass">Agency tenure and quarterly hour requirements</h2>
    </div>

    <div v-if="isLoading" class="space-y-2">
      <div class="h-24 animate-pulse rounded-xl bg-elevated/60" />
      <div class="h-40 animate-pulse rounded-xl bg-elevated/60" />
    </div>

    <template v-else>
      <AgencySettingsTenurePolicy
        v-model:policy-draft="policyDraft"
        :is-owner="isOwner"
        :fiscal-year-preview="fiscalYearPreview"
        :saving="savePolicyMutation.isPending.value"
        @save="savePolicy"
      />

      <AgencySettingsTenureMemberDetail
        v-if="selectedUserId"
        v-model:profile-draft="profileDraft"
        v-model:exemption-draft="exemptionDraft"
        :member-name="selectedMemberName"
        :member-detail="memberDetail"
        :loading="memberDetailQuery.isPending.value"
        :is-owner="isOwner"
        :exemptions="memberExemptions"
        :saving-profile="saveProfileMutation.isPending.value"
        :saving-exemption="saveExemptionMutation.isPending.value"
        @close="closeMemberDetail"
        @save-profile="saveProfile"
        @add-exemption="addExemption"
        @remove-exemption="removeExemption"
      />

      <AgencySettingsTenureRoster
        v-else
        :members="members"
        :policy-enabled="policyEnabled"
        @select="selectMember"
      />
    </template>
  </div>
</template>
