// apps/web/src/components/marketplace-item-card.tsx
import type { WorkspaceMarketplaceItem } from "@brainiac/workspace";
import { Box, Component, Download, HelpCircle, Layout, Plus } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { formatDateTime } from "@/lib/utils/format-date-time";
import {
  getMarketplacePayloadSummary,
  getMarketplacePayloadTypeLabel,
} from "@/lib/utils/workspace-marketplace";
import { cn } from "@/lib/utils";

function kindIcon(kind: WorkspaceMarketplaceItem["payload"]["kind"]) {
  switch (kind) {
    case "node":
      return Box;
    case "tab":
      return Layout;
    case "block":
      return Component;
    default:
      return HelpCircle;
  }
}

function kindBadgeVariant(kind: WorkspaceMarketplaceItem["payload"]["kind"]) {
  switch (kind) {
    case "node":
      return "default" as const;
    case "tab":
      return "success" as const;
    case "block":
      return "warning" as const;
    default:
      return "secondary" as const;
  }
}

function kindIconClass(kind: WorkspaceMarketplaceItem["payload"]["kind"]) {
  switch (kind) {
    case "node":
      return "bg-primary/10 text-primary";
    case "tab":
      return "bg-success/10 text-success";
    case "block":
      return "bg-warning/10 text-warning";
    default:
      return "bg-muted text-muted-foreground";
  }
}

function avatarInitials(name: string) {
  const parts = name.trim().split(/\s+/).filter(Boolean);
  if (parts.length === 0) return "?";
  if (parts.length === 1) return parts[0]!.slice(0, 2).toUpperCase();
  return `${parts[0]![0] ?? ""}${parts[1]![0] ?? ""}`.toUpperCase();
}

export function MarketplaceItemCard({
  item,
  loading = false,
  onInsert,
}: {
  item: WorkspaceMarketplaceItem;
  loading?: boolean;
  onInsert: (item: WorkspaceMarketplaceItem) => void;
}) {
  const kind = item.payload.kind;
  const Icon = kindIcon(kind);

  return (
    <Card className="group flex h-full flex-col transition-all hover:ring-2 hover:ring-primary/30">
      <CardHeader className="pb-4">
        <div className="flex items-start justify-between gap-3">
          <div className="flex min-w-0 items-center gap-2.5">
            <div className={cn("shrink-0 rounded-xl p-2", kindIconClass(kind))}>
              <Icon className="size-5" />
            </div>
            <div className="min-w-0">
              <h3 className="truncate leading-tight font-semibold text-highlighted">{item.title}</h3>
              <p className="mt-0.5 text-xs font-medium tracking-wider text-muted uppercase">
                {getMarketplacePayloadTypeLabel(item.payload)}
              </p>
            </div>
          </div>
          <Badge variant={kindBadgeVariant(kind)} className="shrink-0">
            {getMarketplacePayloadSummary(item.payload)}
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="flex flex-1 flex-col gap-4 pt-0">
        <p className="line-clamp-3 flex-1 text-sm text-muted">
          {item.summary || getMarketplacePayloadSummary(item.payload)}
        </p>

        <div className="flex items-center justify-between gap-3 pt-2">
          <div className="flex min-w-0 items-center gap-2">
            <span
              className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-[10px] font-bold text-muted-foreground ring-1 ring-muted/30"
              aria-hidden="true"
            >
              {avatarInitials(item.createdByName)}
            </span>
            <span className="truncate text-xs font-medium text-muted">{item.createdByName}</span>
          </div>

          <time
            dateTime={item.createdAt}
            className="text-[10px] tracking-tighter whitespace-nowrap text-muted-foreground/60 uppercase"
          >
            {formatDateTime(item.createdAt)}
          </time>
        </div>

        <Button
          variant="secondary"
          className="w-full group-hover:bg-primary group-hover:text-primary-foreground"
          disabled={loading}
          onClick={() => onInsert(item)}
        >
          {kind === "node" ? <Plus className="size-4" /> : <Download className="size-4" />}
          Add to Dashboard
        </Button>
      </CardContent>
    </Card>
  );
}

// apps/web/app/components/MarketplaceItemCard.vue
<script setup lang="ts">
import type { WorkspaceMarketplaceItem } from "@brainiac/workspace";
import {
  getMarketplacePayloadSummary,
  getMarketplacePayloadTypeLabel,
} from "~/utils/workspace-marketplace";

const props = defineProps<{
  item: WorkspaceMarketplaceItem;
  loading?: boolean;
}>();

defineEmits<{
  insert: [item: WorkspaceMarketplaceItem];
}>();

const kindIcon = computed(() => {
  switch (props.item.payload.kind) {
    case "node":
      return "i-lucide-box";
    case "tab":
      return "i-lucide-layout";
    case "block":
      return "i-lucide-component";
    default:
      return "i-lucide-help-circle";
  }
});

const kindColor = computed(() => {
  switch (props.item.payload.kind) {
    case "node":
      return "primary";
    case "tab":
      return "success";
    case "block":
      return "warning";
    default:
      return "neutral";
  }
});
</script>

<template>
  <UCard
    class="flex flex-col h-full transition-all hover:ring-2 hover:ring-primary/30 group"
    :ui="{
      body: 'flex-1 flex flex-col gap-4',
      footer: 'pt-0 border-none',
    }"
  >
    <template #header>
      <div class="flex items-start justify-between gap-3">
        <div class="flex items-center gap-2.5">
          <div
            class="p-2 rounded-xl bg-opacity-10 shrink-0"
            :class="[
              item.payload.kind === 'node' && 'bg-primary text-primary',
              item.payload.kind === 'tab' && 'bg-success text-success',
              item.payload.kind === 'block' && 'bg-warning text-warning',
            ]"
          >
            <UIcon :name="kindIcon" class="size-5" />
          </div>
          <div class="min-w-0">
            <h3 class="font-semibold text-highlighted truncate leading-tight">
              {{ item.title }}
            </h3>
            <p class="text-xs font-medium text-muted uppercase tracking-wider mt-0.5">
              {{ getMarketplacePayloadTypeLabel(item.payload) }}
            </p>
          </div>
        </div>
        <UBadge :color="kindColor" variant="subtle" size="sm" class="shrink-0">
          {{ getMarketplacePayloadSummary(item.payload) }}
        </UBadge>
      </div>
    </template>

    <div class="flex-1">
      <p class="text-sm text-muted line-clamp-3">
        {{ item.summary || getMarketplacePayloadSummary(item.payload) }}
      </p>
    </div>

    <div class="flex items-center justify-between gap-3 pt-2">
      <div class="flex items-center gap-2 min-w-0">
        <UAvatar :alt="item.createdByName" size="xs" class="shrink-0 ring-1 ring-muted/30" />
        <span class="text-xs text-muted truncate font-medium">
          {{ item.createdByName }}
        </span>
      </div>

      <time
        :datetime="item.createdAt"
        class="text-[10px] text-muted/60 whitespace-nowrap uppercase tracking-tighter"
      >
        {{ formatDateTime(item.createdAt) }}
      </time>
    </div>

    <template #footer>
      <UButton
        label="Add to Dashboard"
        :icon="item.payload.kind === 'node' ? 'i-lucide-plus' : 'i-lucide-download'"
        block
        color="neutral"
        variant="subtle"
        :loading="loading"
        class="group-hover:bg-primary group-hover:text-white transition-colors"
        @click="$emit('insert', item)"
      />
    </template>
  </UCard>
</template>
