// apps/web/app/components/workspace/node/blocks/WorkspaceAiPromptBlockEditor.vue
<script setup lang="ts">
import type { WorkspaceAiPromptBlock } from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";
import { getErrorMessage } from "~/utils/get-error-message";
import { formatDateTime } from "~/utils/format-date-time";

const props = defineProps<{
    block: WorkspaceAiPromptBlock;
    tabId: string;
}>();

const { mutateTypedBlock, runPromptBlock, getBlockOperationState } =
    useWorkspaceNodeEditorContext();

const runError = ref<string | null>(null);

const operationState = computed(() =>
    getBlockOperationState(props.tabId, props.block.id),
);

const hasPrompt = computed(() => props.block.prompt.trim().length > 0);

const contextModeLabel = computed(() =>
    props.block.includeContext ? "Uses current node" : "Standalone prompt",
);

async function handleRun() {
    if (operationState.value.pending || !hasPrompt.value) {
        return;
    }

    runError.value = null;

    try {
        await runPromptBlock(props.tabId, props.block.id);
    } catch (error) {
        runError.value = getErrorMessage(error, "Could not run this prompt.");
    }
}

function updateIncludeContext(value: boolean | string | undefined) {
    mutateTypedBlock(props.tabId, props.block.id, "ai-prompt", (block) => {
        block.includeContext = Boolean(value);
    });
}

function updatePrompt(value: string | number | undefined) {
    mutateTypedBlock(props.tabId, props.block.id, "ai-prompt", (block) => {
        block.prompt = String(value ?? "");
    });
}
</script>

<template>
    <div class="space-y-6">
        <div class="relative group">
            <div
                class="absolute -inset-1 rounded-[32px] bg-gradient-to-r from-primary/20 via-primary/5 to-primary/20 opacity-30 blur-xl transition-all group-focus-within:opacity-60"
            />
            <div
                class="relative rounded-3xl border border-primary/20 bg-default/80 p-5 backdrop-blur-sm"
            >
                <div
                    class="mb-4 flex flex-wrap items-start justify-between gap-3 px-1"
                >
                    <div class="space-y-3">
                        <div class="flex items-center gap-2 text-primary">
                            <UIcon name="i-lucide-sparkles" class="size-5" />
                            <h3
                                class="text-[10px] font-bold uppercase tracking-[0.2em]"
                            >
                                AI Strategist
                            </h3>
                        </div>

                        <div class="flex flex-wrap items-center gap-2">
                            <UBadge variant="subtle" class="rounded-2xl">
                                {{ contextModeLabel }}
                            </UBadge>
                            <UBadge
                                v-if="operationState.pending"
                                color="primary"
                                variant="soft"
                                class="rounded-2xl"
                            >
                                {{ operationState.label || "Running prompt" }}
                            </UBadge>
                        </div>

                        <label
                            class="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                        >
                            <UCheckbox
                                :model-value="block.includeContext"
                                size="sm"
                                @update:model-value="
                                    updateIncludeContext($event)
                                "
                            />
                            <span>Include current node context</span>
                        </label>
                    </div>

                    <UButton
                        color="primary"
                        icon="i-lucide-zap"
                        size="sm"
                        class="rounded-full px-5 shadow-lg shadow-primary/20"
                        :loading="operationState.pending"
                        :disabled="!hasPrompt || operationState.pending"
                        @click="handleRun"
                    >
                        {{
                            operationState.pending
                                ? "Running prompt"
                                : "Run prompt"
                        }}
                    </UButton>
                </div>

                <UTextarea
                    :model-value="block.prompt"
                    variant="none"
                    placeholder="Ask for a structured summary, next actions, critique, or standalone answer..."
                    autoresize
                    :max-rows="10"
                    class="w-full"
                    :ui="{
                        base: 'p-0 text-base text-toned font-medium leading-relaxed placeholder:text-muted/40',
                    }"
                    @update:model-value="updatePrompt($event)"
                />
            </div>
        </div>

        <UAlert
            v-if="runError"
            color="error"
            variant="soft"
            icon="i-lucide-alert-circle"
            :title="runError"
            class="rounded-3xl"
        />

        <div v-if="block.latestOutput" class="space-y-3">
            <div class="flex items-center justify-between gap-3 px-2">
                <div class="flex items-center gap-2">
                    <UIcon
                        name="i-lucide-terminal"
                        class="size-4 text-muted/60"
                    />
                    <h4
                        class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                    >
                        Latest result
                    </h4>
                </div>
                <UBadge variant="subtle" class="rounded-2xl">
                    {{ contextModeLabel }}
                </UBadge>
            </div>

            <div
                class="rounded-3xl border border-muted/20 bg-elevated/10 p-6 shadow-sm"
            >
                <div
                    class="prose prose-sm max-w-none whitespace-pre-wrap text-toned leading-relaxed"
                >
                    {{ block.latestOutput }}
                </div>
            </div>
        </div>

        <div v-if="block.outputHistory.length > 0" class="space-y-3">
            <div class="flex items-center justify-between px-2">
                <div class="flex items-center gap-2">
                    <UIcon
                        name="i-lucide-history"
                        class="size-4 text-muted/60"
                    />
                    <h4
                        class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                    >
                        Prompt history
                    </h4>
                </div>
                <span
                    class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/40"
                >
                    {{ block.outputHistory.length }} entries
                </span>
            </div>

            <div class="grid gap-3">
                <div
                    v-for="entry in block.outputHistory"
                    :key="entry.id"
                    class="rounded-2xl border border-muted/20 bg-default/40 p-4"
                >
                    <div class="mb-2 flex items-center justify-between gap-3">
                        <span
                            class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
                        >
                            {{ formatDateTime(entry.createdAt) }}
                        </span>
                    </div>
                    <p class="text-xs italic text-toned/80 line-clamp-2">
                        "{{ entry.prompt }}"
                    </p>
                    <div
                        class="mt-2 whitespace-pre-wrap text-xs leading-relaxed text-toned line-clamp-4"
                    >
                        {{ entry.output }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// apps/web/src/components/workspace/node/blocks/workspace-ai-prompt-block-editor.tsx
import type { WorkspaceAiPromptBlock } from "@brainiac/workspace";
import { AlertCircle, History, Sparkles, Terminal, Zap } from "lucide-react";
import { useMemo, useState } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { BlockCheckbox } from "@/components/workspace/node/blocks/shared/block-checkbox";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { formatDateTime } from "@/lib/utils/format-date-time";
import { getErrorMessage } from "@/lib/utils/get-error-message";

export function WorkspaceAiPromptBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceAiPromptBlock>) {
  const { mutateTypedBlock, runPromptBlock, getBlockOperationState } =
    useWorkspaceNodeEditorContext();
  const [runError, setRunError] = useState<string | null>(null);

  const operationState = getBlockOperationState(tabId, block.id);
  const hasPrompt = block.prompt.trim().length > 0;
  const contextModeLabel = useMemo(
    () => (block.includeContext ? "Uses current node" : "Standalone prompt"),
    [block.includeContext],
  );

  async function handleRun() {
    if (operationState.pending || !hasPrompt) {
      return;
    }
    setRunError(null);
    try {
      await runPromptBlock(tabId, block.id);
    } catch (error) {
      setRunError(getErrorMessage(error, "Could not run this prompt."));
    }
  }

  return (
    <div className="space-y-6">
      <div className="group relative">
        <div className="absolute -inset-1 rounded-[32px] bg-gradient-to-r from-primary/20 via-primary/5 to-primary/20 opacity-30 blur-xl transition-all group-focus-within:opacity-60" />
        <div className="relative rounded-3xl border border-primary/20 bg-background/80 p-5 backdrop-blur-sm">
          <div className="mb-4 flex flex-wrap items-start justify-between gap-3 px-1">
            <div className="space-y-3">
              <div className="flex items-center gap-2 text-primary">
                <Sparkles className="size-5" />
                <h3 className="text-[10px] font-bold uppercase tracking-[0.2em]">AI Strategist</h3>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <Badge variant="secondary" className="rounded-2xl">
                  {contextModeLabel}
                </Badge>
                {operationState.pending ? (
                  <Badge variant="secondary" className="rounded-2xl">
                    {operationState.label || "Running prompt"}
                  </Badge>
                ) : null}
              </div>
              <label className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                <BlockCheckbox
                  checked={block.includeContext}
                  onCheckedChange={(checked) =>
                    mutateTypedBlock(tabId, block.id, "ai-prompt", (entry) => {
                      entry.includeContext = checked;
                    })
                  }
                />
                <span>Include current node context</span>
              </label>
            </div>
            <Button
              type="button"
              size="sm"
              className="rounded-full px-5 shadow-lg shadow-primary/20"
              disabled={!hasPrompt || operationState.pending}
              onClick={handleRun}
            >
              <Zap />
              {operationState.pending ? "Running prompt" : "Run prompt"}
            </Button>
          </div>
          <Textarea
            value={block.prompt}
            placeholder="Ask for a structured summary, next actions, critique, or standalone answer..."
            className="min-h-[120px] w-full resize-y border-0 bg-transparent p-0 text-base leading-relaxed font-medium shadow-none focus-visible:ring-0"
            onChange={(event) =>
              mutateTypedBlock(tabId, block.id, "ai-prompt", (entry) => {
                entry.prompt = event.target.value;
              })
            }
          />
        </div>
      </div>

      {runError ? (
        <div className="flex items-start gap-3 rounded-3xl border border-destructive/30 bg-destructive/10 p-4 text-destructive">
          <AlertCircle className="mt-0.5 size-5 shrink-0" />
          <p className="text-sm font-medium">{runError}</p>
        </div>
      ) : null}

      {block.latestOutput ? (
        <div className="space-y-3">
          <div className="flex items-center justify-between gap-3 px-2">
            <div className="flex items-center gap-2">
              <Terminal className="size-4 text-muted-foreground/60" />
              <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                Latest result
              </h4>
            </div>
            <Badge variant="secondary" className="rounded-2xl">
              {contextModeLabel}
            </Badge>
          </div>
          <div className="rounded-3xl border border-muted/20 bg-muted/10 p-6 shadow-sm">
            <div className="prose prose-sm max-w-none leading-relaxed whitespace-pre-wrap text-foreground">
              {block.latestOutput}
            </div>
          </div>
        </div>
      ) : null}

      {block.outputHistory.length > 0 ? (
        <div className="space-y-3">
          <div className="flex items-center justify-between px-2">
            <div className="flex items-center gap-2">
              <History className="size-4 text-muted-foreground/60" />
              <h4 className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                Prompt history
              </h4>
            </div>
            <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/40">
              {block.outputHistory.length} entries
            </span>
          </div>
          <div className="grid gap-3">
            {block.outputHistory.map((entry) => (
              <div
                key={entry.id}
                className="rounded-2xl border border-muted/20 bg-background/40 p-4"
              >
                <div className="mb-2 flex items-center justify-between gap-3">
                  <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                    {formatDateTime(entry.createdAt)}
                  </span>
                </div>
                <p className="line-clamp-2 text-xs text-foreground/80 italic">"{entry.prompt}"</p>
                <div className="mt-2 line-clamp-4 text-xs leading-relaxed whitespace-pre-wrap text-foreground">
                  {entry.output}
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}
