// apps/web/app/components/workspace/node/blocks/WorkspaceAuthorityScorecardBlockEditor.vue
<script setup lang="ts">
import {
  WORKSPACE_AUTHORITY_SCORECARD_METRICS,
  getAuthorityScorecardSummary,
  getAuthorityScoreMetricProgress,
  workspaceAuthorityScoreMetricIcons,
  workspaceAuthorityScoreMetricLabels,
  type WorkspaceAuthorityScoreMetricKey,
  type WorkspaceAuthorityScorecardBlock,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
  block: WorkspaceAuthorityScorecardBlock;
  tabId: string;
}>();

const { mutateBlock } = useWorkspaceNodeEditorContext();

const summary = computed(() => getAuthorityScorecardSummary(props.block));
const metricKeys = WORKSPACE_AUTHORITY_SCORECARD_METRICS;

function formatValue(value: number) {
  return value.toLocaleString("en-US");
}

function toInteger(value: string, fallback: number) {
  const numeric = Number(value);

  if (!Number.isFinite(numeric)) {
    return fallback;
  }

  return Math.max(0, Math.round(numeric));
}

function getProgressTone(progress: number) {
  if (progress >= 75) {
    return {
      badge: "text-success",
      surface: "border-success/25 bg-success/5",
      progress: "success" as const,
    };
  }

  if (progress >= 40) {
    return {
      badge: "text-warning",
      surface: "border-warning/25 bg-warning/5",
      progress: "warning" as const,
    };
  }

  return {
    badge: "text-error",
    surface: "border-error/25 bg-error/5",
    progress: "error" as const,
  };
}

function incrementMetric(metricKey: WorkspaceAuthorityScoreMetricKey) {
  mutateBlock(props.tabId, props.block.id, (block) => {
    if (block.type !== "authority-scorecard") {
      return;
    }

    block.metrics[metricKey].value += 1;
  });
}

function updateMetricValue(metricKey: WorkspaceAuthorityScoreMetricKey, value: string) {
  mutateBlock(props.tabId, props.block.id, (block) => {
    if (block.type !== "authority-scorecard") {
      return;
    }

    block.metrics[metricKey].value = toInteger(value, block.metrics[metricKey].value);
  });
}

function updateMetricTarget(metricKey: WorkspaceAuthorityScoreMetricKey, value: string) {
  mutateBlock(props.tabId, props.block.id, (block) => {
    if (block.type !== "authority-scorecard") {
      return;
    }

    block.metrics[metricKey].target = Math.max(
      1,
      toInteger(value, block.metrics[metricKey].target),
    );
  });
}
</script>

<template>
  <div class="space-y-6">
    <!-- Summary Stats -->
    <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <div class="rounded-2xl bg-primary/10 border border-primary/20 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-primary/70">On Target</p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-primary">
          {{ summary.atTargetCount }}/{{ summary.metricCount }}
        </p>
      </div>

      <div class="rounded-2xl bg-secondary/10 border border-secondary/20 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-secondary/80">
          Avg Progress
        </p>
        <p class="mt-2 text-xl sm:text-2xl font-black tracking-tight text-secondary">
          {{ summary.averageProgress }}%
        </p>
      </div>

      <div class="rounded-2xl bg-success/10 border border-success/20 p-4">
        <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-success/70">Strongest</p>
        <p class="mt-2 text-lg sm:text-xl font-black tracking-tight text-success">
          {{
            summary.strongestMetric
              ? workspaceAuthorityScoreMetricLabels[summary.strongestMetric]
              : "None"
          }}
        </p>
      </div>
    </div>

    <!-- Section Header -->
    <div class="flex items-center justify-between gap-3 px-1">
      <div>
        <h2 class="text-sm font-black text-highlighted tracking-tight">Authority Metrics</h2>
        <p class="text-xs text-muted">
          Track key authority indicators with quick increments and precise editing.
        </p>
      </div>
    </div>

    <!-- Metric Cards -->
    <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
      <div
        v-for="metricKey in metricKeys"
        :key="metricKey"
        class="rounded-2xl border p-4 transition-all"
        :class="getProgressTone(summary.metrics[metricKey].progress).surface"
      >
        <!-- Card Header: Icon, Label, Value, Progress Badge, Increment Button -->
        <div class="flex items-start justify-between gap-3 mb-4">
          <div class="flex items-center gap-2.5 min-w-0">
            <div
              class="flex size-9 items-center justify-center rounded-xl border border-muted/20 bg-default/80 text-toned shrink-0"
            >
              <UIcon :name="workspaceAuthorityScoreMetricIcons[metricKey]" class="size-4.5" />
            </div>

            <div class="min-w-0">
              <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">
                {{ workspaceAuthorityScoreMetricLabels[metricKey] }}
              </p>
              <p
                class="mt-0.5 text-xl sm:text-2xl font-black tracking-tight truncate"
                :class="getProgressTone(summary.metrics[metricKey].progress).badge"
              >
                {{ formatValue(block.metrics[metricKey].value) }}
              </p>
            </div>
          </div>

          <div class="flex items-center gap-2 shrink-0">
            <UBadge
              :color="getProgressTone(summary.metrics[metricKey].progress).progress"
              variant="soft"
              size="sm"
              class="rounded-xl px-2.5 py-0.5"
            >
              {{ summary.metrics[metricKey].progress }}%
            </UBadge>
            <UButton
              color="primary"
              variant="soft"
              icon="i-lucide-plus"
              size="sm"
              class="rounded-lg"
              aria-label="Increment {{ workspaceAuthorityScoreMetricLabels[metricKey] }}"
              @click="incrementMetric(metricKey)"
            />
          </div>
        </div>

        <!-- Progress Bar -->
        <div class="mb-4 space-y-2">
          <div
            class="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
          >
            <span>Progress</span>
            <span>Target: {{ formatValue(block.metrics[metricKey].target) }}</span>
          </div>
          <UProgress
            :model-value="summary.metrics[metricKey].progress"
            size="sm"
            class="rounded-full"
            :color="getProgressTone(summary.metrics[metricKey].progress).progress"
          />
        </div>

        <!-- Editable Inputs -->
        <div class="grid grid-cols-2 gap-3">
          <div>
            <label
              :for="'current-' + metricKey"
              class="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
            >
              Current
            </label>
            <UInput
              :id="'current-' + metricKey"
              :model-value="String(block.metrics[metricKey].value)"
              type="number"
              size="sm"
              class="rounded-xl"
              @update:model-value="updateMetricValue(metricKey, $event as string)"
            />
          </div>

          <div>
            <label
              :for="'target-' + metricKey"
              class="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60"
            >
              Target
            </label>
            <UInput
              :id="'target-' + metricKey"
              :model-value="String(block.metrics[metricKey].target)"
              type="number"
              size="sm"
              class="rounded-xl"
              @update:model-value="updateMetricTarget(metricKey, $event as string)"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// apps/web/src/components/workspace/node/blocks/workspace-authority-scorecard-block-editor.tsx
import {
  WORKSPACE_AUTHORITY_SCORECARD_METRICS,
  getAuthorityScorecardSummary,
  workspaceAuthorityScoreMetricLabels,
  type WorkspaceAuthorityScoreMetricKey,
  type WorkspaceAuthorityScorecardBlock,
} from "@brainiac/workspace";
import {
  Headphones,
  Mic2,
  Newspaper,
  PenSquare,
  Plus,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";
import { useMemo } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { BlockProgressBar } from "@/components/workspace/node/blocks/shared/block-progress-bar";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

const metricIcons: Record<WorkspaceAuthorityScoreMetricKey, LucideIcon> = {
  posts: PenSquare,
  videos: Video,
  speakingGigs: Mic2,
  podcastAppearances: Headphones,
  mediaFeatures: Newspaper,
  followers: Users,
};

function formatValue(value: number) {
  return value.toLocaleString("en-US");
}

function toInteger(value: string, fallback: number) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }
  return Math.max(0, Math.round(numeric));
}

function getProgressTone(progress: number) {
  if (progress >= 75) {
    return {
      badge: "text-success",
      surface: "border-success/25 bg-success/5",
      progressClass: "bg-success",
    };
  }

  if (progress >= 40) {
    return {
      badge: "text-warning",
      surface: "border-warning/25 bg-warning/5",
      progressClass: "bg-warning",
    };
  }

  return {
    badge: "text-destructive",
    surface: "border-destructive/25 bg-destructive/5",
    progressClass: "bg-destructive",
  };
}

export function WorkspaceAuthorityScorecardBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceAuthorityScorecardBlock>) {
  const { mutateBlock } = useWorkspaceNodeEditorContext();
  const summary = useMemo(() => getAuthorityScorecardSummary(block), [block]);

  function incrementMetric(metricKey: WorkspaceAuthorityScoreMetricKey) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "authority-scorecard") {
        return;
      }
      entry.metrics[metricKey].value += 1;
    });
  }

  function updateMetricValue(metricKey: WorkspaceAuthorityScoreMetricKey, value: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "authority-scorecard") {
        return;
      }
      entry.metrics[metricKey].value = toInteger(value, entry.metrics[metricKey].value);
    });
  }

  function updateMetricTarget(metricKey: WorkspaceAuthorityScoreMetricKey, value: string) {
    mutateBlock(tabId, block.id, (entry) => {
      if (entry.type !== "authority-scorecard") {
        return;
      }
      entry.metrics[metricKey].target = Math.max(
        1,
        toInteger(value, entry.metrics[metricKey].target),
      );
    });
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-2xl border border-primary/20 bg-primary/10 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary/70">
            On Target
          </p>
          <p className="mt-2 text-xl font-black tracking-tight text-primary sm:text-2xl">
            {summary.atTargetCount}/{summary.metricCount}
          </p>
        </div>

        <div className="rounded-2xl border border-secondary/20 bg-secondary/10 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-secondary/80">
            Avg Progress
          </p>
          <p className="mt-2 text-xl font-black tracking-tight text-secondary sm:text-2xl">
            {summary.averageProgress}%
          </p>
        </div>

        <div className="rounded-2xl border border-success/20 bg-success/10 p-4">
          <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-success/70">
            Strongest
          </p>
          <p className="mt-2 text-lg font-black tracking-tight text-success sm:text-xl">
            {summary.strongestMetric
              ? workspaceAuthorityScoreMetricLabels[summary.strongestMetric]
              : "None"}
          </p>
        </div>
      </div>

      <div className="flex items-center justify-between gap-3 px-1">
        <div>
          <h2 className="text-sm font-black tracking-tight text-foreground">Authority Metrics</h2>
          <p className="text-xs text-muted-foreground">
            Track key authority indicators with quick increments and precise editing.
          </p>
        </div>
      </div>

      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
        {WORKSPACE_AUTHORITY_SCORECARD_METRICS.map((metricKey) => {
          const tone = getProgressTone(summary.metrics[metricKey].progress);
          const Icon = metricIcons[metricKey];

          return (
            <div
              key={metricKey}
              className={cn("rounded-2xl border p-4 transition-all", tone.surface)}
            >
              <div className="mb-4 flex items-start justify-between gap-3">
                <div className="flex min-w-0 items-center gap-2.5">
                  <div className="flex size-9 shrink-0 items-center justify-center rounded-xl border border-muted/20 bg-background/80 text-muted-foreground">
                    <Icon className="size-4.5" />
                  </div>

                  <div className="min-w-0">
                    <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                      {workspaceAuthorityScoreMetricLabels[metricKey]}
                    </p>
                    <p
                      className={cn(
                        "mt-0.5 truncate text-xl font-black tracking-tight sm:text-2xl",
                        tone.badge,
                      )}
                    >
                      {formatValue(block.metrics[metricKey].value)}
                    </p>
                  </div>
                </div>

                <div className="flex shrink-0 items-center gap-2">
                  <Badge variant="secondary" className="rounded-xl px-2.5 py-0.5">
                    {summary.metrics[metricKey].progress}%
                  </Badge>
                  <Button
                    type="button"
                    variant="secondary"
                    size="sm"
                    className="rounded-lg"
                    aria-label={`Increment ${workspaceAuthorityScoreMetricLabels[metricKey]}`}
                    onClick={() => incrementMetric(metricKey)}
                  >
                    <Plus />
                  </Button>
                </div>
              </div>

              <div className="mb-4 space-y-2">
                <div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
                  <span>Progress</span>
                  <span>Target: {formatValue(block.metrics[metricKey].target)}</span>
                </div>
                <BlockProgressBar
                  value={summary.metrics[metricKey].progress}
                  max={100}
                  className={tone.progressClass}
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label
                    htmlFor={`current-${metricKey}`}
                    className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
                  >
                    Current
                  </Label>
                  <Input
                    id={`current-${metricKey}`}
                    type="number"
                    value={String(block.metrics[metricKey].value)}
                    className="rounded-xl"
                    onChange={(event) => updateMetricValue(metricKey, event.target.value)}
                  />
                </div>

                <div>
                  <Label
                    htmlFor={`target-${metricKey}`}
                    className="mb-1 block text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60"
                  >
                    Target
                  </Label>
                  <Input
                    id={`target-${metricKey}`}
                    type="number"
                    value={String(block.metrics[metricKey].target)}
                    className="rounded-xl"
                    onChange={(event) => updateMetricTarget(metricKey, event.target.value)}
                  />
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
