// apps/web/app/components/workspace/node/blocks/WorkspaceProsConsBlockEditor.vue
<script setup lang="ts">
import {
  createWorkspaceProsConsItem,
  getProsConsSummary,
  type WorkspaceProsConsBlock,
} from "@brainiac/workspace";

import { useWorkspaceNodeEditorContext } from "~/components/workspace/node/context";

const props = defineProps<{
  block: WorkspaceProsConsBlock;
  tabId: string;
}>();

const { mutateTypedBlock } = useWorkspaceNodeEditorContext();

const summary = computed(() => getProsConsSummary(props.block));
const totalWeight = computed(() =>
  Math.max(summary.value.prosWeight + summary.value.consWeight, 1),
);
const verdictLabel = computed(() => {
  if (summary.value.verdict === "do-it") {
    return "DO IT";
  }

  if (summary.value.verdict === "dont") {
    return "DON'T";
  }

  return "TIE";
});
const verdictClass = computed(() => {
  if (summary.value.verdict === "do-it") {
    return "border-success/30 bg-success/10 text-success";
  }

  if (summary.value.verdict === "dont") {
    return "border-error/30 bg-error/10 text-error";
  }

  return "border-warning/30 bg-warning/10 text-warning";
});

function addItem(list: "pros" | "cons") {
  mutateTypedBlock(props.tabId, props.block.id, "pros-cons", (entry) => {
    entry[list].push(createWorkspaceProsConsItem({ text: "" }));
  });
}

function updateItemText(list: "pros" | "cons", itemId: string, value: string | number | undefined) {
  mutateTypedBlock(props.tabId, props.block.id, "pros-cons", (entry) => {
    const target = entry[list].find((candidate) => candidate.id === itemId);

    if (!target) {
      return;
    }

    target.text = String(value ?? "").slice(0, 240);
  });
}

function updateItemWeight(list: "pros" | "cons", itemId: string, weight: number) {
  mutateTypedBlock(props.tabId, props.block.id, "pros-cons", (entry) => {
    const target = entry[list].find((candidate) => candidate.id === itemId);

    if (!target) {
      return;
    }

    target.weight = Math.min(5, Math.max(1, Math.round(weight)));
  });
}

function removeItem(list: "pros" | "cons", itemId: string) {
  mutateTypedBlock(props.tabId, props.block.id, "pros-cons", (entry) => {
    entry[list] = entry[list].filter((candidate) => candidate.id !== itemId);
  });
}

function getWeightButtonClass(list: "pros" | "cons", currentWeight: number, value: number) {
  const isActive = value <= currentWeight;

  if (list === "pros") {
    return isActive
      ? "border-success/30 bg-success text-white"
      : "border-muted/20 bg-default/60 text-muted/70 hover:border-success/30 hover:text-success";
  }

  return isActive
    ? "border-error/30 bg-error text-white"
    : "border-muted/20 bg-default/60 text-muted/70 hover:border-error/30 hover:text-error";
}
</script>

<template>
  <div class="space-y-8">
    <div
      class="rounded-3xl border border-muted/20 p-6 transition-colors space-y-5"
      :class="verdictClass"
    >
      <div class="flex flex-wrap items-center gap-2">
        <UBadge variant="subtle" class="rounded-2xl"> {{ block.pros.length }} pros </UBadge>
        <UBadge color="neutral" variant="soft" class="rounded-2xl">
          {{ block.cons.length }} cons
        </UBadge>
        <UBadge color="success" variant="soft" class="rounded-2xl">
          {{ summary.prosWeight }} pro weight
        </UBadge>
        <UBadge color="error" variant="soft" class="rounded-2xl">
          {{ summary.consWeight }} con weight
        </UBadge>
      </div>

      <div class="mb-4 flex items-center justify-between gap-4">
        <div>
          <p class="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Verdict</p>
          <p class="mt-1 text-2xl sm:text-3xl font-black tracking-tight">
            {{ verdictLabel }}
          </p>
        </div>
        <div class="flex-1 px-4 sm:px-8">
          <div class="relative h-2 overflow-hidden rounded-full bg-muted/20">
            <div
              class="absolute inset-y-0 left-0 bg-success transition-all duration-500"
              :style="{
                width: `${(summary.prosWeight / totalWeight) * 100}%`,
              }"
            />
            <div
              class="absolute inset-y-0 right-0 bg-error transition-all duration-500"
              :style="{
                width: `${(summary.consWeight / totalWeight) * 100}%`,
              }"
            />
          </div>
          <div class="mt-4 text-center">
            <p class="mb-1 text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">
              Score Delta
            </p>
            <p class="text-lg font-black tracking-tight">
              {{ summary.totalScore > 0 ? "+" : "" }}{{ summary.totalScore }}
            </p>
          </div>
        </div>
        <div class="text-right">
          <p class="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Current Signal</p>
          <p class="mt-1 text-2xl sm:text-3xl font-black tracking-tight">
            {{ summary.verdict === "tie" ? "Balanced" : verdictLabel }}
          </p>
        </div>
      </div>

      <div class="grid gap-4 sm:grid-cols-2">
        <div>
          <p class="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Pro score</p>
          <p class="mt-1 text-xl sm:text-2xl font-black tracking-tight">
            {{ summary.prosWeight }}
          </p>
        </div>
        <div>
          <p class="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Con score</p>
          <p class="mt-1 text-xl sm:text-2xl font-black tracking-tight">
            {{ summary.consWeight }}
          </p>
        </div>
      </div>
    </div>

    <div class="grid gap-6 lg:grid-cols-2">
      <section class="space-y-4">
        <div class="flex items-center justify-between px-2">
          <div class="flex items-center gap-2 text-success">
            <UIcon name="i-lucide-plus-circle" class="size-5" />
            <h3 class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">Pros</h3>
          </div>
          <UButton
            color="success"
            variant="soft"
            icon="i-lucide-plus"
            size="xs"
            class="rounded-full px-4"
            @click="addItem('pros')"
          >
            Add Point
          </UButton>
        </div>

        <div
          v-for="item in block.pros"
          :key="item.id"
          class="group space-y-3 rounded-2xl border border-muted/20 bg-default/40 p-3 transition-all hover:bg-default/60"
        >
          <div class="flex items-start gap-3">
            <UInput
              :model-value="item.text"
              variant="none"
              placeholder="Add a reason in favor..."
              class="flex-1"
              :ui="{
                base: 'px-0 text-sm text-highlighted font-semibold',
              }"
              @update:model-value="updateItemText('pros', item.id, $event)"
            />

            <UButton
              color="neutral"
              variant="ghost"
              icon="i-lucide-trash-2"
              size="xs"
              class="rounded-lg hover:text-error"
              aria-label="Remove pro point"
              @click="removeItem('pros', item.id)"
            />
          </div>

          <div class="flex flex-wrap items-center justify-between gap-3">
            <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-success/70">Weight</p>

            <div class="flex flex-wrap items-center gap-2">
              <button
                v-for="weight in 5"
                :key="weight"
                type="button"
                class="min-w-8 rounded-full border px-2.5 py-1 text-[10px] font-bold transition-colors"
                :class="getWeightButtonClass('pros', item.weight, weight)"
                :aria-label="`Set pro weight to ${weight}`"
                @click="updateItemWeight('pros', item.id, weight)"
              >
                {{ weight }}
              </button>
            </div>
          </div>
        </div>
      </section>

      <section class="space-y-4">
        <div class="flex items-center justify-between px-2">
          <div class="flex items-center gap-2 text-error">
            <UIcon name="i-lucide-minus-circle" class="size-5" />
            <h3 class="text-[10px] font-bold uppercase tracking-[0.2em] text-muted/60">Cons</h3>
          </div>
          <UButton
            color="error"
            variant="soft"
            icon="i-lucide-plus"
            size="xs"
            class="rounded-full px-4"
            @click="addItem('cons')"
          >
            Add Point
          </UButton>
        </div>

        <div
          v-for="item in block.cons"
          :key="item.id"
          class="group space-y-3 rounded-2xl border border-muted/20 bg-default/40 p-3 transition-all hover:bg-default/60"
        >
          <div class="flex items-start gap-3">
            <UInput
              :model-value="item.text"
              variant="none"
              placeholder="Add a risk or downside..."
              class="flex-1"
              :ui="{
                base: 'px-0 text-sm text-highlighted font-semibold',
              }"
              @update:model-value="updateItemText('cons', item.id, $event)"
            />

            <UButton
              color="neutral"
              variant="ghost"
              icon="i-lucide-trash-2"
              size="xs"
              class="rounded-lg hover:text-error"
              aria-label="Remove con point"
              @click="removeItem('cons', item.id)"
            />
          </div>

          <div class="flex flex-wrap items-center justify-between gap-3">
            <p class="text-[10px] font-bold uppercase tracking-[0.2em] text-error/70">Weight</p>

            <div class="flex flex-wrap items-center gap-2">
              <button
                v-for="weight in 5"
                :key="weight"
                type="button"
                class="min-w-8 rounded-full border px-2.5 py-1 text-[10px] font-bold transition-colors"
                :class="getWeightButtonClass('cons', item.weight, weight)"
                :aria-label="`Set con weight to ${weight}`"
                @click="updateItemWeight('cons', item.id, weight)"
              >
                {{ weight }}
              </button>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

// apps/web/src/components/workspace/node/blocks/workspace-pros-cons-block-editor.tsx
import {
  createWorkspaceProsConsItem,
  getProsConsSummary,
  type WorkspaceProsConsBlock,
} from "@brainiac/workspace";
import { MinusCircle, Plus, PlusCircle, Trash2 } from "lucide-react";
import { useMemo } from "react";

import type { WorkspaceBlockEditorProps } from "@/components/workspace/node/block-editor-props";
import { useWorkspaceNodeEditorContext } from "@/components/workspace/node/context";
import {
  ProsConsBalanceBar,
  ProsConsWeightButtons,
} from "@/components/workspace/node/blocks/shared/pros-cons-helpers";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export function WorkspaceProsConsBlockEditor({
  block,
  tabId,
}: WorkspaceBlockEditorProps<WorkspaceProsConsBlock>) {
  const { mutateTypedBlock } = useWorkspaceNodeEditorContext();
  const summary = useMemo(() => getProsConsSummary(block), [block]);

  const verdictLabel =
    summary.verdict === "do-it" ? "DO IT" : summary.verdict === "dont" ? "DON'T" : "TIE";

  const verdictClass =
    summary.verdict === "do-it"
      ? "border-success/30 bg-success/10 text-success"
      : summary.verdict === "dont"
        ? "border-destructive/30 bg-destructive/10 text-destructive"
        : "border-warning/30 bg-warning/10 text-warning";

  function addItem(list: "pros" | "cons") {
    mutateTypedBlock(tabId, block.id, "pros-cons", (entry) => {
      entry[list].push(createWorkspaceProsConsItem({ text: "" }));
    });
  }

  function updateItemText(list: "pros" | "cons", itemId: string, value: string) {
    mutateTypedBlock(tabId, block.id, "pros-cons", (entry) => {
      const target = entry[list].find((candidate) => candidate.id === itemId);
      if (target) {
        target.text = value.slice(0, 240);
      }
    });
  }

  function updateItemWeight(list: "pros" | "cons", itemId: string, weight: number) {
    mutateTypedBlock(tabId, block.id, "pros-cons", (entry) => {
      const target = entry[list].find((candidate) => candidate.id === itemId);
      if (target) {
        target.weight = Math.min(5, Math.max(1, Math.round(weight)));
      }
    });
  }

  function removeItem(list: "pros" | "cons", itemId: string) {
    mutateTypedBlock(tabId, block.id, "pros-cons", (entry) => {
      entry[list] = entry[list].filter((candidate) => candidate.id !== itemId);
    });
  }

  function renderList(list: "pros" | "cons", title: string, placeholder: string) {
    const items = block[list];
    const isPros = list === "pros";

    return (
      <section className="space-y-4">
        <div className="flex items-center justify-between px-2">
          <div className={cn("flex items-center gap-2", isPros ? "text-success" : "text-destructive")}>
            {isPros ? <PlusCircle className="size-5" /> : <MinusCircle className="size-5" />}
            <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/60">
              {title}
            </h3>
          </div>
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="rounded-full px-4"
            onClick={() => addItem(list)}
          >
            <Plus />
            Add Point
          </Button>
        </div>

        {items.map((item) => (
          <div
            key={item.id}
            className="group space-y-3 rounded-2xl border border-muted/20 bg-background/40 p-3 transition-all hover:bg-background/60"
          >
            <div className="flex items-start gap-3">
              <Input
                value={item.text}
                placeholder={placeholder}
                className="flex-1 border-0 bg-transparent px-0 text-sm font-semibold text-foreground shadow-none focus-visible:ring-0"
                onChange={(event) => updateItemText(list, item.id, event.target.value)}
              />
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="rounded-lg hover:text-destructive"
                aria-label={`Remove ${list === "pros" ? "pro" : "con"} point`}
                onClick={() => removeItem(list, item.id)}
              >
                <Trash2 />
              </Button>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <p
                className={cn(
                  "text-[10px] font-bold uppercase tracking-[0.2em]",
                  isPros ? "text-success/70" : "text-destructive/70",
                )}
              >
                Weight
              </p>
              <ProsConsWeightButtons
                list={list}
                currentWeight={item.weight}
                onWeightChange={(weight) => updateItemWeight(list, item.id, weight)}
              />
            </div>
          </div>
        ))}
      </section>
    );
  }

  return (
    <div className="space-y-8">
      <div className={cn("space-y-5 rounded-3xl border p-6 transition-colors", verdictClass)}>
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="secondary" className="rounded-2xl">
            {block.pros.length} pros
          </Badge>
          <Badge variant="secondary" className="rounded-2xl">
            {block.cons.length} cons
          </Badge>
          <Badge variant="success" className="rounded-2xl">
            {summary.prosWeight} pro weight
          </Badge>
          <Badge variant="destructive" className="rounded-2xl">
            {summary.consWeight} con weight
          </Badge>
        </div>

        <div className="mb-4 flex items-center justify-between gap-4">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Verdict</p>
            <p className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{verdictLabel}</p>
          </div>
          <div className="flex-1 px-4 sm:px-8">
            <ProsConsBalanceBar prosWeight={summary.prosWeight} consWeight={summary.consWeight} />
            <div className="mt-4 text-center">
              <p className="mb-1 text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">
                Score Delta
              </p>
              <p className="text-lg font-black tracking-tight">
                {summary.totalScore > 0 ? "+" : ""}
                {summary.totalScore}
              </p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">
              Current Signal
            </p>
            <p className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">
              {summary.verdict === "tie" ? "Balanced" : verdictLabel}
            </p>
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Pro score</p>
            <p className="mt-1 text-xl font-black tracking-tight sm:text-2xl">
              {summary.prosWeight}
            </p>
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] opacity-70">Con score</p>
            <p className="mt-1 text-xl font-black tracking-tight sm:text-2xl">
              {summary.consWeight}
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {renderList("pros", "Pros", "Add a reason in favor...")}
        {renderList("cons", "Cons", "Add a risk or downside...")}
      </div>
    </div>
  );
}
